### ISSUE TITLE
VoiceOver announces a tab is "selected" when it is visually unselected

### ISSUE THREAD

**Issue by sophiasun311** [Workday/canvas-kit#1013]
## 🐛 Bug Report

VoiceOver announces a tab "selected" when it is visually in an unselected state. Non-visual screen reader users may think all tabs are actively selected at the same time. 

## To Reproduce

Use the Tabs in storybook as an example.
https://workday.github.io/canvas-kit/?path=/story/testing-react-labs-tabs--bidirectionality
1. Turn on VoiceOver
2. Use the Tab key to navigate to the "First Tab"
3. Observe VoiceOver speech output: "First Tab, selected, tab 1 of 3" 
4. Press the Right arrow to select the "Second Tab" 
5. We have not press enter to confirm switching panel content, but speech output is: "Second Tab, **selected**, tab 2 of 3",

## Expected Behavior

Screen readers must only be describing the one selected tab as "selected" 

Screenshot:
![Tabs](https://user-images.githubusercontent.com/31709409/113219363-18fc2880-9236-11eb-903c-cb83cf537a51.gif)

**Comment by mathalete** [comment]
Hi,
Please can you indicate what version of Mac OS and what browser (and browser version) you're using? 
Thanks

**Comment by sophiasun311** [comment]
Hi, I'm using MacOS Catalina Version 10.15.7, and Chrome Version 89.0.4389.114

**Comment by willklein** [comment]
Here's some details from a chat we had, per @NicholasBoll:
>Feel free to open a pull request. I think the change is this line: https://github.com/Workday/canvas-kit/blob/master/modules/_labs/tabs/react/lib/Tab.tsx#L117
> 
> Change {isSelected ? true : undefined} to {isSelected} and fix the associated Cypress test: https://github.com/Workday/canvas-kit/blob/master/cypress/integration/Tabs.spec.ts
> 
> There are a few instances of aria-selected that specify the attribute doesn't exist instead of the attributes exists and has a value of "false"
