### ISSUE TITLE
Icons, SystemIconCircle do not extend HTML attributes

### ISSUE THREAD

**Issue by anicholls** [Workday/canvas-kit#1015]
## 🐛 Bug Report

`SystemIcon`, `SystemIconCircle` and other icon components do not extend the standard HTML attributes.

## To Reproduce

```tsx
<SystemIconCircle icon={tokensIcon} className="icon" />
```

## Actual Results

Typescript complains about the prop `className`

**Comment by alanbsmith** [comment]
This is resolved now: https://github.com/Workday/canvas-kit/blob/master/modules/react/icon/lib/Icon.tsx#L13
