### ISSUE TITLE
Move InputProvider to "canvas-kit-react/common"

### ISSUE THREAD

**Issue by alanbsmith** [Workday/canvas-kit#1019]
## 💡 Suggestion

Move `InputProvider` from `canvas-kit-react/tokens` to `canvas-kit-react/common`

## Motivation

It was always weird that it lived in `/core`. Now that the package is called `/tokens`, it feels especially out of place. It would be a lot happier living with `CanvasProvider` in `/common`. 😄 

## Acceptance Criteria

* Move `InputProvider` to `canvas-kit-react/common`
* Create a codemod for the change
* Write tests for the codemod
* Run the codemod against canvas-kit code
* Update documentation

**Comment by anicholls** [comment]
Closed by
