### ISSUE TITLE
Convert Card into a Compound Component

### ISSUE THREAD

**Issue by NicholasBoll** [Workday/canvas-kit#1023]
## 🚀 Feature Proposal

Convert Card into a Compound Component. `heading` and `headingId` props can be removed and instead export a `Card.Header` sub component.

## Motivation

Other components that use Card and need to grant element-level access to the Header will need this. Without this, `Popup` and `Modal` will have to bypass the props and re-create a Header sub component. For example, Modal needs to make the Header an `h1`, but the header in card is a hard-coded `h3`.

## Example

```tsx
// before
<Card heading={'Card Header'} headingId={id}>Card Body</Card>

// after
<Card>
  <Card.Header id={id} as="h1">Card Header</Card.Header>
  <Card.Body>Card Body</Card.Body>
</Card>
```

**Comment by anicholls** [comment]
Closed by #1028
