### ISSUE TITLE
Deprecate loading spinner

### ISSUE THREAD

**Issue by anicholls** [Workday/canvas-kit#103]
## 🚀 Feature Proposal

Based on design's input, going forward we are only going to support one type of loading animation. We need to remove `LoadingSpinner` from `@workday/canvas-kit-react-loading-animations`

Pulled from https://github.com/Workday/canvas-kit/issues/51, and this is a breaking change

## Motivation

 The `LoadingSpinner` and `LoadingDots` serve an identical purpose right now and we need to consolidate. They came about from various design teams on various products. We originally implemented both to support all use cases, but are encouraging consumers to converge on one option. Going forward we will only support the `LoadingDots`.

**Comment by sahlhoff** [comment]
@anicholls currently `LoadingSpinner` has props that are missing from `LoadingDots`: `color`, `scale`. Do we want to move those props over to `LoadingDots`?

**Comment by sahlhoff** [comment]
@anicholls Actually, disregard that second half of the comment– it appears it is in fact the `LoadingDots` animation in CSS but for some reason the classname is `.wdc-loading-spinner` 🤷‍♂

**Comment by sahlhoff** [comment]
Sounds like the CSS renaming is included in `css-updates` branch.

**Comment by anicholls** [comment]
@sahlhoff We would like to leave `color` out, and scale can easily be achieved with 
```
const Spinner = styled(LoadingSpinner)({
  transform: scale(0.8)
});
```
if need be
