### ISSUE TITLE
Docs: Add callouts in component docs for theming and bidirectionally

### ISSUE THREAD

**Issue by anicholls** [Workday/canvas-kit#1032]
## 🚀 Feature Proposal

For the components that support it, we should add some simple documentation at the bottom of each component README that links out to relevant articles for theming and RTL. Something like:

> ## Theming & Bidirectionally
> 
> This component supports theming and RTL via our [theming API](https://github.com/Workday/canvas-kit/blob/master/modules/common/react/lib/theming/README.md). For info specific to bidirectionality, [look here](https://github.com/Workday/canvas-kit/blob/master/modules/common/react/lib/theming/README.md#bidirectionality).

**Comment by jaclynjessup** [comment]
Closing this in favor of creating features to display theming and bidirectionally at a larger scale across Canvas Kit
