### ISSUE TITLE
SidePanel API Updates

### ISSUE THREAD

**Issue by anicholls** [Workday/canvas-kit#105]
## 🚀 Feature Proposal

SidePanel needs a breaking change to bring it in line with our [API & Pattern Guidelines](https://github.com/Workday/canvas-kit/blob/master/API_PATTERN_GUIDELINES.md):

- Change `sidePanelBackgroundColor` to `backgroundColor`
- **Not Breaking**: Add `backgroundColor` as a static variable (https://github.com/Workday/canvas-kit/pull/110)
- **Not Breaking:** Change `open` param in `onBreakpointChange` to `aboveBreakpoint`. We shouldn't suggest the behavior - consumers can do what they want with the return value.
- **Bonus**: There are lots of undefined styles being applied based on conditionals in the styled components. Let's fix this 🙂 

Ensure you document all breaking changes that are made in your PR.

Pulled from https://github.com/Workday/canvas-kit/issues/51 and will be a breaking change.

## Motivation

We want our APIs to be as consistent as possible. Let's bring `SidePanel` back in line by making these changes so our APIs feel more natural from one component to the next.

**Comment by NicholasBoll** [comment]
It looks like @anicholls is working on this in #123
