### ISSUE TITLE
Rename and Reorganize the Storybook Tokens section 

### ISSUE THREAD

**Issue by alanbsmith** [Workday/canvas-kit#1066]
## 💡 Suggestion

Rename and Reorganize the Tokens section in Storybook

## Motivation

The [Tokens section in Storybook](https://workday.github.io/canvas-kit/?path=/story/tokens-common-theming--direction) is weird and we should fix it.

## Example

Maybe this?

```
TOKENS
  Color
  Depth
  ...
ASSETS
  Icon
COMMON
  Utilities
    createComponent
    ...
  Components
    Box
    ...
```
    
Or this?
    
```
    TOKENS
  Color
  Depth
  ...
ASSETS
  Icon
UTILITIES
  Helpers
    createComponent
    ...
  Components
    Box
    ...
```

**Comment by anicholls** [comment]
I think after discussion, we should go with `COMMON` for the top level since `UTILITIES` is less clear that it contains components

**Comment by alanbsmith** [comment]
Closing. Storybook organization matters less now that we have Canvas Docs.
