### ISSUE TITLE
Collapsed menu items do not call the onAction method

### ISSUE THREAD

**Issue by jpante** [Workday/canvas-kit#1070]
## 🐛 Bug Report

Collapsed menu items do not call the onAction method

## To Reproduce

Set the onAction props for the list items, but when I clicking on the collapsed items  my onAction method gets ignored. The simple list is working as expected.

Set all the breadcrumbs at the start, it is rendered in a correct way: the dropdown menu contains the omitted items.
However, when I add items to the existing breadcrumbs, the additional item gets added to the end of the whole breadcrumb,  but the middle items do not collapse into the ... icon. Therefore we end up with partially collapsed breadcrumbs.

### Error Output

![image-2021-05-14-11-57-12-940](https://user-images.githubusercontent.com/1861673/118323772-ffe1cb00-b4b5-11eb-9de6-fa96ca289c41.png)

**Comment by jaclynjessup** [comment]
closing as this was marked as done 7/13/21
