### ISSUE TITLE
Tooltip overlaps keyboard focus border

### ISSUE THREAD

**Issue by jpante** [Workday/canvas-kit#1071]
## 🐛 Bug Report

Tooltip overlaps keyboard focus border

Steps to reproduce:

## To Reproduce

1. Open the storybook link (wd-components)
2. Navigate to popup widget --> Adapter canvas-kit tooltips.
3. Using keyboard, navigate to Tooltip widget.
4. Bring the focus on tooltip trigger element. Tooltips is displayed.
5. Notice the focus on the button.

## Expected Behavior

Tooltip should not overlap the button keyboard focus

## Actual Results

Tooltip overlaps the button keyboard focus

## Browser (if applicable)
<img width="467" alt="Screen Shot 2021-05-14 at 1 15 40 PM" src="https://user-images.githubusercontent.com/1861673/118324132-7da5d680-b4b6-11eb-801c-3c90fa6d5073.png">

Safari-Mac, Windows - IE11, Chrome

Screen Reader: JAWS, NVDA, VO

### Error Output

<img width="429" alt="Screen Shot 2021-05-14 at 1 16 27 PM" src="https://user-images.githubusercontent.com/1861673/118324230-9c0bd200-b4b6-11eb-97c2-0dcd12e91ff8.png">

**Comment by NicholasBoll** [comment]
A possible solution could be CSS using something like:

```ts
'[data-whatinput=keyboard]`
```

Tooltips use margins to position and padding sent to PopperJS is 0. If the keyboard is the input type, a focus ring will show, so we can increase the margin on tooltips by 2px which is the border.

**Comment by jpante** [comment]
Screenshot for  output needs updating

**Comment by myvuuu** [comment]
@jpante is this a blocker for Workday teams?
