### ISSUE TITLE
Add Contributors to Changelog.md

### ISSUE THREAD

**Issue by lychyi** [Workday/canvas-kit#108]
## 🚀 Feature Proposal

It would be nice to be able to recognize contributors on the PRs that they made in our release notes (Changelog.md) through Github tagging.

## Motivation

👍 Contributors are awesome 

## Example

`fix: Update lodash version to resolve vulnerability (#41) (@vibdev)`

**Comment by anicholls** [comment]
Fixed with https://github.com/lychyi/github-compare-changelog-generator
