### ISSUE TITLE
TextArea component error state not showing red outline when in focus

### ISSUE THREAD

**Issue by seamus-daly** [Workday/canvas-kit#1083]
## 🐛 Bug Report

When using the TextArea component when the component triggers an error state the red border outline is hidden when the component is in focus. This seems to be an issue which was introduced in Chrome version 86, where a user-agent style is hiding the outline. Issue was brought up in the #canvas-kit slack channel with @NicholasBoll 

## To Reproduce

The behaviour can be seen when testing the component with an error state in https://design.workday.com/components/inputs/text-area 

## Expected Behavior
The red border should be visible to make it immediately obvious to the user the error is throw for that component without clicking out of it

## Actual Results

The red border is hidden behind a blue border and so cannot be seen without the user clicking out of it

## Browser (if applicable)

Chrome

## Link to repl or repo (highly encouraged)

Please provide a reference to a repo or branch to help us reproduce this bug.

### Error Output

Paste the error output here

Include a screenshot of a visual bug
<img width="741" alt="Screenshot 2021-05-26 at 14 22 52" src="https://user-images.githubusercontent.com/84867206/119807812-6cf45800-bedb-11eb-9486-4ea0ced8aac7.png">

**Comment by jpante** [comment]
Thanks for raising, this bug will apply to all inputs within Canvas Kit and we'll look to solve globally.

**Comment by jaclynjessup** [comment]
Cannot reproduce based on current [storybook](https://workday.github.io/canvas-kit/?path=%2Fstory%2Fpreview-inputs-text-area-react--error)
