### ISSUE TITLE
Add a dist tag for support branches

### ISSUE THREAD

**Issue by anicholls** [Workday/canvas-kit#1119]
## 🚀 Feature Proposal

Whenever we publish a regular release, it uses the dist tag `latest`. We run into an issue when we publish a release for a support branch before updating the master branch. This causes the previous major version to become `latest` temporarily until the next release of the master branch. We often release one after another to reduce this gap, but this isn't great practice. We should probably add a `support` dist tag for the latest on the support branch.

**Comment by jaclynjessup** [comment]
Closing as this was marked done 7/9/21
