### ISSUE TITLE
TextButton with Icon - Spacing between text and Icon is narrower as right to left user.

### ISSUE THREAD

**Issue by AndrewTse** [Workday/canvas-kit#1121]
## 🐛 Bug Report

When using the TextButton component with a Icon as user who is right to left (eg. arabic user) the spacing between the text of the button and the icon as this arabic user is narrower than a english user.
 
## To Reproduce
View the TextButton with Icon as a user who is right to left user. (eg. arabic) (attached screenshot with the issue)
 

## Expected Behavior

Spacing to be consistent between english and arabic users

## Actual Results

The margin is not reversed for a right to left user remains the same as an english user.

## Browser (if applicable)
Yes it was a visual bug, google chrome.

![image](https://user-images.githubusercontent.com/7326816/122970052-4b28ac80-d385-11eb-9dfe-984fa10ebbdc.png)
![image 2](https://user-images.githubusercontent.com/7326816/122970091-5bd92280-d385-11eb-8397-d3809e66a590.png)

**Comment by sahlhoff** [comment]
Hi @AndrewTse would you be able to provide a codesandbox replicating the issue? I'm unable to replicate it using v5 and v4.5: https://codesandbox.io/s/9nnkt, https://codesandbox.io/s/ty8jp. Thank you!

**Comment by jaclynjessup** [comment]
closing as this was marked done 7/9/21
