### ISSUE TITLE
OverflowTooltip not displayed for TextButton with an icon

### ISSUE THREAD

**Issue by jamesfan** [Workday/canvas-kit#1125]
## 🐛 Bug Report

The OverflowTooltip fails to display when wrapping a TextButton with an icon.

## To Reproduce

[Reproduction Codesandbox](https://codesandbox.io/s/overflow-tooltip-textbutton-icon-68qzi?file=/src/App.js).

Mouse over the first TextButton (no icon). Note how the tooltip displays properly. Now, mouse over the second TextButton with the icon (`<TextButton icon={resetIcon}>`) -- no tooltip is displayed.

![overflow-tooltip](https://user-images.githubusercontent.com/146020/123169621-61d70e00-d42e-11eb-8493-446e39f190e5.gif)

## Expected Behavior

A tooltip of `Text Button with OverflowTooltip` should also be displayed when mousing over the second TextButton with the icon.

**Comment by jamesfan** [comment]
I did a bit of digging. The TextButton `<button>` doesn't have `text-overflow: ellipsis` so the logic to find the overflow element in [`findEllipsisElement`](https://github.com/Workday/canvas-kit/blob/master/modules/react/tooltip/lib/OverflowTooltip.tsx#L34) falls back to looking for `overflow: auto | scroll | clip | hidden` in its children (as described in the [Tooltip docs](https://workday.github.io/canvas-kit/?path=/docs/components-popups-tooltip-react--ellipsis#line-clamp)) using [`findOverflowElement`](https://github.com/Workday/canvas-kit/blob/master/modules/react/tooltip/lib/OverflowTooltip.tsx#L14).

For a TextButton with an icon, the icon exists earlier in the DOM than the `<span>` element representing the text. The icon contains an `<svg>` with `overflow: hidden` -- unlike most elements which have a default `overflow` value of `visible`, `<svg>`s appear to default to `hidden`.

<img width="1414" alt="svg-overflow-hidden" src="https://user-images.githubusercontent.com/146020/123175103-0dd02780-d436-11eb-9ffe-6446ead65a30.png">

This causes `findOverflowElement` to catch the `<svg>` before it even reaches the correct overflow element: the text `<span>`. The `<svg>` then fails [the overflow check](https://github.com/Workday/canvas-kit/blob/master/modules/react/tooltip/lib/OverflowTooltip.tsx#L52) in `isOverflowed` (all dimensions have a value of `24`) which means no tooltip is displayed.

I wonder if we should prioritize children that have `text-overflow: ellipsis` before falling back to `findOverflowElement` in `findEllipsisElement`.

**Comment by NicholasBoll** [comment]
Fixed in #1132
