### ISSUE TITLE
Checkbox text is cut off when text is too long

### ISSUE THREAD

**Issue by donnanguyen1** [Workday/canvas-kit#1134]
## 🐛 Bug Report

On the Checkbox component, when the text prop is passed but is too long, part of the text can get cut off on the left.

## To Reproduce

1. In storybook, set checkbox text to "I consent to receive periodic automated text messages (including both transactional and marketing SMS and MMS) related to this and future employment applications, prospective employment opportunities, and employment related correspondence in the event of hiring. I accept the associated Terms and Conditions and understand that my consent is not required. Standard message and data rates may apply. To opt-out of all messaging, reply STOP" 
2. see the word "I" is cut off. There is also less space between the text and checkbox than usual

## Expected Behavior

The text is not cut off/padding left of the text starts from the checkbox itself, not the leftmost. 

## Actual Results

Full text is visible with sufficient space between checkbox and text

## Browser (if applicable)

If this was a visual bug, what browser did you spot it on?
Chrome

## Link to repl or repo (highly encouraged)

Please provide a reference to a repo or branch to help us reproduce this bug.

### Error Output

<img width="449" alt="Screen Shot 2021-07-07 at 10 47 37 AM" src="https://user-images.githubusercontent.com/87093936/124817091-2eac7880-df1e-11eb-9c5e-0788cebd8449.png">

**Comment by myvuuu** [comment]
Was merged, can close out
