### ISSUE TITLE
The group of results combobox has an unnecessary tabindex="0" value

### ISSUE THREAD

**Issue by mathalete** [Workday/canvas-kit#1156]
## 🐛 Bug Report

The group of results combobox has an unnecessary `tabindex="0"` value on its `role="listbox"`.

## To Reproduce

Type into the combobox and observe that the `role="listbox"` has a `tabindex="0"` attribute

## Expected Behavior

The `role="listbox"` shouldn't have a `tabindex="0"` attribute as it's not intended to receive keyboard focus.

**Comment by myvuuu** [comment]
Merged, just needs to be deployed
