### ISSUE TITLE
Review and Update Buttons: Button Readme File to MDX

### ISSUE THREAD

**Issue by myvuuu** [Workday/canvas-kit#1161]
## 💡 Suggestion

Review the readme file for the Button component and:
- Copy/convert it into an MDX file in the canvas-kit repo
- Test code snippets and examples to ensure they are up-to-date and accurate, update as needed

## Motivation

To update and improve Canvas Kit documentation

**Comment by jamesfan** [comment]
We recently added the Button MDX in #1127.
