### ISSUE TITLE
Review and Update Buttons: Action Bar Readme File to MDX

### ISSUE THREAD

**Issue by myvuuu** [Workday/canvas-kit#1162]
## 💡 Suggestion

Review the readme file for the Action Bar component and:
- Copy/convert it into an MDX file in the canvas-kit repo
- Test code snippets and examples to ensure they are up-to-date and accurate, update as needed

## Motivation

To update and improve Canvas Kit documentation.

**Comment by jamesfan** [comment]
We recently added the Action Bar MDX in #1127.
