### ISSUE TITLE
Review and Update Containers: Tabs Readme File to MDX

### ISSUE THREAD

**Issue by myvuuu** [Workday/canvas-kit#1165]
## 💡 Suggestion

Review the readme file for the Tabs component and:
- Copy/convert it into an MDX file in the canvas-kit repo
- Test code snippets and examples to ensure they are up-to-date and accurate, update as needed

## Motivation

To update and improve Canvas Kit documentation

**Comment by jamesfan** [comment]
The [Tabs MDX](https://github.com/Workday/canvas-kit/blob/master/modules/react/tabs/stories/Tabs.stories.mdx) already exists.
