### ISSUE TITLE
FormField doesn't work well with nested child inputs

### ISSUE THREAD

**Issue by alanbsmith** [Workday/canvas-kit#1171]
## 🐛 Bug Report

> Note: This issue was initially a part of #1112, but I'm breaking it out into a separate issue to handle separately.

`FormField` doesn't work as expected with nested child inputs. This is because `FormField` [clones each child component](https://github.com/Workday/canvas-kit/blob/v4.7.0/modules/form-field/react/lib/FormField.tsx#L152) and indiscriminately applies props (but ignores nested children / grandchildren).

## To Reproduce

- [Visit this sandbox](https://codesandbox.io/s/optimistic-thunder-9yi1y?file=/src/App.js)
- see the combobox not picking up the error props

## Expected Behavior

I would assume a high-level API like `FormField` to Just Work™, or I would assume a lower-level API would be available for me to wire things together for my use case

## Actual Results

A user has to manually add the error and the aria-invalid to the input as a workaround.

## Browser (if applicable)

n/a

## Link to repl or repo (highly encouraged)

https://codesandbox.io/s/optimistic-thunder-9yi1y?file=/src/App.js

### Error Output

n/a

**Comment by myvuuu** [comment]
Workaround exist, can't fix without breaking FormFields

**Comment by alanbsmith** [comment]
This was resolved with #1308
