### ISSUE TITLE
Provide better support for screen reader text in Combobox MenuItems

### ISSUE THREAD

**Issue by alanbsmith** [Workday/canvas-kit#1174]
## 🐛 Bug Report

Because of how we [get text from MenuItem elements](https://github.com/Workday/canvas-kit/blob/fa0f4d9226ada17cbd9f293eb914313d94d966d8/modules/labs-react/combobox/lib/Combobox.tsx#L137), we ignore attributes from child elements. In some situations, this creates a diminished experience for people who use screenreaders. For example a list structured like below would announce as "Entering group GroupName (2), with 2 options."

```sh
- GroupName (2)
  - GroupItem 1
  - GroupItem 2
- GroupName (4)
  - GroupItem 1
  - GroupItem 2
  - GroupItem 3
  - GroupItem 4
```
  
While the functionality isn't broken, it's also confusing and a bit annoying. There's also no real workaround to hide the text with `aria-hidden`. We should find a better way to improve support here.

## Example

https://codesandbox.io/s/compassionate-hamilton-3xw2p?file=/src/App.js

**Comment by jaclynjessup** [comment]
Closing as this will be addressed in #1955 & #1932
