### ISSUE TITLE
Convert Toast into a Compound Component

### ISSUE THREAD

**Issue by myvuuu** [Workday/canvas-kit#1199]
## 🚀 Feature Proposal

Convert Toast into a compound component.

### Development Notes

Spec file: https://github.com/Workday/canvas-kit/blob/master/modules/react/toast/spec/Toast.spec.tsx

Current API:
```
() => {
  const toastMessage = 'Your workbook was successfully processed.';
  const actionText = 'View more details';

  return (
    <Toast onClose={cb} onActionClick={onCloseCB} actionText={actionText}>
      {toastMessage}
    </Toast>
  );
}
```

Prospective API (starting point, please reconsider naming and structure):
```
// TBD
```

Prospective sub-components:
- toast message
- action text

Recommended scope:
- update API in existing tests
- add support for defining `onClose` and `onActionClick` using a `model` prop
- document the upgrade in the v6 migration guide
- keep the current design

Optional improvements:
- write a code mod for migration
- add any missing test cases

**Comment by alanbsmith** [comment]
Closed. This was resolved with #1432
