### ISSUE TITLE
Cannot set Ref prop to Banner component

### ISSUE THREAD

**Issue by youryss** [Workday/canvas-kit#1200]
## 🐛 Bug Report

I'm trying to use the ref property of the Banner component but it seems the component doesn't have this api available.

## To Reproduce

try creating a ref and applying that ref to the banner and programmatically try using any html event method like focus()

https://codesandbox.io/s/frosty-cache-t584f?file=/src/CustomBanner.tsx

## Expected Behavior

I hope that when I apply ref to the component I have access to its DOM reference 

## Actual Results

ref does not seem to work and we have no DOM reference

## Browser (if applicable)

If this was a visual bug, what browser did you spot it on?

## Link to repl or repo (highly encouraged)

https://codesandbox.io/s/frosty-cache-t584f?file=/src/CustomBanner.tsx

**Comment by myvuuu** [comment]
Will be fixed as part of the v7 release!
