### ISSUE TITLE
useUniqueId can start with a hypen

### ISSUE THREAD

**Issue by vibdev** [Workday/canvas-kit#1202]
## 🐛 Bug Report

useUniqueId is removing any numbers at the beginning of the string. If the uuid is e.g. `1234-abc` this results in `-abc`

Based on the use of the regex replace it seems like useUniqueId is following the HTML4 Spec:

> ID and NAME tokens must begin with a letter ([A-Za-z]) and may be followed by any number of letters, digits ([0-9]), hyphens ("-"), underscores ("_"), colons (":"), and periods (".").

Could be fixed by adding a hypen to the regex.

...

However the [HTML5 Spec](https://html.spec.whatwg.org/multipage/dom.html#the-id-attribute) says: 

> When specified on HTML elements, the id attribute value must be unique amongst all the IDs in the element's tree and must contain at least one character. The value must not contain any ASCII whitespace. There are no other restrictions on what form an ID can take; in particular, IDs can consist of just digits, start with a digit, start with an underscore, consist of just punctuation, etc.

If we want to match this spec we could just remove the regex replace all together.

## To Reproduce

I refreshed a component a few times and saw it pretty quickly. But you can reproduce in a regex tester pretty easily. 

## Expected Behavior

Depends on the spec we are using. But guessing we should just go with HTML5 and let it start with numbers.

## Actual Results

Id can start with only a letter or a hyphen

<img width="204" alt="Screen Shot 2021-08-07 at 8 08 11 PM" src="https://user-images.githubusercontent.com/1562615/128619419-0d090b0a-c929-433d-b977-6f9cd8d1bdf1.png">

**Comment by NicholasBoll** [comment]
This has been fixed by #1325 and released in v6
