### ISSUE TITLE
Overflow Tabs Spike

### ISSUE THREAD

**Issue by jpante** [Workday/canvas-kit#1230]
## 🔍 Spike /  Exploration

Understand and initial implementation of behaviors required to support. 

## What questions would be answered once this spike was completed?

1. What the interface looks like for multiple data lists (things in and out)
2. How do we make that behavior and model generic for other 'overflow' list type components

## Does this relate to any existing issues?

Link any issues that this spike should resolve
#910

**Comment by NicholasBoll** [comment]
Answer to the questions:
1. Add a collection API (repurpose and expose the `ListModel` as a collection). The collection API has delegates for selection (active tab, but reusable for other collections) and cursor (currently done through model extension). The overall API for collections will look like this:
    ```tsx
    // Static Tabs with no overflow
    <Tabs>
      <Tabs.List>
        <Tabs.Item>First Tab</Tabs.Item>
        <Tabs.Item>Second Tab</Tabs.Item>
      </Tabs.List>
      <Tabs.Panel>First Tab Contents</Tabs.Panel>
      <Tabs.Panel>Second Tab Contents</Tabs.Panel>
    </Tabs>

    // overflow requires `items` be passed to the top-level
    <Tabs items={[{name: 'first', label: 'First Tab'},{name: 'second', label: 'Second Tab'},{name: 'third', label: 'Third Tab'},]}>
      <HStack>
        <Tabs.List>
          {(item) => <Tabs.Item name={item.name}>{item.label}</Tabs.Item>}
        </Tabs.List>
        <Tabs.OverflowButton>More</Tabs.OverflowButton>
        <Tabs.OverflowMenu>
          {(item) => <Tabs.OverflowItem name={item.name}>{item.label}</Tabs.OverflowItem>}
        </Tabs.OverflowMenu>
      </HStack>
      <Tabs.Panel name="first">First Tab Contents</Tabs.Panel>
      <Tabs.Panel name="second">Second Tab Contents</Tabs.Panel>
      <Tabs.Panel name="third">Third Tab Contents</Tabs.Panel>
    </Tabs>
    ```
2. Update the Tabs model to handle an overflow container: `containerRef` that will be assigned to the `Tabs.List` component for the purpose of measuring total available size to figure out how much room is available and move items into the overflow when there isn't enough room. An `containerRef` and behavior hooks are generic enough to not be restricted to Tabs, but can be used for other overflow menus.
