### ISSUE TITLE
Layout erroneously passes in spacing prop to non-Column children

### ISSUE THREAD

**Issue by lychyi** [Workday/canvas-kit#125]
## 🐛 Bug Report

Children in `Layout` will mistakenly get cloned with `spacing` as a prop set by `Layout`. Only `Column` should have `spacing` passed in by `Layout`.

The logic [here](https://github.com/Workday/canvas-kit/blob/master/modules/layout/react/lib/Layout.tsx#L64) doesn't check for the type of React child properly.

## To Reproduce

See Codesandbox

## Expected Behavior

`Layout` should ignore non `Column` type components and not clone it with the `spacing` prop.

## Actual Results

`Layout` incorrectly identifies children as `Column`s and clones that child with an extra `spacing` prop if `Layout` defines a `spacing` prop.

## Browser (if applicable)

If this was a visual bug, what browser did you spot it on?

## Link to repl or repo (highly encouraged)

https://codesandbox.io/s/clever-haibt-vnkim

### Error Output

Paste the error output here

```bash

```

or

Include a screenshot of a visual bug

**Comment by NicholasBoll** [comment]
Fixed by #238
