### ISSUE TITLE
Fix typo in comments of useReturnFocus.tsx to improve readability

### ISSUE THREAD

**Issue by willklein** [Workday/canvas-kit#1292]
## 💡 Suggestion

There is a typo on this line: https://github.com/Workday/canvas-kit/blob/master/modules/react/popup/lib/hooks/useReturnFocus.tsx#L11

>  This should **ble** used on popup elements that use `useInitialFocus`.

## Motivation

This made me stumble trying to understand the code. It would make for a `good first issue` for someone to touch up!

**Comment by himanshu007-creator** [comment]
Hi , i would like to work on this issue
