### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by ksmithroat** [Workday/canvas-kit#1294]
## 🐛 Bug Report

not really a bug, but the reporting a bug line in the README file should be "submit a pull request to address it" not "submit a pull request to addresses it"

**Comment by ksmithroat** [comment]
Hi Alan!

Sure! It’s been a minute since I’ve actually worked in GitHub, but willing
to help contribute 🤠

Cheers,
Katherine

**Comment by willklein** [comment]
Woo!

I'm happy to help. This is a great first issue and it's fantastic you found it for us.

What's the best way for me to assist? I can do as little or as much to help, it's kind of my objective for the month to help people contribute for the first time!

We can be commenting here, doing a screen share, or finding another way to chat. 🤝

**Comment by willklein** [comment]
Looks like it's fixed!
