### ISSUE TITLE
Standardize Font Smoothing

### ISSUE THREAD

**Issue by anicholls** [Workday/canvas-kit#130]
## Summary

We should consolidate our usage of font-smoothing. We have varied use across the kits, with a mix of `antialiased`, `subpixel-antialiased` and `auto`. These cause our text to render differently depending on the component.

I don't know if font smoothing is something we've ever officially agreed upon with design. We should do a review of the options across different browsers with them and decide on one to use in all contexts.

**Comment by stephanerangaya** [comment]
We can start a discussion. Here are some reading materials:
- https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth
- https://usabilitypost.com/2012/11/05/stop-fixing-font-smoothing/
- https://www.zachleat.com/web/font-smooth/

After reading these, it seems that they suggest leaving it on `auto` and only using a different value when it makes sense. It also seems that `subpixel-antialiased` is gone from macOS Mojave and up.

**Comment by alanbsmith** [comment]
Closing this as a stale issue. If it comes up again, we address it.
