### ISSUE TITLE
Display package version in Storybook

### ISSUE THREAD

**Issue by lychyi** [Workday/canvas-kit#131]
## 🚀 Feature Proposal

To get a better understanding of the Storybook we're looking at we should be displaying a version in an obvious location.

## Motivation

This will make looking at a storybook and using a component stay in sync mentally if features or bug fixes got added.

## Example

For example, it would be nice to know what package version was represented when you looked at an `Input` or `Button` component.

**Comment by NicholasBoll** [comment]
This is fixed by #1082
