### ISSUE TITLE
Fix delayed initial skeleton animation

### ISSUE THREAD

**Issue by lychyi** [Workday/canvas-kit#134]
## 🐛 Bug Report

Perception-wise, the diagonal sheen of the Skeleton loader does not fire immediately when the component renders. Given the 5 second duration of the animation, it has a considerable delay before you see it. If the placeholder is meant to substitute content for sub-second load times, most users will never see the sheen.

## To Reproduce

https://workday.github.io/canvas-kit/?path=/story/skeleton--complete

## Expected Behavior

The sheen should animate as soon as the component renders/appears.

## Actual Results

The sheen takes a bit before it animates. Long enough so that content may already replace what's behind it before you see it.

**Comment by lychyi** [comment]
From @anicholls:

The animation is also size dependent. We should be calculating a pixel per second speed/duration so the animation is the same at all screen sizes

**Comment by willklein** [comment]
This will be addressed with a different animation in #1001.
