### ISSUE TITLE
Action Bar Spike

### ISSUE THREAD

**Issue by myvuuu** [Workday/canvas-kit#1361]
## 🔍 Spike /  Exploration

Perform a spike on the Action Bar component to determine when it should be soft and/or hard deprecated.

## What questions would be answered once this spike was completed?

1. How many teams are using Action Bar from Canvas Kit?
2. Who is using CK's Action Bar?
3. Is CK Action Bar similar to other Workday alternatives (design, dev, API)?

## Other Success Criteria?

1. A list of teams using CK's Action Bar is identified
2. A recommendation is provided on when/how Action bar should be soft and/or hard deprecated

**Comment by RayRedGoose** [comment]
Based on my  a research of ActionBar and Toolbar (from WD components) implementations, both components looks similar.

Toolbar have the next features:
- to set RTL or LTR direction (that works in wrapped ActionBar without prop), to set left or center alignment (what didn't used in any implementation), 
- to set `nobackground` prop to make transparent background (what hasn't been used in any implementation).  
Most of implementations are Toolbar without modifications (18 from 27 with fixed position), but some of this used absolute (7/27)  and relative (2/27) position.

Existing ActionBar solves problem with positioning by adding `fixed` prop and it has responsiveness for small screens. Almost all ActionBar implementations used `fixed` prop as true. So I'm wonder if it's better to keep fixed position as a default.
