### ISSUE TITLE
Canvas tab unregister calls onActivate

### ISSUE THREAD

**Issue by testCanvasBug** [Workday/canvas-kit#1364]
## 🐛 Bug Report

When canvas tabs unmount it calls the onActivate command, which calls the callback.

## To Reproduce
Unmount the canvas tabs.

Add a tab and then switch component.

## Expected Behavior
This should not call the onActivate command.

This should just unregister the component

## Actual Results
The onActivate command runs

A clear and concise description of what actually happens
When canvas tabs unmount it calls the onActivate command, which calls the callback.

## Browser (if applicable)
Chrome

If this was a visual bug, what browser did you spot it on?
Chrome

**Comment by NicholasBoll** [comment]
This doesn't seem to be a problem anymore in v6. The example is `HoistedModel` in the Tabs component: https://workday.github.io/canvas-kit/?path=/story/components-containers-tabs-react--hoisted-model

If you open the dev console, you'll see "Selected Tab" messages when a tab is selected, but you will no longer see it if you navigate to another example. This used to happen in v5: https://5d854c26ba934e0020f5e98a-ggqxrdeudb.chromatic.com/?path=/story/components-containers-tabs-react--hoisted-model. The same steps of navigating away will create a console message that a tab was activated.

**Comment by myvuuu** [comment]
Verified in v6
