### ISSUE TITLE
Closing notifications on a modal closes the entire modal

### ISSUE THREAD

**Issue by testCanvasBug** [Workday/canvas-kit#1365]
## 🐛 Bug Report

If a modal triggers a notification, closing the notification closes the entire modal as well. Canvas is confusing which close has been triggered.

## To Reproduce
Have something in a canvas modal that triggers a canvas notification. Close the notification.

## Expected Behavior
This should just close the notification and not the entire modal

## Actual Results
The entire modal closes

## Browser (if applicable)
Chrome

If this was a visual bug, what browser did you spot it on?
Chrome

**Comment by myvuuu** [comment]
Hi @testCanvasBug ! do you have a code sandbox that you can share?
