### ISSUE TITLE
Icon Button Spike

### ISSUE THREAD

**Issue by myvuuu** [Workday/canvas-kit#1380]
## 🔍 Spike /  Exploration

Perform a spike on the usage of icon buttons so that the DSE team can create a plan to reduce the LOE required for teams using icon buttons to migrate to v7.

## What questions would be answered once this spike was completed?

1. How many teams are using CK's icon buttons?
2. Who are those teams?
3. What icon button variants (circle default, hovered square filled, etc.) are those teams using?
4. How will the existing icon button variants map back to the v7 icon button updates?
5. How do we handle the Toolbar icon button?

## Does this relate to any existing issues?

- #1379

**Comment by jaclynjessup** [comment]
closing as this was marked done 3/28/22
