### ISSUE TITLE
Add/Update Depth Tokens

### ISSUE THREAD

**Issue by myvuuu** [Workday/canvas-kit#1383]
## 🚀 Feature Proposal

Update Depth tokens:

- [x] Updating all depth values
- [x] Removing depth -1
- [x] Adding depth 5 and 6
- [ ] Select Drop-down/Menu: Currently depth 2 -> Depth 3
- [ ] Menu:Depth 2 -> Depth 3
- [ ] Color Picker palette:Depth 2 -> Depth 5
- [ ] Toasts:Depth 2 -> Depth 5
- [x] Card:Depth 2 -> Depth 1
- [ ] Side panel: No depth in CKR -> Depth 6
- [ ] Modal Dialogs (Modal that users must take an action on to dismiss, usually display on top of an opacity overlay) : Depth 6
- [ ] Non modal Dialogs (Modals that users do not have to take an action to dismiss, they can just click anywhere outside it): Depth 5
- [ ] Update migration guide

**Comment by jaclynjessup** [comment]
closing as this was marked done 4/7/22
