### ISSUE TITLE
Remove Popper's containerElement prop

### ISSUE THREAD

**Issue by alanbsmith** [Workday/canvas-kit#1404]
## 💡 Suggestion

Remove Popper's [`containerElement` prop](https://github.com/Workday/canvas-kit/blob/fa0f4d9226ada17cbd9f293eb914313d94d966d8/modules/react/popup/lib/Popper.tsx#L31).

## Motivation

We no longer need this with Fullscreen API support introduced in #1403.

## Acceptance Criteria

- [ ] Remove the `containerElement` prop from `Popper`
- [ ] Update documentation and examples
- [ ] Update V7 migration guide

**Comment by jaclynjessup** [comment]
Closing was marked done Apr 27 22 in sprint
