### ISSUE TITLE
Avoid Wrapping Menu in multiple divs

### ISSUE THREAD

**Issue by vibdev** [Workday/canvas-kit#1467]
## 🐛 Bug Report

The menu element is wrapped in two outer divs than make styles hard to override.

## To Reproduce

https://codesandbox.io/s/borderless-menu-00ej4

## Expected Behavior

The top level element should be an `ul`

## Actual Results

`div` soup

**Comment by alanbsmith** [comment]
Closing this! We resolved this with the new Menu in main in V7. #1547
