### ISSUE TITLE
Modal.Target / Popup.Target "as" prop shows a function ref warning in the console for wrapped components

### ISSUE THREAD

**Issue by ahayes91** [Workday/canvas-kit#1473]
## 🐛 Bug Report

When using new Modal.Target from Canvas Kit v5 onwards, a warning appears in the console if you try to pass a wrapped component to Modal.Target `as` prop instead of using one of the Canvas Kit buttons directly. 
While not a blocker, this means we can't apply any conditional logic to our buttons on the modals without incurring development warnings in our UI and in our jest tests (e.g. if we need to extract out ways to change themes across our buttons, etc). 
Is there a reason why the `as` prop is restricted this way?

## To Reproduce
Code sandbox here with full code:

[![Edit small-meadow-87r7o](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/small-meadow-87r7o?fontsize=14&hidenavigation=1&theme=dark)

Code that produces no warning:

```jsx
import { Modal, useModalModel } from "@workday/canvas-kit-react/modal";
import { PrimaryButton } from "@workday/canvas-kit-react/button";

export const ModalWithoutWrapper = () => {
  const model = useModalModel();
  return (
    <Modal model={model}>
      <Modal.Target as={PrimaryButton} data-testid={"buttonId"}>
        Open
      </Modal.Target>
      <Modal.Overlay>
        <Modal.Card>
          <Modal.CloseIcon />
          <Modal.Body>
            <div>Show modal</div>
          </Modal.Body>
        </Modal.Card>
      </Modal.Overlay>
    </Modal>
  );
};
```

Code that produces warning:

```jsx
import { PrimaryButton } from "@workday/canvas-kit-react/button";
import { Modal, useModalModel } from "@workday/canvas-kit-react/modal";

const PrimaryButtonWithWrapper = ({ children, ...props }) => (
  <PrimaryButton {...props}>{children}</PrimaryButton>
);

export const ModalWithWrapper = () => {
  const model = useModalModel();
  return (
    <Modal model={model}>
      <Modal.Target as={PrimaryButtonWithWrapper} data-testid={"buttonId"}>
        Open
      </Modal.Target>
      <Modal.Overlay>
        <Modal.Card>
          <Modal.CloseIcon />
          <Modal.Body>
            <div>Show modal</div>
          </Modal.Body>
        </Modal.Card>
      </Modal.Overlay>
    </Modal>
  );
};
```

## Expected Behavior

I'd expect to see no warnings in the console when using Modal.Target. 

## Actual Results

Warning that appears:

```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `[Popup.Target](http://popup.target/)`.
```

## Browser (if applicable)

N/A

## Link to repl or repo (highly encouraged)

Code sandbox:
[![Edit small-meadow-87r7o](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/small-meadow-87r7o?fontsize=14&hidenavigation=1&theme=dark)

### Error Output

```bash
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `[Popup.Target](http://popup.target/)`.
    at PrimaryButtonWithWrapper (https://87r7o.csb.app/src/ModalWithWrapper.jsx:28:23)
    at eval (https://87r7o.csb.app/node_modules/@workday/canvas-kit-react/dist/es6/common/lib/utils/components.js:31:27)
    at eval (https://87r7o.csb.app/node_modules/@workday/canvas-kit-react/dist/es6/common/lib/utils/components.js:31:27)
    at ModalWithWrapper (https://87r7o.csb.app/src/ModalWithWrapper.jsx:40:42)
    at div
    at App (https://87r7o.csb.app/src/App.js:19:3)
```

**Comment by NicholasBoll** [comment]
I'm not sure this is a bug per se. The warning is complaining about refs not being forwarded. We attempt to make popup targets work even without ref forwarding by making the assumption the popup will be opened by a click event being the trigger to open the popup. In this case, we check if the model's ref has been assigned (by normal ref forwarding). If not, we mutate the ref manually by assigning the `.current` value to the `event.currentTarget` which should be the button. This isn't 100% accurate, but it is in most circumstances.

To fix this, you need to [forward the ref](https://reactjs.org/docs/forwarding-refs.html) to the component. In your example:

```jsx
const PrimaryButtonWithWrapper = React.forwardRef(({ children, ...props }, ref) => (
  <PrimaryButton ref={ref} {...props}>{children}</PrimaryButton>
));
```

**Comment by ahayes91** [comment]
Thanks @NicholasBoll for the explanation! I think that's fair enough and given that's documented here in this ticket, should be good to just close this off as expected behaviour. Thank you!
