### ISSUE TITLE
Codemod wrongly migrates Skeleton.Header to Skeleton.DeprecatedHeader

### ISSUE THREAD

**Issue by jaslloyd** [Workday/canvas-kit#1496]
## 🐛 Bug Report

Codemod wrongly migrates Skeleton.Header to Skeleton.DeprecatedHeader

## To Reproduce

1. Have some code you need to migrate that includes `Skeleton.Header`
2. Run codemod script `npx @workday/canvas-kit-codemod v6 src`
3. Skeleton.Header is now changed Skeleton.DeprecatedHeader

## Expected Behavior

To not change Skeleton.Header to Skeleton.DeprecatedHeader, Skeleton.Header is right component

## Actual Results

Skeleton.Header gets migrated to Skeleton.DeprecatedHeader

## Browser (if applicable)

If this was a visual bug, what browser did you spot it on?

## Link to repl or repo (highly encouraged)

Please provide a reference to a repo or branch to help us reproduce this bug.

### Error Output

Paste the error output here

```bash

```

or

Include a screenshot of a visual bug

**Comment by willklein** [comment]
We also have an issue renaming any instance of `Header` to `DeprecatedHeader` even if it's not a Canvas Kit import, and this is a common component name.
