### ISSUE TITLE
Spike for Determining Modality 

### ISSUE THREAD

**Issue by myvuuu** [Workday/canvas-kit#1508]
## 🔍 Spike /  Exploration

Spike ticket needed to determine how to calculate and implement modality.

## What questions would be answered once this spike was completed?

1. How can modality be calculated with the Canvas Provider?
2. How do we implement modality so that different component behaviors or designs can be triggered by certain modalities?

## Does this relate to any existing issues?

https://github.com/Workday/canvas-kit/issues/1491

**Comment by jaclynjessup** [comment]
Closing as this was marked Done in sprint Apr 6 22
