### ISSUE TITLE
Convert Pagination to a Compound Component

### ISSUE THREAD

**Issue by myvuuu** [Workday/canvas-kit#1519]
- [ ] Determine how many teams are currently using Pagination
- [ ] Identify a change management process to help teams migrate to the new compound component
- [ ] Convert to a compound component
- [ ] Promote to Main OR add the compound component Pagination to Main and keep the original in Preview (depending on how many teams are using it)
- [ ] Implement code mod, if possible OR reach out to teams using Pagination directly to help them upgrade 
- [ ] Update documentation

**Comment by willklein** [comment]
I'm not sure why this issue was ever created. It was a compound component when it was back in February 2021: https://github.com/Workday/canvas-kit/pull/954

It was promoted to Main in May 2021 for v5: https://github.com/Workday/canvas-kit/pull/1069
