### ISSUE TITLE
canvas-kit support for Angular

### ISSUE THREAD

**Issue by zensarCompass** [Workday/canvas-kit#153]
### canvas-kit support for Angular.

For questions or help please see:

- Please let us know if canvas-kit supports to Angular versions as well. If yes could you please share one sample. Thanks 🙂

**Comment by rohinihonmute** [comment]
Hi Josephnle,
Thank you for replay 🙂. May i know is there is difference between using Canvas-Kit-CSS to html Controls and using canvas-react-controls its self?

**Comment by lychyi** [comment]
@rohinihonmute Can you elaborate what you mean by that? I'm not sure I understand the question?

**Comment by rohinihonmute** [comment]
If I use css of canvas kit in angular. Will be same as canvas kit controls in react. 
And if all controls are available in angular (if i apply css to html controls)?

**Comment by lychyi** [comment]
Like @josephnle we're working on parity between the two component libraries (CSS and React) so in the near future, they should be the same as far as styling goes.

But today, for example, the [CSS styles for a Canvas `button`](https://workday.github.io/canvas-kit/?path=/story/css-button--all) should render the same as the [`<Button>` React component](https://workday.github.io/canvas-kit/?path=/story/button--primary). So when you go to implement components or UI in Angular, you would apply the CSS styles and you could get the same look and feel as our React components.

I hope I'm answering that correctly. I think the word that I'm getting hung up on is "controls" I'm not familiar with what you mean by that.

**Comment by rohinihonmute** [comment]
@laychyi if I use css of canvas in angular what are the limitations?is there any components are not implemented in css other than react? 
Means I want to know only the difference if I use it with angular and if I use it with react. 
And yes components I used word for ui controls(like button,text, checkbox)..

**Comment by NicholasBoll** [comment]
@rohinihonmute The CSS kit of Canvas is only the styling of Canvas. The React kit of Canvas includes behavior and accessibility implemented through React components. The CSS kit could be wrapped by any framework (including Angular), but guaranteeing correct behavior is left as an exercise of the one(s) wrapping the CSS kit.

To summarize, the CSS kit is only styling and the React kit is styling + behavior.

**Comment by lychyi** [comment]
I hope that answered your question @zensarCompass!

**Comment by zensarCompass** [comment]
Yes @lychyi . Thanks for you help :-)
