### ISSUE TITLE
React 18 Spike

### ISSUE THREAD

**Issue by myvuuu** [Workday/canvas-kit#1538]
## 🔍 Spike /  Exploration

Investigate the steps required for upgrading to React 18.

## What questions would be answered once this spike was completed?

1. How does upgrading to React 18 impact our other dependencies?
2. Is React 18 dropping support for anything we or our users might need?

## Deliverable(s)
Document findings in a post similar to https://github.com/Workday/canvas-kit/discussions/1455

**Comment by RayRedGoose** [comment]
This Spike was placed into a [discussion](https://github.com/Workday/canvas-kit/discussions/1545). Upgrading to React 18 doesn't cause any issues. But it will require update Storybook for the supporting version to have ability to see React 18 feature in action.
