### ISSUE TITLE
Replace TSLint with ESLint

### ISSUE THREAD

**Issue by josephnle** [Workday/canvas-kit#154]
## 🚀 Feature Proposal

Replace TSLint with ESLint using [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint)

## Motivation

TSLint will be deprecated sometime in 2019. The TSLint team has decided to adopt ESLint longterm and the recommendation is to use ESLint and typescript-eslint. They've also provided a [CLI command](https://github.com/typescript-eslint/tslint-to-eslint-config) to assist with the migration.

See:
- https://eslint.org/blog/2019/01/future-typescript-eslint
- https://github.com/palantir/tslint/issues/4534
- https://medium.com/palantir/tslint-in-2019-1a144c2317a9

**Comment by Patil2099** [comment]
@josephnle  Can I work on this?
