### ISSUE TITLE
Identify all non-compound components that still need to be converted

### ISSUE THREAD

**Issue by alanbsmith** [Workday/canvas-kit#1543]
## 🔍 Spike /  Exploration

List all components that still need to be converted to compound components and create issues for them.
 
Issues found: 
- [ ] #1196 
- [ ] #1519 
- [ ] #1195 
- [ ] #1669 
- [ ] #1316 
- [ ] #1774 
- [ ] #1506
- [ ] #1852 
- [ ] #1738 suggests converting it to a compound component

Issues created:
- [ ] #1931 
- [ ] #1932
- [ ] #1933
- [ ] #1934
- [ ] #1935
- [ ] #1936

There are also several button components that are built on `BaseButton`, which is compound. They are unlikely to change:

- Delete Button
- Primary Button
- Secondary Button
- Tertiary Button
- Toolbar Dropdown Button
- Toolbar Icon Button

There is also the sub-component `SegmentedControl.SegmentedControlButton` that could also be broken down, but it's similar to the other buttons that are composed on `BaseButton`.

## What questions would be answered once this spike was completed?

- [x] List all components that need to be converted to compound components that are not currently in-flight
- [x] Note any components that are not compound but excluded from planned conversion
- [x] Update #1926 with relevant issues found and created

**Comment by willklein** [comment]
I created some new issues and added them:
#1931, #1932, #1933, #1934, #1935, #1936

I found some existing issues and added them:
#1506, #1852, #1738

I closed #1519 after discovering that this issue was invalid. The work was completed in v5.
