### ISSUE TITLE
Identify all docs that need to be converted to MDX and updated to the new template

### ISSUE THREAD

**Issue by alanbsmith** [Workday/canvas-kit#1544]
## What questions would be answered once this spike was completed?

1. Which docs still need to be converted to MDX?
2. What docs need to be updated to the new template?
3. Does anything need to be reorganized and/or broken down (ex: breaking the theming doc into several docs)?

Ideally this list would be converted to issues as the deliverable.

**Comment by mannycarrera4** [comment]
-[ ] Avatar

**Comment by josh-bagwell** [comment]
The only other component I saw that could be included is Side Panel?

**Comment by jaclynjessup** [comment]
Closing spike - work will be completed within the Epic
