### ISSUE TITLE
Canvas Kit v7 in Vite Dev Server

### ISSUE THREAD

**Issue by anicholls** [Workday/canvas-kit#1572]
## 🐛 Bug Report

Canvas Kit v7 breaks when components are rendered on the page after imported with a slash import when using Vite. Builds are fine - it's only in the dev server. The issue is due to [dependency pre-bundling](https://vitejs.dev/guide/dep-pre-bundling.html).

It worked fine in v6 and here's why: Vite only does pre-bundling for direct dependencies. `Flex` was a transitive dependency in v6 (because CKR depends on labs), but now `Flex` has been promoted to CKR proper so it is getting pre-bundled.

The error is that the `Flex` component is `undefined` when `StyledStack` tries to instantiate itself (`StyledStack = styled(Flex)`). Once the error occurs, you have to clear the Vite cache to make it go away (`node_modules/.vite`).

I tried disabling pre-bundling for Canvas Kit, but it breaks other things and this is a less than ideal solution.

I was originally looking into problems with `createComponent` and `styled`, but those turned out to be red herrings (the source map led me astray). After a significant amount of investigation, I noticed that in the pre-bundle chunk file, `Flex` is defined _below_ `StyledStack`, which is why it is `undefined` at this point. If I manually move it up, or change to `styled(Box)` (which is defined earlier in the file), the error goes away. Changing from a slash import to a global import (e.g. `import { Checkbox } from '@workday/canvas-kit-react'`), this also fixes the issue. See lines 11804 - 11889 in the bundle that Canvas Kit gets put into in `node_modules/.vite`

Since swapping to `styled(Box)` worked, I figured I'd inspect the difference between `Flex` and `Box` to see if there was anything in the source code that would cause this. The only thing I can see is [how they're imported into Stack](https://github.com/Workday/canvas-kit/blob/prerelease/major/modules/react/layout/lib/Stack.tsx#L4-L5) (module reference for `Box` and relative for `Flex`). However, if I manually change this in my `node_modules` folder before starting the server and rebuilding the Vite cache, it doesn't make a difference 😞 

This seems like an issue with Vite, but I wanted to get this issue opened so others are aware and to dump my thoughts before the end of the day. I will update with more info and a matching ticket on the Vite repo.

## To Reproduce

Steps to reproduce the behavior: Start, install and run https://github.com/anicholls/vite-ckv7, then view in browser.

## Expected Behavior

An example page to be displayed

## Actual Results

![image](https://user-images.githubusercontent.com/908478/167042852-9c06a29e-e57f-4c85-959b-d43ec42067b8.png)

**Comment by vibdev** [comment]
With Vite, does tree shaking work using the global import?

**Comment by vibdev** [comment]
I am able to repro in Codesandbox without Vite

https://codesandbox.io/s/dont-flex-on-me-itxn3k?file=/src/App.tsx

**Comment by natedub** [comment]
This little patch is the fix:

```diff
diff --git a/modules/react/layout/lib/Flex.tsx b/modules/react/layout/lib/Flex.tsx
index f253af19..988cbe93 100644
--- a/modules/react/layout/lib/Flex.tsx
+++ b/modules/react/layout/lib/Flex.tsx
@@ -1,7 +1,7 @@
 import * as React from 'react';
 import styled from '@emotion/styled';
 import {createComponent, StyledType} from '@workday/canvas-kit-react/common';
-import {Box, BoxProps} from '@workday/canvas-kit-react/layout';
+import {Box, BoxProps} from './Box';

 import {flex, FlexStyleProps} from './utils/flex';

diff --git a/modules/react/layout/lib/Stack.tsx b/modules/react/layout/lib/Stack.tsx
index 907b8522..389f9f1c 100644
--- a/modules/react/layout/lib/Stack.tsx
+++ b/modules/react/layout/lib/Stack.tsx
@@ -1,7 +1,7 @@
 import * as React from 'react';
 import styled from '@emotion/styled';
 import {createComponent, StyledType} from '@workday/canvas-kit-react/common';
-import {Box, BoxProps} from '@workday/canvas-kit-react/layout';
+import {Box, BoxProps} from './Box';
 import {Flex, FlexProps} from './Flex';
 import {getValidChildren} from './utils/getValidChildren';
 import {stack, StackStyleProps} from './utils/stack';
```

These imports were reentrant: while doing the initial import of all the symbols for `layout`, we were importing `layout`. This was enough to break the import ordering of esbuild and webpack.

**Comment by anicholls** [comment]
Thanks @natedub - you're a hero. I tested the change to `Stack`, but missed the change in `Flex`.

We should probably add a lint rule to prevent modules from importing themselves. Could be an addition to the [`restricted-imports` rule](https://github.com/Workday/canvas-kit/blob/master/utils/custom-lint-rules/restricted-imports.js)
