### ISSUE TITLE
Select Component in Preview Opens Dropdown when clicking on the label

### ISSUE THREAD

**Issue by nkmagik** [Workday/canvas-kit#1573]
## 🐛 Bug Report
When using the Select component from preview, we noticed that clicking on the label will automatically open the dropdown.

**EDIT** - this behavior appears to be happening for more than just the `<Select> `component as well.  I have just noticed the same behavior with the `<Checkbox> `component where clicking on the label checks/unchecks the checkbox instead of just focusing on it.
 
## Steps to reproduce the behavior
- Navigate to the storybook for the Select component in preview - https://workday.github.io/canvas-kit/?path=/story/preview-select-react-left-label--default
- Click on the label
- It should automatically focus on the dropdown and open it as well

## Expected Behavior
The expected behavior is that clicking on the label focuses the active element to the dropdown, but it doesn't automatically open it. 

## Actual Results
Clicking on the label focuses the active element to the dropdown (expected).  However, it also opens the dropdown (unexpected).

## Browser (if applicable)
Noticed the issue in Chrome, but I expect that this issue may appear across all browsers.

## Link to repl or repo (highly encouraged)

N/A

### Error Output
![select-label-click](https://user-images.githubusercontent.com/3858491/167485054-ade3f42d-d063-4de7-826f-11cdae0dc3af.gif)

**Comment by willklein** [comment]
I confirmed this is desired behavior. From our accessibility researcher:
> this is a feature, not a bug 🎉
>
> if it helps any, the [whatwg](https://html.spec.whatwg.org/multipage/forms.html#the-label-element) defines the spec for what should happen when a label is clicked, then browser vendors will interpret that how they wish - hence the variety of behaviour with native select as an example

Not every component library or browser chooses to support clickable labels but this is more consistent with other inputs and we stand by our choice to make it clickable.
