### ISSUE TITLE
Checkbox requires an id if label is enabled

### ISSUE THREAD

**Issue by jeffma123** [Workday/canvas-kit#158]
## 🐛 Bug Report

The checkbox should not require an id.

## To Reproduce

Create multiple checkboxes. Clicking on the label only affects the first checkbox.

## Expected Behavior

Each label should work independently.

**Comment by lychyi** [comment]
@jeffma123 Is the bug that a checkbox shouldn't require an `id`? Or is it the fact that multiple checkboxes do not function correctly if you don't supply an `id`?

**Comment by anicholls** [comment]
@lychyi from @NicholasBoll on slack:
> `defaultProps` sets the `id` to a `uuid`, but that function is only evaluated for the component and not for each instance.
> The fix is pretty simple - make `id` be an instance variable on the `Checkbox` class, get rid of `defaultProps.id` and update the render function to use `id || this.id`. That will guarantee a unique `id` for each instance that is overridable.
