### ISSUE TITLE
Add breakpoint documentation

### ISSUE THREAD

**Issue by alanbsmith** [Workday/canvas-kit#1619]
## 💡 Suggestion

Add responsive breakpoint documentation to MDX / Storybook

## Motivation

Breakpoint docs are currently available [here](https://github.com/Workday/canvas-kit/tree/master/modules/react/common/lib/theming#breakpoints), but are basically invisible for users and taxing for us to reference. I would recommend they live in our dev docs under a Theming page where we could also add information about Bidi / RTL and theming – [similar to what we have here](https://workday.github.io/canvas-kit/?path=%2Fdocs%2Ffeatures-theming--theme).

**Comment by thunguyen19** [comment]
@alanbsmith https://workday.github.io/canvas-kit/?path=/docs/tokens-common-theming is not working anymore. Could you please update?

**Comment by jaclynjessup** [comment]
Breakpoint documentation can be found here https://workday.github.io/canvas-kit/?path=%2Fdocs%2Ffeatures-responsive-styling--responsive-container
