### ISSUE TITLE
Soft Deprecate Drawer

### ISSUE THREAD

**Issue by myvuuu** [Workday/canvas-kit#1625]
## 💡 Suggestion

Soft deprecate Drawer by:

- [ ] Adding deprecation warnings to Drawer
- [ ] Reaching out to teams using Drawer (if there are any) to assist with the migration to Side Panel
- [ ] Create code mod to rename it to "Deprecated Drawer"

## Motivation

Drawer is an older component and Side Panel can now handle everything Drawer did (and more)

**Comment by mannycarrera4** [comment]
This will be addressed : https://github.com/Workday/canvas-kit/issues/1712
