### ISSUE TITLE
Deprecate IE11

### ISSUE THREAD

**Issue by myvuuu** [Workday/canvas-kit#1631]
## 💡 Suggestion

IE11 support will be dropping in September 2022 and will need to be deprecated from Canvas Kit by:

- [x] Removing IE specific code
- [x] Update documentation to indicate that IE11 is no longer support

**Comment by mannycarrera4** [comment]
I think we can just uncheck IE from chromatic
![Screen Shot 2022-08-18 at 8 54 57 AM](https://user-images.githubusercontent.com/7966550/185427024-147d5930-2969-458d-977d-83a94b632e6f.png)

**Comment by mannycarrera4** [comment]
Update supported browser list https://github.com/Workday/canvas-kit#supported-browsers

**Comment by mannycarrera4** [comment]
Look into if we still need whatinput and canvas provider
