### ISSUE TITLE
Canvas required input example has required attribute set to the wrong element

### ISSUE THREAD

**Issue by andrew-poblete** [Workday/canvas-kit#1633]
## 🐛 Bug Report

On https://canvas.workdaydesign.com/components/inputs/form-field/#required, the example has `required ` set to to the label instead of the input.

1. Go to https://canvas.workdaydesign.com/components/inputs/form-field/#required
2. Inspect the required "email" field.

## Expected Behavior

The `required` attribute should be on the email's input field and not the email's label

## Actual Results

The `required` attribute is on the email's label

## Browser (if applicable)

Chrome

**Comment by vibdev** [comment]
Looks like it is correct in the newer preview version:
https://workday.github.io/canvas-kit/?path=/story/preview-inputs-text-input-react--required ✅

But incorrect in the base package:
https://workday.github.io/canvas-kit/?path=/story/components-inputs-text-input-react--required ❌

**Comment by mannycarrera4** [comment]
Hey @andrew-poblete, @vibdev  is correct! If you're using our `FormField` from the main package `react` that's how you would make the input required. Closing this issue. Moving forward our goal is to have one component or promote the preview component to the main package, for now if you're using the one from the main package, you would add it to the form field component.
