### ISSUE TITLE
vertically aligned combobox overlaps with each other

### ISSUE THREAD

**Issue by angie-hui** [Workday/canvas-kit#1668]
## 🐛 Bug Report

When multiple combobox are vertically displayed, the menu items of the previous combobox is hidden under the input field of the combobox below.

## To Reproduce

1) Have 2 combobox vertically stacked on top of each other
2) Open options menu of top combobox

## Expected Behavior
 Menu items should be visible and not hidden under input field of the next combobox

## Actual Results
Menu items are hidden behind input field of the next combobox

## Browser (if applicable)
Chrome

If this was a visual bug, what browser did you spot it on?

## Link to repl or repo (highly encouraged)

https://codesandbox.io/s/overlapping-combo-box-4bpo8y?file=/src/App.js

### Error Output

Paste the error output here

```bash

```

or

Include a screenshot of a visual bug
![image](https://user-images.githubusercontent.com/108896120/177844938-00ac0eeb-38db-4e38-b9c1-4c58d6da5860.png)

**Comment by NicholasBoll** [comment]
Here's a codesandbox of this workaround working: https://codesandbox.io/s/0edf2x

**Comment by angie-hui** [comment]
I've tried the workaround and it works. Did you want me to close the issue?
