### ISSUE TITLE
Convert Combobox to a Compound Component (and promotion?)

### ISSUE THREAD

**Issue by RayRedGoose** [Workday/canvas-kit#1669]
### AC
- [ ] Feat: Convert to a compound component + Update documentation
- [ ] Chore: Promote to Main/Preview OR add the compound component Combobox
- [ ] Spike: Determine how many teams are currently using Combobox
- [ ] Chore: Implement code mod, if possible or help teams directly

**Comment by mannycarrera4** [comment]
A few thing son this ticket:

- I think combobox is more of a system similar to list.
- This system should trickle into the `Select` component since they both work well together
