### ISSUE TITLE
Multiple types are colliding if commonjs is used for resolution

### ISSUE THREAD

**Issue by NicholasBoll** [Workday/canvas-kit#1680]
## 🐛 Bug Report

The `modules/react/package.json` has a `types` field, but the sub-directory packages do not. This can cause an issue where multiple types are imported - one from `dist/commonjs` and one from `dist/es6`

We can fix this by adding the following line:

```ts
types: `../dist/es6/${folderName}`,
```
to https://github.com/Workday/canvas-kit/blob/1bc3124ba0dd585b0f6079e0c42f8141293f0f0b/utils/publish.js#L49-L53

This will make the `types` field consistent. This fix is a minor, low-risk change and can go into the `support` branch.

**Comment by pbhuynh** [comment]
This is also happening in 7.x FWIW!
