### ISSUE TITLE
Consider Prop Spread Behavior

### ISSUE THREAD

**Issue by anicholls** [Workday/canvas-kit#171]
## 💬 Question

This question was prompted with a [standardization of our `elemProps` behavior](https://github.com/Workday/canvas-kit/blob/master/API_PATTERN_GUIDELINES.md#prop-spread-behavior) in https://github.com/Workday/canvas-kit/pull/150.

After adding tests to all components for the correct prop spread behavior, it became evident we have several components who don't spread props on their outermost container element:
- ~`PageHeader` - Props are spread on content container (first child)~
- `Menu` - Props are spread on styled `List` element (first child)
- `ColorInput` - Props are spread on styled TextInput `CustomHexInput` element (first child)
- `Radio` - Props are spread on styled `RadioInput` element (first grandchild)
- `Checkbox` - Props are spread on styled `CheckboxInput` element (first grandchild)
- `TextInput` - Props are referred to as `inputProps` and spread on styled `Input` element (first child)
- `Select` - Props are spread on styled `SelectContainer` element (first child)
- `ColorPreview` - Wraps `ColorInput`
- `Switch` - Props are spread on styled `SwitchInput` element (first child)

There was some pretty lengthy discussion on Slack about whether we should always be spreading on:

**1️⃣ The Container Element**
- Standardized, predictable
- Leaks implementation details
- Container is sometimes mostly unrelated to the component
- Could use prop objects (i.e. `<Menu data-someattr={true} listProps={{oneProp: 'foo', anotherProp: 'bar'}} />`)

**2️⃣ The Most Applicable Element**
- How do we decide/standardize what this is?
- More accurate/usable, but less consistent/predictable

However, the question arose around whether this is even the right strategy for this behavior going forward. It has been popular internally and it works well for generic and low-level components, but it quickly gets complicated when you start to compose them (as we're beginning to discover). We should discuss and evaluate this in more depth as a team, but https://github.com/Workday/canvas-kit/pull/150 will be merged, as it achieved the results it was originally intended for.

**Comment by alanbsmith** [comment]
Closing this as `Done` with #150
