### ISSUE TITLE
Follow-up on Type component docs

### ISSUE THREAD

**Issue by alanbsmith** [Workday/canvas-kit#1711]
## 💡 Suggestion

Let's have a separate polish step for cleaning up Type docs

## Motivation

There's a lot to cover. Let's separate out that work.

**Comment by RayRedGoose** [comment]
Is there any difference with Manny's issue: https://github.com/Workday/canvas-kit/issues/1707?

**Comment by alanbsmith** [comment]
Closing. Dupe of #1707
