### ISSUE TITLE
Make SystemIcon token aware of colors

### ISSUE THREAD

**Issue by mannycarrera4** [Workday/canvas-kit#1751]
## 🚀 Feature Proposal

Marking this for SystemIcon but I think we should make a larger audit to make sure our components are token aware. 

But we'd need to make some adjustments to `SystemIcon` for that to allow use token colors for `color` prop:

```tsx
<SystemIcon icon={checkIcon} color="greenApple400" />
```

- Adjust the color type in `SystemIconStyles`
- `string` becomes `CanvasColor | (string & {});`
- Remove `color` from the Omit props
- Add a function to process the colors

```ts
import {iconColors, colors, CanvasColor} from '@workday/canvas-kit-react/tokens';

function getColor(value: CanvasColor | string) {
  if (value in colors) {
    return colors[value as keyof typeof colors];
  }
  return value;
}
```

**Comment by thunguyen19** [comment]
@mannycarrera4 I think this issue could extend to other color related props within this component, i.e `accent`, `accentHover`, `background`, `fill`.... etc. Could you confirm if my understanding is correct? If so, shall we make changes to other props as well, instead of `color` only?

**Comment by mannycarrera4** [comment]
Hey @thunguyen19 that's correct! Anything that accepts a color should have this capability!
