### ISSUE TITLE
Update migration guide for v7 to document icon size changing in our buttons

### ISSUE THREAD

**Issue by mannycarrera4** [Workday/canvas-kit#1754]
## 🐛 Bug Report

We need to document that the icon size is changing for default button size. Consumers expect a default IconButton with an icon size of 24px would translate to a `TertiaryButton` with size medium to be 24px but really it's 20 x 20.

**Comment by jaclynjessup** [comment]
Can confirm that within the [announcement](https://canvas.workdaydesign.com/whats-new/announcements#canvas-kit-v7-and-figma-library-release) we mention the icon size will not change when it does 

> The medium sized Icon Buttons with a 20px icon that are being mapped to the new medium sized icon only Primary, Secondary, and Tertiary button variants will have a larger 24px icon

see [Sandbox](https://codesandbox.io/s/tertiarybuttoniconsize-lpgl79?file=%2Fsrc%2FApp.tsx) to view icon size changing

On another note within the [props](https://workday.github.io/canvas-kit/?path=%2Fdocs%2Fcomponents-buttons-button-react--tertiary) we note 3 sizes for tertiary buttons, yet list 4.
![Screen Shot 2022-09-22 at 10 38 25 AM](https://user-images.githubusercontent.com/23533895/191803777-686c072b-367f-4b5c-a8e8-b89706ec7661.png)

**Comment by jaclynjessup** [comment]
Announcement was fixed. Closing this issue and opening separate one for the props sizing issue.
