### ISSUE TITLE
Avatar component should render as a div by default and button only if onClick props is defined

### ISSUE THREAD

**Issue by 6r3al** [Workday/canvas-kit#180]
## 🐛 Bug Report

The Avatar component is rendered as a button whether or not its onClick props is defined. 
However it can be used as a visual element only or it can already be included in a button in which case it would trigger the following warning error in the browser console:
`Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.`
The Avatar component would need to be rendered as a div by default and as a button only if its onClick props is defined.

## To Reproduce

Try to add the Avatar component with no onClick props as a child of a button element.

## Expected Behavior
If its onClick props is not defined, the Avatar component should be rendered as a div.
If its onClick props is defined, the Avatar component should be rendered as a button.

## Actual Results

Avatar component with no onClick props is rendered as a button.
The following warning error in the browser console:
`Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.`

### Error Output

<img width="742" alt="Screenshot 2019-09-11 at 12 31 38" src="https://user-images.githubusercontent.com/35978459/64693855-27d28d00-d490-11e9-831e-c38328dd9efa.png">

<img width="1156" alt="Screenshot 2019-09-11 at 12 31 05" src="https://user-images.githubusercontent.com/35978459/64693860-2d2fd780-d490-11e9-87ce-3a5586fe6c18.png">

**Comment by NicholasBoll** [comment]
@6r3al Thanks for filing an issue. We're having some internal discussions on what is an `Avatar`. It seems like there is really 2 different components - `Avatar` and `AvatarButton`. Implementing the solution as described (`div` vs `button` depending on `onClick`) basically requires defining 2 different interfaces and 2 different components and a wrapper component that returns one or the other depending on if `onClick` prop is defined. It seems like `Avatar` and `AvatarButton` would be very similar to `Icon` and `IconButton`.

This would be a breaking change for everyone depending on `Avatar` being an `AvatarButton`.

**Comment by 6r3al** [comment]
@NicholasBoll Thanks for getting back to me on this. Yes having 2 components `Avatar` and `AvatarButton` would make total sense to me and would be a great solution.

**Comment by anicholls** [comment]
Hey @6r3al, Thanks for agreeing to take this on! Here are the details we've decided on for implementation:
- We will add a second component (`AvatarButton`) that extends `AvatarProps`
- Both `Avatar` (default) and `AvatarButton` will be exported from the `@workday/canvas-kit-react-avatar` module
- The `Container` styled element will be changed to a div
- `AvatarButton` will wrap `Avatar` with a styled button
- The focus outline behavior will move from `Avatar` to the containing `AvatarButton` element
- The `onClick` and `buttonRef` props will move to `AvatarButton`

Let me know if you have any questions. Thanks again! 🎉
