### ISSUE TITLE
Select component's onChange typing does not specify HTMLSelectElement

### ISSUE THREAD

**Issue by zenblender** [Workday/canvas-kit#189]
## 🐛 Bug Report

The typing for the `Select` component's `onChange` prop should probably be `React.SyntheticEvent<HTMLSelectElement>` instead of `React.SyntheticEvent`.

## To Reproduce

I could not implement `onChange` without casting the event argument to `any` because otherwise I could not reference `e.currentTarget.value`.

This throws an error:
```
<Select
      value={value}
      onChange={(e) => {
        changeHandler(e.currentTarget.value)
      }}
>...</Select>
```

This works but requires `any`:
```
<Select
      value={value}
      onChange={(e: any) => {
        changeHandler(e.currentTarget.value)
      }}
>...</Select>
```

## Expected Behavior

I should be able to access `e.currentTarget.value` without any type casting.

## Link to repl or repo (highly encouraged)

https://github.com/Workday/canvas-kit/blob/5cba45e1bb15c47df24a587f99198d5d1939d700/modules/select/react/lib/Select.tsx#L16

### Error Output

![Screen Shot 2019-09-13 at 3 09 16 PM](https://user-images.githubusercontent.com/1471363/64895007-7fabf800-d638-11e9-8332-e320a40f718d.png)

**Comment by lychyi** [comment]
We'll also take a look if this is the only one that does this. It could be in other places of the codebase.

**Comment by lychyi** [comment]
We'll also take a look if this is the only one that does this. It could be in other places of the codebase.
