### ISSUE TITLE
When upgrading to v8, if theming isn't set properly, modals crash when using breakpoints from theming

### ISSUE THREAD

**Issue by mannycarrera4** [Workday/canvas-kit#1899]
## 🐛 Bug Report

In v8 we Introduced some styling based on breakpoints that come from theming. If consumers don't have this set up properly, they get the following error: 

```ModalOverlay.js:56 Uncaught TypeError: Cannot read properties of undefined (reading 'breakpoints')
    at ModalOverlay.js:56:1
    at handleInterpolation (emotion-serialize.browser.esm.js:139:1)
 ```
 
 If there is no default theme provided or CanvasProvider isn't set correctly this error will show up.
 
 I think we should update the upgrade guide to reflect this change and how to solve it as well as any other supporting information that might help our consumers.

**Comment by fizz3r** [comment]
This will also fail with 

`uncaught TypeError: Cannot read properties of undefined (reading 'down')
    at eval (ModalOverlay.js?2a8d:56:1)`

if you have the `CanvasProvider` setup as showed in the CK [docs](https://workday.github.io/canvas-kit/?path=/docs/tokens-common-theming--direction): 

```
<CanvasProvider
        theme={{
          canvas: {
            direction: state.isRTL ? ContentDirection.RTL : ContentDirection.LTR,
          },
        }}
       >
```
