### ISSUE TITLE
RadioGroup focus should focus the selected item

### ISSUE THREAD

**Issue by anicholls** [Workday/canvas-kit#190]
## 🐛 Bug Report

Based on the a11y spec, whenever a radio group receives focus, the selected item (if any) should receive focus, not the first one in the list.

## To Reproduce

- Render a `RadioGroup` with the second radio button selected
- Tab to the radio group

## Expected Behavior

- Second (selected) radio button is focused

## Actual Results

- First radio button is focused

### Error Output

![Screen Shot 2019-09-13 at 3 29 18 PM](https://user-images.githubusercontent.com/908478/64898253-46c15280-d63b-11e9-97ab-c6b849b51866.png)

**Comment by stephanerangaya** [comment]
Documentation: https://www.w3.org/TR/wai-aria-practices/examples/radio/radio-1/radio-1.html

**Comment by stephanerangaya** [comment]
I couldn't reproduce this. When I render a `RadioGroup` with the second radio button selected and I `Tab` into the `RadioGroup`, the focus is on the selected `Radio`.

**Comment by anicholls** [comment]
Yep, it appears this is working as intended. Going to close. Thanks for checking @stephanerangaya!
