### ISSUE TITLE
Impact switching Space and Depth to Rem

### ISSUE THREAD

**Issue by jaclynjessup** [Workday/canvas-kit#1911]
## 🔍 Spike /  Exploration

Before converting to use rem we need to discover the impact this will have

## What questions would be answered once this spike was completed?

1. How many teams are using their own rems vs. pixels?
2. For each usage scenario, how will introducing rem based depth and space tokens impact product teams? 
3. Can you opt-in/opt-out

**Comment by myvuuu** [comment]
Done
