### ISSUE TITLE
Popup Card maxHeight breaks calc when multiple values are provided

### ISSUE THREAD

**Issue by alanbsmith** [Workday/canvas-kit#1919]
## 🐛 Bug Report

When multiple values are provided to the Popup Card's margin prop, it breaks [the `calc` function](https://github.com/Workday/canvas-kit/blob/master/modules/react/popup/lib/PopupCard.tsx#L87-L89) used in the `maxHeight` property and invalidates the style.

E.g.
```tsx
// valid use of the margin prop
<Popup.Card margin="32px 24px">

// but it produces this which is not valid.
maxHeight: calc(100vh - 32px 24px * 2)
```

## To Reproduce

```tsx
<Popup.Card margin="32px 24px">
```

## Expected Behavior

You should be able to add a valid style to the margin shorthand prop and `maxHeight` not invalidated.

## Actual Results

`maxHeight` is invalidated.

### Reproduction

[CodeSandbox](https://codesandbox.io/s/v7-overflow-modal-ye2ze7?file=/src/OverflowModal.tsx)

**Comment by thunguyen19** [comment]
@alanbsmith When there are more than 2 values for `margin`, which value should we respect? `top`, `right`, `bottom`, `left`?
