### ISSUE TITLE
Prompt Spike

### ISSUE THREAD

**Issue by jaclynjessup** [Workday/canvas-kit#1928]
## 🔍 Spike /  Exploration

A prompt input has come up a lot recently for a Canvas Kit component.

## What questions would be answered once this spike was completed?

1. What is the scope that we could do within Canvas Kit? Can we support a bare bone prompt component?
2. Could this be a combination of ComboBox with search & pills?
3. What can we build with our primitives?
4. What changes do we need to make to combobox for it to handle multiselect, select, and autocomplete?

## Other Success Criteria?

1. Would any refactoring make creating this easier?
2. Should this be added (or not added) to Canvas Kit?

**Comment by NicholasBoll** [comment]
https://github.com/Workday/canvas-kit/discussions/1939
