### ISSUE TITLE
Convert Tooltip to a Compound Component

### ISSUE THREAD

**Issue by willklein** [Workday/canvas-kit#1936]
## 💡 Suggestion

The current API is a single JSX element that wraps a child element/component it enables a tooltip on. It does not expose its use of Popper or the styled `<div>`. The `title` prop ends up as a child of the styled div. This can be refactored to a compound component API for consistency, similar to the Form Field in Preview vs the one in Main.

Would like to keep the tooltip wrapper we currently have, could make this into the BaseTooltip.

**Comment by myvuuu** [comment]
Does not need to be a compound component
