### ISSUE TITLE
Explore options for incorporating testing on different screen sizes and modality

### ISSUE THREAD

**Issue by myvuuu** [Workday/canvas-kit#1949]
## 🔍 Spike /  Exploration

A spike should be conducted to help the Canvas team understand what/how to incorporate testing for different screen sizes and modality into our existing QA processes so that CKR components can be optimize for mobile web and WebView.

## What questions would be answered once this spike was completed?

1. How are other product teams testing across various screen sizes and modality?
2. What is the industry standard for testing mobile web and WebView experiences?
3. How can we incorporate these testing technique into our existing processes? 

## Other Success Criteria?

1. There will be experiences that we cannot test for ex. iPhone zooming
2. Identify the limitations of Chromatic - will this cause an increase in cost of plan

## Does this relate to any existing issues?

- https://github.com/Workday/canvas-kit/issues/1950

**Comment by RayRedGoose** [comment]
Chromatic and Cypress allow to write tests for different viewports. Chromatic applies touch modality automatically  to tests for mobile viewport. Cypress has functionality to change viewports and `.realTouch` event activating touch modality. 

Canvas Kit has a few components that looks differently depending on screen (or container) size or modality.  We don’t need to make big changes to our testing process, but we should add additional tests for those components.

There are components that should have additional tests to improve coverage:

- **Tabs**
    - add visual tests for overflow variant
    - add visual test for mobile screen
    - add cypress tests for touch modulity
- **ActionBar**
    - add visual tests for different container widths
    - add visual tests for below breakpoint viewport
    - add cypress tests for different container widths
- **Breadscrumb**
    - add cypress tests for different container widths
- **Modal**
    - add visual tests for mobile screen - 320px and 768px
    - add touch modality functionality test to cypress
