### ISSUE TITLE
Support for Non-Square Input Image for Avatar Component 

### ISSUE THREAD

**Issue by jstin** [Workday/canvas-kit#1960]
## 🐛 Bug Report

When providing a non-square image (aspect ratio != 1:1) as input to the Avatar component, the image is scaled to fit. It would be preferred if there was a setting to choose the css `object-fit` property for the image, such that a user could specify `object-fit: contain`. This will allow for letter boxing in the case of non 1:1 aspect ratio images.

Suggestion to add additional prop here, for `objectFit`
https://github.com/Workday/canvas-kit/blob/master/modules/react/avatar/lib/Avatar.tsx#L37

Docs specify 1:1 aspect ratio, so perhaps this is a feature request
https://github.com/Workday/canvas-kit/tree/master/modules/react/avatar#url-string

## To Reproduce

Provide a non-square image as input to the Avatar. See example in https://codesandbox.io/s/hungry-proskuriakova-6g3gcz

## Expected Behavior

If `object-fit` is set to `contain` or similar, letterboxing should appear, instead of a squished image. See example in https://codesandbox.io/s/hungry-proskuriakova-6g3gcz
<img width="590" alt="Screen Shot 2022-12-14 at 3 10 51 PM" src="https://user-images.githubusercontent.com/247896/207726052-45522b3b-64fc-4d3a-8d9b-417cd812cd8f.png">

## Actual Results

Without specifying the `object-fit` the image is squished to fit into a 1:1 aspect ratio.

## Browser (if applicable)

n/a

## Link to repl or repo (highly encouraged)

[Please provide a reference to a repo or branch to help us reproduce this bug.](https://codesandbox.io/s/hungry-proskuriakova-6g3gcz)

### Error Output
<img width="552" alt="Screen Shot 2022-12-14 at 3 07 27 PM" src="https://user-images.githubusercontent.com/247896/207725490-14886953-7692-40d2-8456-18c839388279.png">

**Comment by jaclynjessup** [comment]
Can use suggested fix or it is also possible to use Emotion to add the CSS style. Either via the styled API or the css prop
