### ISSUE TITLE
Depth Token Testing Group

### ISSUE THREAD

**Issue by jaclynjessup** [Workday/canvas-kit#1982]
## 🔍 Spike /  Exploration

We need to find teams that are on v8 & using the depth tokens that were released in v7.

## What questions would be answered once this spike was completed?

1. Ask teams that would fall into this category (ideally find different teams from design group)
2. See if they are in a state where they could pick up a stable alpha release in about 6 weeks / super sprint 30

## Does this relate to any existing issues?

- [ ] #1948

**Comment by alanbsmith** [comment]
I have three teams ready! Closing!
