### ISSUE TITLE
Removal of Menu in Preview

### ISSUE THREAD

**Issue by myvuuu** [Workday/canvas-kit#1993]
## 💡 Suggestion

Remove Menu in Preview. A newer version is already available in Main

## Acceptance Criteria
- [ ]  Remove the component
- [ ]  Remove the tests
- [ ]  Update the upgrade guide

**Note from moving to v10 from v9**

- Wait til v10 for removal of Menu and MenuItem in preview
- Get teams to move to Menu in main before it is removed in v10 by:
- Giving teams the Migration guide and code sandbox example to cover examples
- Support as we can

**Comment by alanbsmith** [comment]
Alan will look at who is using the preview menu so we can give advanced notice
