### ISSUE TITLE
Move Box, Flex, and Grid to a new "Layout" Folder in Storybook

### ISSUE THREAD

**Issue by myvuuu** [Workday/canvas-kit#2038]
## 💡 Suggestion

We created a new component category called "Layout" in v8 to store components that can be used to structure the layout of a page. This includes:

- Box
- Flex
- Stack (to be hard deprecated in v9)
- Grid

These changes have been applied to the Canvas site already, but those components are still listed in the Containers folder in Storybook and should be moved to a new "Layout" folder to maintain consistency

## Motivation

This creates more alignment between CK/Storybook and the Canvas DS site

## Work Required

- [ ] Create a new "Layout" folder in Storybook
- [ ] Move Box, Flex, and Grid to the new "Layout" folder
- [ ] Update the route.js file

**Comment by mannycarrera4** [comment]
So i purposely moved these out to simplify the storybook when the storybook reorg happened. These components are low level enough where I feel like they should be surfaced rather than hidden under another directory.
