### ISSUE TITLE
Rename soft and hard deprecation for clarity

### ISSUE THREAD

**Issue by alanbsmith** [Workday/canvas-kit#2042]
## 💡 Suggestion

There's been a considerable amount of confusion around soft and hard deprecation. We could likely clear that up by using new terms:

* Soft-deprecation -> deprecation (a warning)
* Hard-deprecation -> removal (it's completely removed)

## Acceptance Criteria

- [ ] Need to update this in every instance of the usage of terms  (for v9 and moving forward)
- [ ] Update glossary terms

**Comment by willklein** [comment]
Quick draft of comms (needs work), could go in the upgrade guide for v9:
> Note: In past major releases we've referred to "soft deprecation" for when a component is being renamed as "DeprecatedComponentName" with the intention to "hard deprecate" it in the next major release, which meant removing it. We are simplifying our language in this release and going forward; deprecation will not rename the component, but mark it with a JSDoc warning that it is deprecated. When* we remove it in a major version, it will be "removed."
