### ISSUE TITLE
Support CSS Variables in CKR components' style attribute

### ISSUE THREAD

**Issue by vibdev** [Workday/canvas-kit#2045]
## 🚀 Feature Proposal

CSS variables work great with `styled` components but not so much with standard CKR components. It would be nice if we could use them directly in the style attribute without the TS `as` operator.

Might be nice if you could somehow set them inline to get merged into the class too, but that can be an issue for another day.

-------

What I want:
```tsx
<div style={{ "--hot-takes": colors.chiliMango400 }} />
```

-------

What you need to do today:
```tsx
<div style={
    { "--hot-takes": colors.chiliMango400 } as React.CSSProperties
}/>
```

**Comment by NicholasBoll** [comment]
The `style` tag is not a prop we control. The `cs` prop does allow CSS variables as well as `createStyles` and `createStencil`
