### ISSUE TITLE
Layout/Column Grid not sizing inner cells correctly

### ISSUE THREAD

**Issue by nikolasjchaconas** [Workday/canvas-kit#205]
## 🐛 Bug Report

Building a `<Layout>` with `<Layout.Column columns=4>` with Images have a width of 100% in each cell, The center column is a smaller width than the outer columns because of inner padding.

## To Reproduce

Create a `<Layout>` with `<Layout.Column columns=4>` and put `<img>` tags with widths of 100%.

## Expected Behavior

All cells should be the same width and be spaced correctly.

## Actual Results

Cells along the center column have smaller widths than cells in the outermost columns.

## Browser (if applicable)

Chrome

![image](https://user-images.githubusercontent.com/10246689/65192882-a6e63900-da2d-11e9-9258-da79eceeb921.png)

**Comment by lychyi** [comment]
@nikolasjchaconas Thanks for reporting! If you know the fix, we'll gladly take contributions!

**Comment by sahlhoff** [comment]
@nikolasjchaconas I couldn't replicate this issue 100%, but I did find a similar issue where the gutters are not aligned for partial columns. Please take a look at this sandbox for more context: https://codesandbox.io/s/canvas-kit-issue-reproduction-oeqer. It would also be helpful to see if you could replicate this issue in a code sandbox. Thanks for reporting, I'll take a look at the issue discovered in this sandbox.
