### ISSUE TITLE
Using data-id with CK's Menu component causes the Menu Item to not be focuses when opening Menu

### ISSUE THREAD

**Issue by cheungspWorkday** [Workday/canvas-kit#2050]
## 🐛 Bug Report

When we add `data-id` to `<Menu.Item>` , it causes the menu items to not be focused when the menu opened.  
Confirmed that removing the `data-id` from `Menu.Item` fixes this bug. Will use `data-testid` for now until bug is fixed.

@willklein's explanation of why:

> it messes with something under the hood in our collection system, and the `cursorId` isn’t set the first time it’s opened. If there are two items, the second one that doesn’t have a `data-id` gets focused. If both have a `data-id`, nothing will focus

Canvas Kit version: ^8.0.6
Component: Menu (Main)
https://workday.github.io/canvas-kit/?path=/story/components-popups-menu--icons

## To Reproduce

Set a `data-id` with any string value on the first `<Menu.Item>` and open the Menu. It will not be focused.

@willklein's CodeSandbox: https://codesandbox.io/s/menu-data-id-issue-5z2lpi?file=/src/App.tsx

## Expected Behavior

The Menu item should be focused when Menu is opened, even when `data-id` is added to the `<Menu.Item>`

## Actual Results

The `Menu item` with `data-id` doesn't get focused the first time the menu is opened, however subsequent opens will focus correctly.

## Browser (if applicable)

Chrome + Safari

## Link to repl or repo (highly encouraged)

https://codesandbox.io/s/menu-data-id-issue-5z2lpi?file=/src/App.tsx

### Error Output

Paste the error output here

Video if needed: https://www.loom.com/share/b30c75ac6eeb4ab18cdf7ee91b15adf1

**Comment by mannycarrera4** [comment]
v8 is no longer supported. I was able to reproduce, but this has been fixed in v9 which is also no longer supported. We're currently on v11. If you need a work around for v8, you can either pass `id` instead of `data-id` and this will work.
