### ISSUE TITLE
Toast labs component has styling issues with short messages

### ISSUE THREAD

**Issue by ahayes91** [Workday/canvas-kit#2060]
## 🐛 Bug Report

I'm in the process of migrating to the Toast component in labs (due to be released to Main in v9 as per https://github.com/Workday/canvas-kit/issues/1935) and I noticed that if you have a short toast message, the fixed/min-width in the toast CSS causes the close icon to become misaligned. 

## To Reproduce

Supply some short text to `Toast.Message` to a toast with a close icon, e.g. "Some details updated" - I used one of the team's previous code sandbox examples to demo this for a Toast within a Popup system:

[![Edit Popup Toast Labs (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/popup-toast-labs-forked-36vjqy?fontsize=14&hidenavigation=1&theme=dark)

## Expected Behavior

You can put in a hack to set a min-width of 258px div around the message body to show what should happen (if we always want toasts to have a fixed width rather than shrink / grow to content - that's up to you folks 😁 )

![Screenshot 2023-03-03 at 16 23 47](https://user-images.githubusercontent.com/8914051/222773376-4ddf550e-46df-4906-a0d1-7b4b3bfcb764.png)

## Actual Results

![Screenshot 2023-03-03 at 16 21 58](https://user-images.githubusercontent.com/8914051/222773009-3f944a9e-b140-4cf3-981f-a399e61778f2.png)

## Browser (if applicable)

Chrome

## Link to repl or repo (highly encouraged)

[![Edit Popup Toast Labs (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/popup-toast-labs-forked-36vjqy?fontsize=14&hidenavigation=1&theme=dark)

### Error Output

Screenshots provided above

**Comment by mannycarrera4** [comment]
Ah thanks for reporting this! I found this while working on https://github.com/Workday/canvas-kit/issues/1935 ! We'll fix this in v9!

**Comment by ahayes91** [comment]
Way ahead of me Manuel! Thanks so much 💯

**Comment by mannycarrera4** [comment]
Looks like [this](https://github.com/Workday/canvas-kit/pull/2044/files#diff-8b7a88b5b016f1862c9fbc17c4dde4c3850560b5d6baec87cd55d3dde7330fbeR20) should do the trick, but I'll be sure to add this use case in our testing as well

**Comment by mannycarrera4** [comment]
As a work around, you can add flexGrow to the `Toast.Body`

[Sandbox](https://codesandbox.io/s/popup-toast-labs-forked-26ps60?file=/src/App.tsx)
