### ISSUE TITLE
Add style props for Box

### ISSUE THREAD

**Issue by josh-bagwell** [Workday/canvas-kit#2133]
## 🚀 Feature Proposal

Add the following style props on `Box`:

- `clip-path` 
- `borderImageSource`
- `borderImageSlice`

## Motivation

It's a CSS Property we do not have access to currently on `Box`.

**Comment by alanbsmith** [comment]
We can also add `WebkitBackgroundClip` and `WebkitTextFillColor`, but let's see if Emotion will add the `webkit-` prefix for us. I'd prefer we use `backgroundClip` and `textFillColor` for the prop names if possible.

**Comment by jaclynjessup** [comment]
Post v10 we are moving in a different direction, see #2416
