### ISSUE TITLE
Callback typings need updating

### ISSUE THREAD

**Issue by lychyi** [Workday/canvas-kit#215]
## 🐛 Bug Report

We should reconsider how exact we need to/should be making our callback signatures in our props. Just using `React.SyntheticEvent` for example, causes issues like #189.

Today, we're all over the place with how it gets defined. Sometimes we defined them as `React.FooEventHandler<HTMLBarElement>`, sometimes we do `(e: React.SyntheticEvent) => void` sometimes we do (e: React.MouseEvent<HTMLButtonElement>), etc.

We also need to be documenting this in our API guidelines and set a standard.

**Comment by vibdev** [comment]
Personally I think React.FooEventHandler<HTMLBarElement> is the easiest to read

**Comment by myvuuu** [comment]
Fixed in #212
