### ISSUE TITLE
doc parser fix for naming collisions

### ISSUE THREAD

**Issue by jaclynjessup** [Workday/canvas-kit#2187]
There is an issue with the Doc Parser with naming collisions with Subcomponents. For example, in the new Table component that is in preview, it is pulling existing JSDocs from the old Table that is in main. TableRow is used in both components as a subcomponent and the parser does not pull from the correct component's JSDocs.

**Comment by josh-bagwell** [comment]
There is an issue with the Doc Parser with naming collisions with Subcomponents. For example, in the new `Table` component that is in preview, it is pulling existing JSDocs from the old `Table` that is in main.  `TableRow` is used in both components as a subcomponent and the parser does not pull from the correct component's JSDocs.
