### ISSUE TITLE
Popup -     Line 47:  'setAnchorEl' is not defined  no-undef   Line 47:  'anchorEl' is not defined     no-undef

### ISSUE THREAD

**Issue by rohinihonmute** [Workday/canvas-kit#219]
import React from 'react';
import { NavLink } from "react-router-dom";
import { actionCreators } from '../../Actions/Employee';
import { bindActionCreators } from 'redux';
import { connect } from 'react-redux';
import axios from 'axios';
import { Button } from '@workday/canvas-kit-react-button';
import { Popup } from '@workday/canvas-kit-react-popup';

//import  Popper from '@material-ui/core/Popper';
//import Popover, { PopoverAnimationVertical } from 'material-ui/Popover';
import { Popover, Popper} from '@material-ui/core';

export default class List extends React.Component {
    
    constructor(props) {
        super(props);
        console.log(this.props)
        this.state = { EmployeeList: [], open: false }
        const [anchorEl, setAnchorEl] = React.useState(null);
    

    }
  
    componentDidMount() {

      

        axios.get('api/Employee/getEmployee')
            .then(res => {
                if (res.status == 200) {
                    this.setState({ EmployeeList: res.data }); //this is an asynchronous function
                }
                else {
                    alert("something went wrong")
                    this.setState({ EmployeeList: [] });
                }
            })
    }

    handleClose(event) {
        this.setState({ open: false });       
    };
  
    delete(event) {
        debugger;
        setAnchorEl(anchorEl ? null : event.currentTarget);
        console.log("called");// this.setState(this.item.id)
        this.setState({ open: true}); 
        console.log(this.props)
    }

    render() {
        console.log(this.props)        
        return (
        <div>
            <h1> In List </h1>               
            <table className="wdc-table">
            <thead>
                <tr className="wdc-table-row-selected">
                  <th>First Name</th>
                  <th>Middle Name</th>
                  <th>Last Name</th>
                  <th>Grade</th>
                  <th>Job Title</th>
                  <th>Edit</th>
                  <th>Delete</th>
                </tr>
            </thead>
            <EmployeeList items={this.state.EmployeeList} _handleDelete={this.delete.bind(this)} />           
            </table>
                <Popper placement={'bottom'} open={this.state.open} anchorEl={anchorEl}>
                <Popup
                    width={300}
                    heading={'Popup Title'}
                    padding={Popup.Padding.l}
                    handleClose={this.handleClose.bind(this)}>
                    {this.props.children}
                </Popup>
            </Popper>
        </div>
        )
    }
}

class EmployeeList extends React.Component {

    _handleDelete(event) {
        debugger;
        this.props._handleDelete(event);
    }

    render()
    {
        return (
            <tbody> 
                {this.props.items.map(data => (                   
                    < tr key={data.id}>
                        <td>{data.fname}</td>
                        <td>{data.mname}</td>
                        <td>{data.lname}</td>
                        <td>{data.grade}</td>
                        <td>{data.jobTitle}</td>
                        <td><NavLink to={"/NewForm/" + data.id} >Edit</NavLink></td>
                        <td>
                            <button className="wdc-btn wdc-btn-delete" onClick={this._handleDelete.bind(this)}>Delete</button>
                        </td>
                    </tr>
                ))}
            </tbody>
        );
    }
}

**Comment by rohinihonmute** [comment]
Hi Team,
I am trying to open popup on delete button .
getting this issue .
please provide me suggestions or example to implement popup in react class.

**Comment by lychyi** [comment]
Hi @rohinihonmute, the Github issues platform is for filing bugs against the codebase. It is not intended to be a help forum and I do not believe this is a bug with our codebase.

Per our issues template:

```
### Please note that this issue tracker is not a help form and this issue will be closed
```

With that said, for this time only... the error you're getting in the subject line denotes a linter error in which you are attempting to use things that are undefined. It is not a compiler error or an error in the code. It is helping you catch a bug while you are developing in where you're defining a block-scoped (`const`) variable in your constructor and trying to use it outside of that block.

In addition, you're trying to use a `useState` hook within a class which will not work the way you intend it to.
