### ISSUE TITLE
Date and Time picker?

### ISSUE THREAD

**Issue by rohinihonmute** [Workday/canvas-kit#220]
Hello,
Don't we have time picker and date picker in Canvas kit?

**Comment by lychyi** [comment]
Hi @rohinihonmute, we do not yet. There's some fairly complicated logic that goes with date/time pickers so we're holding off until we can pursue a good solution.

We'll keep the [Component Status](https://github.com/Workday/canvas-kit/blob/master/COMPONENT_STATUS.md) up-to-date as we get it on the roadmap!
