### ISSUE TITLE
FormField: Support multiple messages

### ISSUE THREAD

**Issue by NicholasBoll** [Workday/canvas-kit#223]
## 🚀 Feature Proposal

Design has requested the ability for FormFields to handle more than a single message and more than one type of message.

## Motivation

There can be more than a single error or hint for a form field. The screenshot below shows an example.

## Example

![Screen Shot 2019-09-26 at 9 41 57 AM](https://user-images.githubusercontent.com/338257/65703612-503ab980-e042-11e9-8bdc-9f5899e58b02.png)

**Comment by stephanerangaya** [comment]
@NicholasBoll Is the screenshot coming from design, can we consider that as spec?

**Comment by NicholasBoll** [comment]
@stephanerangaya Yes. It can probably be introduced as a non-breaking change by accepting an array of messages and types

**Comment by NicholasBoll** [comment]
This is no longer a request. We'll re-evaluate if it comes back

**Comment by jpante** [comment]
Reopening to look at supporting this across Workday

**Comment by myvuuu** [comment]
Should check back with design for more up to date specs and development

**Comment by jaclynjessup** [comment]
Not something we are in current need of. Will reopen if this arises again

**Comment by jaclynjessup** [comment]
Not something we are in current need of. Will reopen if this arises again
