### ISSUE TITLE
Pulling CSS variables into Canvas Kit React

### ISSUE THREAD

**Issue by jaclynjessup** [Workday/canvas-kit#2233]
- Update theme object in `CanvasProvider` to use CSS vars
- Maybe export CSS var stylesheet from Canvas Kit as a convenience for consumers (you decide!)
- Update CanvasProvider and Theming documentation to help consumers understand how to use CSS variables and Emotion theme for theming
- Add documentation to V10 upgrade guide

**Comment by myvuuu** [comment]
Blocks #2274

**Comment by myvuuu** [comment]
Closing, work being completed as part of the Button Refactoring
