### ISSUE TITLE
`useFocusRedirect` does not handle focus leave from radio group in Popup

### ISSUE THREAD

**Issue by pablobirukov** [Workday/canvas-kit#2257]
## 🐛 Bug Report

`useFocusRedirect` does not handle focus leave from Popup when a radio group is the last element in the popup

## To Reproduce

Have a [Popup with radio group](https://github.com/pablobirukov/canvas-kit/pull/1/files)

https://codesandbox.io/s/focus-redirect-with-radio-group-3562q2

Open popup, move focus with Tab to radio group, move focus with Tab further

## Expected Behavior

Popup is to close and focus is to move to the element following Popup trigger

Radio group behaves as it's a single focusable element, [spec](https://www.w3.org/wiki/RadioButton)

## Actual Results

focus leaves the document as if radio group was the last focusable element in the document (which it is)

## Browser (if applicable)

FF, Chrome

## Link to repl or repo (highly encouraged)

https://codesandbox.io/s/focus-redirect-with-radio-group-3562q2

### Error Output

https://github.com/Workday/canvas-kit/assets/1861546/735fd15b-95f7-4745-abe8-69f3ce074e93

**Comment by NicholasBoll** [comment]
I've updated the issue to includes a code sandbox link
