### ISSUE TITLE
[Toast] Non-uniform horizontal spacing around Toast Message

### ISSUE THREAD

**Issue by nramamurth** [Workday/canvas-kit#2268]
## 🐛 Bug Report

A strange behavior is noticed in how `Toast.Message` is rendered on Storybook v/s standalone in Code Sandbox. 

**Codesandbox:** The message is wrapped as expected: https://codesandbox.io/s/ck-v9-toast-fmcpyv?file=/src/App.tsx

**Storybook:** The text does not wrap as it does in the code sandbox example above and the text does not look aligned (?). 

## To Reproduce

Run canvas-kit storybook and supply longer text to `Toast.Message`. 

## Expected Behavior

Wrap message with uniform spacing around it.

## Actual Results

Non-uniform horizontal spacing around the message that does not wrap. 

## Browser (if applicable)

Chrome.

## Link to repl or repo (highly encouraged)

https://codesandbox.io/s/ck-v9-toast-fmcpyv?file=/src/App.tsx

### Error Output

<img width="1720" alt="Screenshot 2023-06-22 at 2 58 04 PM" src="https://github.com/Workday/canvas-kit/assets/10090859/fa3033bd-c725-469c-95e6-d3567b603ffa">

**Comment by myvuuu** [comment]
Hey Naveen! This seems to have resolved as of v11, I am not seeing the same issue in storybook v10 or v11. I'll go ahead and close this ticket out, but please feel free to reopen if you're still experiencing this issue.
