### ISSUE TITLE
Add home page to Storybook docs

### ISSUE THREAD

**Issue by lychyi** [Workday/canvas-kit#227]
## 🚀 Feature Proposal

Show a welcome page as the default story in our Storybook (instead of the first component that happens to pop up).

## Motivation

We now have stories for `CSS`, `React`, and `Labs`. We also are being powered by generous OSS sponsors: Chromatic QA, Netlify, and Travis. It would be great to give those folks a shoutout on our deployed assets.

Finally, it would be good to get content writing in on the "first impression" for our Storybook so that it is easier to navigate.

**Comment by NicholasBoll** [comment]
👍 

It is possible to set the order of stories in the config

**Comment by lychyi** [comment]
Done via #296
