### ISSUE TITLE
Rewrite color utility to use ChromaJS

### ISSUE THREAD

**Issue by lychyi** [Workday/canvas-kit#229]
## 🚀 Feature Proposal

Upgrade [Chroma JS](https://github.com/gka/chroma.js/) to version 2.x (2.0.6 as of writing)

## Motivation

We use Chroma for some color manipulations and we also export a [function](https://github.com/Workday/canvas-kit/blob/5bdee566dbf9fb77b80957c08ddf31859e0c32cd/modules/common/react/lib/utils/colorUtils.ts) that calculates color usage based on accessibility which Chroma already does.

## Outline
* Update chroma-js to 2.x
* Update @types/chroma-js to latest
* Rewrite the color utility that picks foreground color to only use Chroma instead of calculating relative lum (no need to re-invent the wheel)

**Comment by anicholls** [comment]
Updated chroma-js version to 2.1.0 as part of #272. Still need to rewrite the color utility though.

**Comment by NicholasBoll** [comment]
Fixed by #700
