### ISSUE TITLE
When Combobox is used within a Dialog, clicking on an option closes the Dialog.

### ISSUE THREAD

**Issue by mannycarrera4** [Workday/canvas-kit#2314]
## 🐛 Bug Report

When an Autocomplete is used within a Dialog, selecting an option closes the dialog.

## To Reproduce

[Steps to reproduce the behavior:](https://codesandbox.io/s/adoring-monad-5p7ksq?file=/src/Autocomplete.tsx)

## Expected Behavior

We could probably updated the docs/ or examples to account for this to prevent propagation instead of adding that as the default behavior.

**Comment by alanbsmith** [comment]
This isn't really a bug, just a behavior you might not initially expect. The click event on the menu propagates up to the dialog and closes it as well. We can add a few lines in our docs about this.

**Comment by NicholasBoll** [comment]
I think `stopPropagation `and `preventDefault `should be used with extreme caution.

`preventDefault `should not be used without understanding the default action that is meant to be associated with an event and why.

`stopPropagation `should be used as a last resort when all other options have been eliminated and why we want to stop propagation and why something propagating is causing issues.

In this case, it looks like the dialog closes on a mouse down event and not a click. This suggests to me the [useCloseOnOutsideClick ](https://github.com/Workday/canvas-kit/blob/803e504ebbca7db32a38d6bdf86a93752aa3da1a/modules/react/popup/lib/hooks/useCloseOnOutsideClick.ts) is triggering which is calling [PopupStack.contains](https://github.com/Workday/canvas-kit/blob/803e504ebbca7db32a38d6bdf86a93752aa3da1a/modules/popup-stack/lib/PopupStack.ts#L348-L373) to determine if the `mousedown `event is from a "child" of the element. There is something the Princess popup stack calls "autohide partners". The Canvas Popup stack does not have the concept of "autohide partners", but has a concept of "ownership" that accomplishes the same thing.

The intent is a "popup target" should be registering as an owner of any popup for the purposes of determining virtual parent elements. For example, if you click inside a popup, the popup stack will look up the owner of that popup - usually the "target". From there, it will see if the target is inside another popup. This continues until the `document.body` element is found. The effect is clicking inside a popup launched from another popup should not close the original popup.
