### ISSUE TITLE
Review v10 upgrade guide

### ISSUE THREAD

**Issue by jaclynjessup** [Workday/canvas-kit#2348]
## 💡 Suggestion

Let's do a final cleanup of the V10 upgrade guide to get the formatting / copy / examples really consistent and easy to read.

## Motivation

This last polish step has helped us a lot with previous major releases. It's hard to make things consistent while you're in it, and a cleanup helps bring it all together.

## AC

- [ ]  Review upgrade guide that were updated as part of v10
- [ ]  Modify v10 documentation (including the upgrade guide) as needed
- [ ] Migration guide should read within one voice/rhythm
- [ ] Follow same structure & pattern as previous guides look at v7/v8/v9 example

**Comment by mannycarrera4** [comment]
@jamesfan something to note for this:
- Review Documentation around Styling feature
- Add info about styling that Nicholas introduced to the upgrade guide
- Add info/ review info for buttons
