### ISSUE TITLE
Modal covered by bottom address bar on iPhone

### ISSUE THREAD

**Issue by mike-kerley** [Workday/canvas-kit#2352]
## 🐛 Bug Report

The `Modal` component is partially covered by the bottom address bar on mobile browsers, making it impossible to click/tap on action buttons at the bottom.

## To Reproduce

Create a `<Modal>` like the one in https://workday.github.io/canvas-kit/?path=/docs/components-popups-modal--basic. View it from a mobile simulator/emulator.

## Expected Behavior

Modal is fully visible and buttons can be clicked/tapped

## Actual Results

Modal is partially covered as shown below

## Browser (if applicable)

* iPhone Safari (iOS 17)
* Default Samsung mobile browser, using latest android on Samsung S23

## Link to repl or repo (highly encouraged)

https://github.com/mike-kerley/canvas-kit-modal-demo

### Error Output

<image src="https://github.com/Workday/canvas-kit/assets/58498830/469f6f07-afd0-41b9-9923-ef3683f2c40b" width="325">

**Comment by mike-kerley** [comment]
I believe this is caused by the use of `100vh` and `alignItems: 'end'` in `ModalOverlay`:
https://github.com/Workday/canvas-kit/blob/2c0010f61e0f2dbeeb1436ac2b79eb806d8bb91c/modules/react/modal/lib/ModalOverlay.tsx#L58-L61

Safari (and apparently Samsung's browser) include the toolbar area in their viewport height calculation.

**Comment by mannycarrera4** [comment]
When testing, make sure to open storybook in a new iframe and then set the viewport, otherwise storybook knows to shrink the viewport and the bug isn't reproducible.
