### ISSUE TITLE
If a RadioGroup is the first focusable element in a Popup, the useInitialFocus hook moves the focus to the first radio option instead of the selected option when popup opens

### ISSUE THREAD

**Issue by Victor-Meng-Workday** [Workday/canvas-kit#2384]
## 🐛 Bug Report
If a `RadioGroup` component is the first focusable element inside a `Popup` component, then the `useInitialFocus` hook will always move the focus to the first radio option when the popup opens. The expected behavior is that the selected radio option should be focused when the popup opens.

## To Reproduce
1. Create a `Popup` component and enable `useInitialFocus` on the popup.
2. Add a `RadioGroup` component as well as several `Radio` (main version) or `RadioGroup.RadioButton` (preview version) components inside the popup.
3. Select any radio option that's not the first option, e.g. the second option.
4. Open the popup: notice that the first radio option is focused even though the second option is selected.

## Expected Behavior
The selected radio option should be focused when the popup opens.

## Actual Results
The first radio option is focused when the popup opens.

## Browser (if applicable)

If this was a visual bug, what browser did you spot it on?

## Link to repl or repo (highly encouraged)

Please provide a reference to a repo or branch to help us reproduce this bug.

### Error Output

https://github.com/Workday/canvas-kit/assets/148582228/be66e2c1-891d-4034-8f8c-a083a459f106

**Comment by thunguyen19** [comment]
@Victor-Meng-Workday I think you may need to pass in the `initialFocusRef` to the `usePopupModel` and the `RadioGroup` props `ref` for this to work. `useInitialFocus` needs to keep track of the ref (https://github.com/Workday/canvas-kit/blob/master/modules/react/popup/lib/hooks/useInitialFocus.tsx#L29). Otherwise it'll go getFirstFocusableElement.

I tried the below reproduction and did not observe the issue anymore.
```
//
const initialFocusRef = React.useRef<HTMLInputElement>(null);

// create the popup model
const model = useModalModel({
    initialFocusRef,
});

// enable useInitialFocus on the popup
useInitialFocus(model);

// Pass the `initialFocusRef` into RadioGroup props
return (
   <Popup model={model}>
       ....
        <RadioGroup onChange={handleChange} value={value} ref={initialFocusRef}>
          <Radio label="bla-bla" name="bla-bla"/>
        </RadioGroup>
    </Popup>
);
```
