### ISSUE TITLE
System Icon Styles Refactor

### ISSUE THREAD

**Issue by jaclynjessup** [Workday/canvas-kit#2391]
## 🚀 Feature Proposal

System Icon style re-factor is needed with the new `cs` prop that has been created. We will also need to update the System Icon to use the new system level tokens via CSS variables from the CanvasProvider.

**Acceptance Criteria:**
- All Canvas System Icon variants are tied to CSS variables
- Update the v11 upgrade guide

## Motivation

This will utilize the new `cs` prop and we now have access to new css properties

## Other
remove default hover state and use component tokens

**Comment by myvuuu** [comment]
Completed
