### ISSUE TITLE
SPIKE primitive/low-level components post v10

### ISSUE THREAD

**Issue by jaclynjessup** [Workday/canvas-kit#2416]
## 🔍 Spike /  Exploration

With the restyling effort to move towards static styling Box, Flex, Stack, Text & Grid Components. This spike will investigate the path forward for v11 and beyond in regards to these components and our styling approach with eh `cs` prop and new CSS package.

## What questions would be answered once this spike was completed?

1. If we stop using these within CKR and deprecate in v11, what does that look like
2. Can we have a codemod by v11 for these?
3. Should we have a createStyledComponent to have access to all styles at each level without calling base at each level?

**Comment by mannycarrera4** [comment]
Summary of the spike: https://github.com/Workday/canvas-kit/discussions/2430
