### ISSUE TITLE
Pill read-only variant

### ISSUE THREAD

**Issue by elspinn** [Workday/canvas-kit#2428]
## 🐛 Bug Report

The Pill `variant=readOnly` styles the background color on-hover.

## To Reproduce

Can be seen in the [Canvas Pill documentation ](https://canvas.workdaydesign.com/components/indicators/pill/#tab=web&heading=read-only)
Move cursor over read only pill to see style change.

## Expected Behavior

On hover the background should not change color

## Actual Results

On hover the background changes color

## Browser (if applicable)

Firefox 120.0
Chrome 119.0.6045.159

## Link to repl or repo (highly encouraged)

[Canvas Read Only Pill Docs](https://canvas.workdaydesign.com/components/indicators/pill/#tab=web&heading=read-only)

### Error Output

<img width="775" alt="Screenshot 2023-11-24 at 12 58 44" src="https://github.com/Workday/canvas-kit/assets/23078574/4f1be319-0a94-4e40-a26b-051464f8c278">

**Comment by alanbsmith** [comment]
Looks like BaseButton styles are leaking:

```css
var(--css-button-vars-hover-background, var(--cnvs-base-palette-black-pepper-500, #1e1e1e));
```

Here's the [line](https://github.com/Workday/canvas-kit/blob/master/modules/react/button/lib/BaseButton.tsx#L177-L187) in BaseButton.

**Comment by mannycarrera4** [comment]
```
 cs={{
            '&:hover': {backgroundColor: 'transparent', border: `1px solid ${colors.licorice200}`},
          }}
```
Alan pointed that the styles are leaking, adding this to StyledNonInteractivePill will fix it, but not sure if that's the right solution
