### ISSUE TITLE
Bug: SearchForm is forwarding props to DOM elements

### ISSUE THREAD

**Issue by alanbsmith** [Workday/canvas-kit#2458]
## 🐛 Bug Report

`SearchForm` is forwarding component props to the underlying DOM element.

- `isCollapsed`
- `isHidden`
- `showForm`
- `shouldShow`

## To Reproduce

- See the sandbox linked below

## Link to repl or repo (highly encouraged)

[Sandbox](https://codesandbox.io/s/search-form-console-warnings-rlnsv9)

### Error Output

```
Warning: React does not recognize the `shouldShow` prop on a DOM element. If you 
intentionally want it to appear in the DOM as a custom attribute, spell it as 
lowercase `shouldshow` instead. If you accidentally passed it from a parent component, 
remove it from the DOM element.
button
```

**Comment by alanbsmith** [comment]
This isn't breaking anything, but we should clean it up.

**Comment by dawitadmassu** [comment]
Hi @alanbsmith 

I want to contribute here. 
I can help on cleaning this up. can you give me your guidance?
