### ISSUE TITLE
Add a Select example with a placeholder option

### ISSUE THREAD

**Issue by mannycarrera4** [Workday/canvas-kit#2512]
## 💡 Suggestion

It's common enough to have a placeholder option in select Here's an [example](https://codesandbox.io/p/sandbox/v10-select-demo-forked-45ppj3?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clq2lh9cg00073b6jfndf9trw%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clq2lh9cg00033b6jf1wtzfx2%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clq2lh9cg00043b6j45zgm1tz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clq2lh9cg00063b6jt7k8p9mc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clq2lh9cg00033b6jf1wtzfx2%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq2lh9cg00023b6jq04d4byq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A51%252C%2522startColumn%2522%253A3%252C%2522endLineNumber%2522%253A51%252C%2522endColumn%2522%253A48%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clq2lh9cg00033b6jf1wtzfx2%2522%252C%2522activeTabId%2522%253A%2522clq2lh9cg00023b6jq04d4byq%2522%257D%252C%2522clq2lh9cg00063b6jt7k8p9mc%2522%253A%257B%2522id%2522%253A%2522clq2lh9cg00063b6jt7k8p9mc%2522%252C%2522activeTabId%2522%253A%2522clq2lh9cg00053b6jizu62aig%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq2lh9cg00053b6jizu62aig%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522SANDBOX_INFO%2522%252C%2522id%2522%253A%2522clr6yt32w003c3b6lv9y4i5pw%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clq2lh9cg00043b6j45zgm1tz%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clq2lh9cg00043b6j45zgm1tz%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Selects are different than inputs so the placeholder attribute doesn't quite work. But adding a choose option is a valid way to do this as seen in this [example](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/)

We should add a placeholder example to the Select MDX.

**Comment by playstore777** [comment]
Hello, I am not able to run the code locally.
I am getting 
![image](https://github.com/Workday/canvas-kit/assets/67255734/a53b7df9-a916-4a05-8503-b4199db90088)


I tried deleting node_modules and reinstalling packages using Yarn and NPM but nothing worked got the same error all the times.

Please let me know if I am missing any step I followed all the steps given [here](https://canvas.workday.com/getting-started/for-developers/contributing/#getting-started-developing:~:text=version%20to%20NPM.-,Getting%20Started%20Developing,-Clone%20the%20repository)

I am using on

> Visual Studio Code Version: 1.87.2 (user setup)
> Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
> Date: 2024-03-08T15:20:17.278Z
> Electron: 27.3.2
> ElectronBuildId: 26836302
> Chromium: 118.0.5993.159
> Node.js: 18.17.1
> V8: 11.8.172.18-electron.0
> OS: Windows_NT x64 10.0.19045

**Comment by mannycarrera4** [comment]
There's an example with placeholder already

**Comment by mannycarrera4** [comment]
@playstore777 it looks like there's an issue downloading the fonts. Not sure what's going on but feel free to open up an issue instead of using this one to report something.
