### ISSUE TITLE
Text Input Style Refactor - Color Tokens

### ISSUE THREAD

**Issue by myvuuu** [Workday/canvas-kit#2650]
## 🚀 Feature Proposal

We will need to update the Text Input to use the new system color tokens.

Acceptance Criteria:

- All Text Input variants are using to system color tokens
- Update the v11 upgrade guide

## Motivation

This will utilize the new color tokens

## Example

Please provide an example for how this feature would be used.

**Comment by jaclynjessup** [comment]
Combining with #2648
