### ISSUE TITLE
Select flashes when clicking on the input when the menu is open

### ISSUE THREAD

**Issue by NicholasBoll** [Workday/canvas-kit#2868]
## 🐛 Bug Report

The `<Select>` component now closes during the `mousedown` event on the `combobox` input and a `click` event opens it again.

`<Select>` changed to using 2 `input` elements starting in [v10.3.5](https://github.com/Workday/canvas-kit/releases/tag/v10.3.5). 

## To Reproduce

[v10.3.5](https://5d854c26ba934e0020f5e98a-btitxuitxu.chromatic.com/?path=/story/components-inputs-select--basic)

Open the Select. Click on the select input element

## Expected Behavior

It should close after a click like it does in [v10.3.4](https://5d854c26ba934e0020f5e98a-wvyddxibfh.chromatic.com/?path=/story/components-inputs-select--basic)

## Actual Results

The menu flashes as it disappears while during the `mousedown` event and opens again during the `click` event.

**Comment by mannycarrera4** [comment]
Fixed : https://github.com/Workday/canvas-kit/releases/tag/v10.3.52
