### ISSUE TITLE
Select Input with Canvas Menu

### ISSUE THREAD

**Issue by jpante** [Workday/canvas-kit#294]
## 🚀 Feature Proposal

Currently the `Select` component uses the native drop down.

To align to Canvas specifications the drop down should be styled to match the canvas menu style.

<img width="447" alt="Screen Shot 2019-11-03 at 4 53 11 PM" src="https://user-images.githubusercontent.com/1861673/68094985-75e58a80-fe5a-11e9-822d-ad9b081ccff1.png">

**Comment by lychyi** [comment]
Courtesy of @stephanerangaya 

https://24ways.org/2019/making-a-better-custom-select-element/
