### ISSUE TITLE
canvas-kit-css-icons is not publishing an index.scss file

### ISSUE THREAD

**Issue by icfantv** [Workday/canvas-kit#302]
## 🐛 Bug Report

The published module `canvas-kit-css` publishes an index.scss file at the root module level that references `canvas-kit-css-icon/index.scss` file but the published version of that latter module does not contain an index.scss file at the root module level (or at all).

## To Reproduce

N/A

## Expected Behavior

N/A

## Actual Results

N/A

## Browser (if applicable)

N/A

## Link to repl or repo (highly encouraged)

N/A

### Error Output

Paste the error output here

```bash
ERROR in ./src/styles/styles.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@workday/canvas-kit-css-icon/index.scss';
^
      File to import not found or unreadable: ~@workday/canvas-kit-css-icon/index.scss.
      in /Users/adam.gordon/code/mcc/designer-ui/node_modules/@workday/canvas-kit-css/index.scss (line 9, column 1)
    at runLoaders (/Users/adam.gordon/code/mcc/designer-ui/node_modules/webpack/lib/NormalModule.js:286:20)
    at /Users/adam.gordon/code/mcc/designer-ui/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/adam.gordon/code/mcc/designer-ui/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/adam.gordon/code/mcc/designer-ui/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.render [as callback] (/Users/adam.gordon/code/mcc/designer-ui/node_modules/sass-loader/lib/loader.js:52:13)
    at Object.done [as callback] (/Users/adam.gordon/code/mcc/designer-ui/node_modules/neo-async/async.js:8067:18)
    at options.error (/Users/adam.gordon/code/mcc/designer-ui/node_modules/node-sass/lib/index.js:294:32)
 @ ./src/presenter/NotificationDesignerPresenter.tsx 30:0-33
 @ ./src/index.ts
```

**Comment by anicholls** [comment]
Thanks for the issue! This is an easy one. We're just missing a line for `index.scss` [here](https://github.com/Workday/canvas-kit/blob/master/modules/icon/css/package.json#L9).

**Comment by vibdev** [comment]
Looks like canvas-kit-css-text-input is missing too, I don't see it or the other form fields in node_modules/@workday

**Comment by icfantv** [comment]
@anicholls @NicholasBoll if you guys don't get to this today, I can look at a PR Monday as I'm in PLS all week but will be back in Boulder then.  PLMK.

**Comment by mannycarrera4** [comment]
@icfantv we'll address it today! thanks!

**Comment by vibdev** [comment]
@mannycarrera4 maybe what I am seeing with the form inputs is a separate issue will refile 👍
