### ISSUE TITLE
ChildrenContainer component in the Side Panel component does not change size when closed.

### ISSUE THREAD

**Issue by joeseiden** [Workday/canvas-kit#303]
## 🐛 Bug Report

The ChildrenContainer component derives its size from the openWidth property on the SidePanel component, but unlike its parent and sibling components, ChildrenContainer does not change width when the side panel is closed.

## Expected Behavior

ChildrenContainer should match the width of the side panel when open or closed.

## Actual Results

ChildrenContainer remains full size and causes some overflow issues for its contents when side panel is closed.

**Comment by mannycarrera4** [comment]
@joeseiden thanks for reporting the bug!
