### ISSUE TITLE
Convert Sass @import usage to @use

### ISSUE THREAD

**Issue by anicholls** [Workday/canvas-kit#305]
`@import` has been deprecated (see https://sass-lang.com/documentation/at-rules/import) in favor of the new `@use` rule.

We should eventually adopt the new style. They do provide a [migrator](https://sass-lang.com/documentation/cli/migrator), which may make this pretty easy.

**Comment by stephanerangaya** [comment]
[According to the doc](https://sass-lang.com/documentation/at-rules/use), only Dart Sass currently supports `@use`. Users of other implementations must use the `@import` rule instead. We're using node-sass relying on LibSass, which is not yet supporting `@use`.

**Comment by myvuuu** [comment]
CSS is in maintenance
