### ISSUE TITLE
Some SCSS imports do not use tilde

### ISSUE THREAD

**Issue by vibdev** [Workday/canvas-kit#307]
## 🐛 Bug Report

When importing a scss file, e.g.
`@import '~@workday/canvas-kit-css-form-field/index.scss';`

You get the following import chain:

```
~@workday/canvas-kit-css-form-field/index.scss
~@workday/canvas-kit-css-core/lib/mixins
~@workday/canvas-kit-css-core/lib/variables
@workday/canvas-colors-web/dist/sass/canvas-colors-hex.scss
@workday/canvas-depth-web/dist/sass/canvas-depth.scss
```

These seem to be the only two imports without the tilde and force projects to use two separate methods of import.

## To Reproduce

Run `@import '~@workday/canvas-kit-css-form-field/index.scss';`

## Expected Behavior

All imports are done the same way.

## Actual Results

Two ways are needed

**Comment by anicholls** [comment]
Closed by #308
