### ISSUE TITLE
Remove Preview/Tokens & Upgrade CKR Labs Type Hierarchy

### ISSUE THREAD

**Issue by jessespencer** [Workday/canvas-kit#311]
## 🚀 Feature Proposal

This Issue consists of two parts:

- **Remove preview-react/tokens** 
  - Move Labs Type tokens from preview-react/tokens to tokens
  - Move Labs StaticStates from preview-react/tokens to common
  - Create a codemod to migrate imports
    - run codemod against canvas-kit to update all instances
- **Update the type tokens in react/tokens**
  - update the type hierarchy structure
  - add type properties
  - reduce and simplify variants
  - update `Hyperlink` component to contain deprecate `link` variant styles
  - add codemod to migrate legacy and beta type + variants
  - run codemod against canvas-kit to update all instances
  - Update migration guide and tokens documentation

## Acceptance Criteria

- [ ] update canvas labs type hierarchy
- - [ ] use new type hierarchy
- - [ ] [reduce and simplify type variants](https://github.com/Workday/canvas-kit/discussions/1062)
- [ ] update canvas labs type docs
- [ ] update HyperLink component (as we're removing the link variant)
- [ ] update all other affected components
- [ ] update migration guide

## Note 

Adding Type components will be in a follow-on PR. There's an issue for it [here](https://github.com/Workday/canvas-kit/issues/1072).

**Comment by NicholasBoll** [comment]
Fixed via #1078
