### ISSUE TITLE
Global and Marketing headers icon responsive issue.

### ISSUE THREAD

**Issue by jpante** [Workday/canvas-kit#314]
## 🐛 Bug Report

Items in the header do not respect responsive breakpoints

## To Reproduce

1. Goto the global header story
2. Reduce the view port to ipad or mobile size

## Expected Behavior

Navigation items and system icons disappear when responsive breakpoints are hit

<img width="456" alt="Screen Shot 2019-11-11 at 3 02 45 PM" src="https://user-images.githubusercontent.com/1861673/68628318-152b0300-0495-11ea-960a-abc23df8e0cb.png">

## Actual Results

Navigation items and system icons remain, floating outside of the header boundary 
<img width="430" alt="Screen Shot 2019-11-11 at 3 07 48 PM" src="https://user-images.githubusercontent.com/1861673/68628327-19572080-0495-11ea-9c2d-c9539254b08b.png">

## Link to repl or repo (highly encouraged)

https://workday.github.io/canvas-kit/?path=/story/labs-header-react--global-header

**Comment by vibdev** [comment]
Breakpoints are not internal to the header anymore, there is an isCollapsed prop that needs to be triggered from the caller. It is also available in the knobs tab in storybook.

**Comment by vibdev** [comment]
Maybe the stories should be adjusted to auto set that prop at certain breakpoints?

**Comment by myvuuu** [comment]
Will need to fix this in the examples for Main Header and Page Header

**Comment by alanbsmith** [comment]
Closing as this component has been deprecated.
