### ISSUE TITLE
Add a getting started contribution checklist

### ISSUE THREAD

**Issue by melehamasaki** [Workday/canvas-kit#315]
## 🚀 Feature Proposal

It would be great to add a "getting started" contribution checklist under "CONTRIBUTING.md".

## Motivation

So developers know how to get started.

## Example

A developer wants/needs to contribute a component. They navigate to "CONTRIBUTING.md" and read through the content to see the recommended list of actions items they should do to get started on their contribution (ie. 1. Talk to Alex,  2. Outline proposed props, etc.)

**Comment by alanbsmith** [comment]
Closing this as `Done`. Getting Started Contribution docs live [here](https://workday.github.io/canvas-kit/?path=/story/welcome-contributing--page#getting-started-developing).
