### ISSUE TITLE
Modal: Component is constrained by overflow content

### ISSUE THREAD

**Issue by NicholasBoll** [Workday/canvas-kit#330]
## 🐛 Bug Report

Modal is constrained by overflow content when conflicting stacking contexts are created.

The `Modal` uses `position: fixed` on the containing element which normally takes it out of the flow of the document and ignores overflow constraints (like `overflow: hidden` or `overflow: scroll`). But when combined with certain style properties like `transform`, `perspective` and `filter`, the new stacking context created is constrained by the parent component's overflow container.

The fix would be to use a Portal to take the modal out of the standard layout of the containing element and thus not be restricted by the stacking context of the parent element. This could be a breaking change if `z-index` is used on parent elements. For example if a parent element of a Modal uses `position` and `z-index` outside defaults, the Modal could show behind these elements unless a `z-index` was also passed to the Modal component. It is possible to have a very large `z-index` applied to the Modal container. As long as all Portalled content has the same z-index values, the browser should stack them based on order in the DOM. That would mean all content that uses a Portal would need to have the same z-index value (tooltips and other Popups). Many applications use a Popup Manager to manage z-index values (even though they probably shouldn't - Portals can be used instead).

## To Reproduce

Put the Modal into an overflow constrained container with a `transform` style applied to it. When the Modal is opened, it will be constrained by that overflowed container.

## Expected Behavior

The Modal should not be constrained by the overflowed parent element

## Actual Results

The Modal is constrained by the overflowed parent element

## Browser (if applicable)

This applies to browsers differently. It was found in Chrome. More info here: https://developer.mozilla.org/en-US/docs/Web/CSS/position#fixed

## Link to repl or repo (highly encouraged)

https://codesandbox.io/s/n32vx

### Error Output

![Screen Shot 2019-11-25 at 12 36 43 PM](https://user-images.githubusercontent.com/338257/69571889-41a84a00-0f80-11ea-993b-fcdf1060cbc4.png)

**Comment by anicholls** [comment]
Closed by https://github.com/Workday/canvas-kit/pull/419
