### ISSUE TITLE
@workday/canvas-kit-css-fonts is not in the NPM Registry

### ISSUE THREAD

**Issue by aaronanderson** [Workday/canvas-kit#339]
The [CSS Core](https://github.com/Workday/canvas-kit/blob/master/modules/core/css/README.md#fonts) documentation references `@import '~@workday/canvas-kit-css-fonts/index.scss';` but this module is not in the NPM registry, only `@workday/canvas-kit-react-fonts` is. Will the CSS font module be available in the near future?

**Comment by anicholls** [comment]
@aaronanderson Thanks for reporting! I believe this was an oversight when we moved our internal modules to the public repo. I am opening a PR to address this.

**Comment by aaronanderson** [comment]
Hi @anicholls, unfortunately I don't see the canvas-kit-css-fonts module in the NPM registry [https://www.npmjs.com/search?q=canvas-kit-css-fonts](https://www.npmjs.com/search?q=canvas-kit-css-fonts) Perhaps since it is apart from the main @workday/canvas-kit-css it was not published during the 3.2.0 build and release.
