### ISSUE TITLE
Popper on tooltip appears sporadically

### ISSUE THREAD

**Issue by ginna-baker** [Workday/canvas-kit#349]
## 🐛 Bug Report

The tooltip does not always appear when hovering over the tooltip anchor object (such as the button)

if you move the mouse away toward the tooltip and then back, the tooltip no longer shows.

## To Reproduce

Go to the Canvas Kit storybook
https://workday.github.io/canvas-kit/?path=/story/tooltip--default
Follow instructions above.

## Expected Behavior

The tooltip should always show when hovering over the anchor object (button for eg).

## Actual Results

See issue description.

## Browser (if applicable)

All browsers.

## Link to repl or repo (highly encouraged)

See above

### Error Output

N/A

Include a screenshot of a visual bug
Hovering
![Screen Shot 2019-12-03 at 12 02 35 PM](https://user-images.githubusercontent.com/6732956/70080994-db957580-15c4-11ea-9e61-f459bdf2f977.png)

NOTE:
The issue stems from the Popper library (mouse event handling) and has a known fix.  It is a simple 1-line change.
https://github.com/mui-org/material-ui/issues/7680

**Comment by NicholasBoll** [comment]
Thanks for filing! I can reproduce even on the open source code: https://workday.github.io/canvas-kit/?path=/story/tooltip--default

I'm working on Tooltips right now and we'll no longer be using `@material-ui/core`. I'll close when that PR is posted

**Comment by NicholasBoll** [comment]
Closed by #528
