### ISSUE TITLE
Add Slider Component 

### ISSUE THREAD

**Issue by devonsoto77** [Workday/canvas-kit#354]
## 🚀 Feature Proposal

A slider component, there will be two different variations. One with a direct input and one without. 

## Example

Used to set the height and width for legends within charts. 

## Designs

<img width="534" alt="Screen Shot 2019-12-06 at 11 12 31 AM" src="https://user-images.githubusercontent.com/17392486/70345589-a59cff00-1819-11ea-8674-8a82407490ad.png">

<img width="490" alt="Screen Shot 2019-12-06 at 11 16 06 AM" src="https://user-images.githubusercontent.com/17392486/70345685-d3824380-1819-11ea-83c2-fdf2d5ec7803.png">

**Comment by alanbsmith** [comment]
We closed this PR (#413) a while back but forgot to close the issue.
