### ISSUE TITLE
feat: Add theming support to input components

### ISSUE THREAD

**Issue by anicholls** [Workday/canvas-kit#358]
## 🚀 Feature Proposal

The framework for theming recently got merged (#272). We need to add support for it within our components. As a first step, we should use the theme object color values within every component. We can look at breakpoints as the followup.

## Implementation

Simply extend the `Themeable` interface, and use the `theme` prop provided to our custom `styled` function to style things

```tsx
import {styled, Themeable} from '@workday/canvas-kit-labs-react-core';

export interface MyComponentProps extends Themeable, React.HTMLAttributes<HTMLDivElement> {
  // Props
}

// ...

const Container = styled('div')<MyComponentProps>(
  ({theme}) => ({
    background: theme.palette.primary.main
  })
);

// ...
```

Note: We're going to start with just strong colors (focus outline, blue, red, green, yellow, etc.). We will tackle backgrounds, default borders, etc. in a future update.

## Components
- [x] Checkbox (#456)
- [x] Color Picker (#411)
- [x] Radio (#457)
- [ ] Select (#570)
- [x] Switch (#465)
- [x] TextArea (#459)
- [x] TextInput (#411)

**Comment by anicholls** [comment]
Seems like #416 is required to [remove the docs page for our theming and visual stories](https://github.com/Workday/canvas-kit/pull/411#discussion_r373733032)

**Comment by jpante** [comment]
See  #570 for final themed component
