### ISSUE TITLE
Update outdated depth values

### ISSUE THREAD

**Issue by anicholls** [Workday/canvas-kit#359]
## 🐛 Bug Report

Our depth values in our core modules are using an outdated version of our styles and do not match what is in our Figma libraries. We should update so we are consistent. Let's also double check what's on design.workday.com.

### Considerations

- Where does this go?
  - Labs core module
  - Replace the existing depth styles. I would not consider this a breaking change since it is purely visual, does not cause a reflow, and is simply fixing something out of date. 
- Do we pull this out of `design-assets`? Right now we're simply re-exporting what is autogenerated from that repo. We have discussed moving these styles into CKR anyway - maybe now is the time to do it.

**Comment by anicholls** [comment]
Sounds like there's some work going on to iterate on the latest depth styles. Closing this until that work is done as we don't want to update twice.

**Comment by zorfling** [comment]
@anicholls - what's the latest ETA on this one?

**Comment by anicholls** [comment]
@zorfling Sorry for the delay! I checked in with the design team and it sounds like they're still working on it. Waiting on it coming out in a future update of our Figma library. I will post here when I get an update!
