### ISSUE TITLE
ARIA 1.0 Combobox support

### ISSUE THREAD

**Issue by vibdev** [Workday/canvas-kit#366]
## 🐛 Bug Report

The combobox component supports ARIA spec 1.1 however browsers have not added full support yet.

## To Reproduce

Try to use the combobox component with a screenreader

## Expected Behavior

All roles and aria attributes should be read out

## Actual Results

The role of combobox is not read out.

## Browser (if applicable)

I think issue is still in most browser and screenreader combos, e.g. chrome and voiceover

------

I am proposing to make a new prop that can toggle between the specs. It should default to using v1.0

**Comment by NicholasBoll** [comment]
Thanks @vibdev, I'm looking into the following links for more context:
* https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.0pattern/combobox-autocomplete-list.html
* https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html
* https://www.levelaccess.com/differences-aria-1-0-1-1-changes-rolecombobox/

**Comment by NicholasBoll** [comment]
After some digging, our internal accessibility team knows about this. This proposal came at the request of the accessibility team. Supporting 1.1 but defaulting to 1.0 is to be forward-thinking so that if implementation do catch up to the spec, we can flip a switch. Support for 1.0 isn't meant to be dropped by any assistive technology.

Accessibility also mentioned issues when navigating to the combobox with the arrow keys vs tabbing.

**Comment by anicholls** [comment]
Closed by #380

**Comment by virtualmason** [comment]
Is the Workday Canvas Combo Box / autocomplete currently working? I know it's in beta but does it work for anyone after adding the library? It seems like Chrom does not recognize it?

**Comment by lychyi** [comment]
@virtualmason I'm not sure what you mean by this. Can you open an issue with the appropriate details so we can take a look? Combobox is in our "Labs" state but it doesn't mean it should ship broken.

**Comment by virtualmason** [comment]
If you look at the docs it mentions ComboBox with no way to use it. I
assume to get the ComboBox I'm to "import {ComboBox} from ''
@workday/canvas-kit-labs-react-combo-box' so I can use Combobox but the
browser does not recognize it. I also tried doing it just like in the read
me below without importing "ComboBox" only npm installing the library. Is
there some missing information for it to work that is not mentioned below,
on the npm page or workday labs page
https://github.com/Workday/canvas-kit/tree/master/modules/_labs/combobox/react
?

import {SearchBar} from '@workday/canvas-kit-labs-react-header';
import {MenuItem} from '@workday/canvas-kit-labs-react-menu';
import {TextInput} from '@workday/canvas-kit-labs-react-text-input';
import {FormField} from '@workday/canvas-kit-labs-react-form-field';

const autocompleteCallback = event => console.log('Adjust menu items here')


<FormField id='id-123' label='Example'>
  <Combobox
    autocompleteItems={[<MenuItem>Item 1</MenuItem>]}
    onChange={autocompleteCallback}
    onFocus={action(`Focus`)}
    onBlur={action(`Blur`)}
  />
    <TextInput placeholder="Autocomplete" autoFocus={true} />
  </Combobox>
</FormField>

**Comment by NicholasBoll** [comment]
It does look like the link in the readme is incorrect. The path is https://github.com/Workday/canvas-kit/blob/master/modules/_labs/combobox/react/stories/stories.tsx

The link to the Combobox in docs is: https://workday.github.io/canvas-kit/?path=/story/labs-combobox-react--autocomplete

**Comment by NicholasBoll** [comment]
I've created a pull request for #455 to fix the broken stories link. I've also simplified the Readme example.

Please open a new Github issue with the problem you are facing including steps to reproduce, etc. We have an issue reproduction here: https://codesandbox.io/s/canvas-kit-issue-reproduction-i9b54

Here's a working example: https://codesandbox.io/s/polished-frost-ti9c7
