### ISSUE TITLE
Modal handleClose prop is being used to determine multiple things

### ISSUE THREAD

**Issue by Keysox** [Workday/canvas-kit#398]
## 🐛 Bug Report

https://workday.github.io/canvas-kit/?path=/story/components-popups-modal-react--without-close-icon shows an example of a modal without the `X` icon in the top right but the documentation doesn't clearly state how it's intended to be configured that way. Passing `handleClose={undefined}` seems to do the trick but then setting `closeOnEscape={true}` no longer works.

## Expected Behavior

I expected the modal to have a boolean prop such as `showCloseIcon` to help with discoverability.

**Comment by NicholasBoll** [comment]
This is fixed in v5
