### ISSUE TITLE
Upgrade to Chromatic 2.0 Early Access

### ISSUE THREAD

**Issue by NicholasBoll** [Workday/canvas-kit#400]
## 🚀 Feature Proposal

Upgrade to Chromatic 2.0 Early Access. Version 2 adds a much richer review process to visual diffs. Without it, we just have a simple Approve/Deny button, but nothing about _why_ something was approved or denied.

Upgrading requires a new key (early access key) and will require all active PRs to be re-reviewed if any changes were already accepted.

## Motivation

Better visual reviews.

**Comment by lychyi** [comment]
Closed via #405
