### ISSUE TITLE
canvas-kit-css-icon depends on @workday/canvas-kit-react-common

### ISSUE THREAD

**Issue by aaronanderson** [Workday/canvas-kit#408]
## 💬 Questions and Help
I noticed that [canvas-kit-css-icon.js](https://github.com/Workday/canvas-kit/blob/master/modules/icon/css/lib/canvas-kit-css-icon.js) has an import for a react module: `import {pickForegroundColor} from '@workday/canvas-kit-react-common';` 

I needed to add this React dependency to my project in order to load the icon module. This wasn't documented and seems out of place for a CSS only project but maybe it is intentional.

**Comment by lychyi** [comment]
@aaronanderson this is a bug and that function (as strange as it is to include something from our 'react' lib) should be in the dependencies section it looks like.

Thanks for catching that.
