### ISSUE TITLE
Modal is not fully accessible

### ISSUE THREAD

**Issue by NicholasBoll** [Workday/canvas-kit#414]
## 🐛 Bug Report

The modal component traps keyboard focus and hides content behind an overlay, but does not hide contents for assistive technologies. To hide contents for assistive technology, `aria-hidden` must be added to content that is not part of the modal. This will prevent users from accessing content outside the modal.

This work is related to #330 

## To Reproduce

Using VoiceOver in MacOS:
* Navigate to https://workday.github.io/canvas-kit/iframe.html?id=components-popups-modal-react--default
* Open the Modal
* Enable VoiceOver
* Open Web Rotor (default keyboard shortcut is Control+Option+U)
* Hit the right key until "Form Controls" is active

## Expected Behavior

"Delete Item" or "Delete Item button" should not appear on the list of controls (depending on VoiceOver verbosity)

## Actual Results

"Delete Item button" appears on the list of controls

## Browser (if applicable)

Doesn't matter

## Link to repl or repo (highly encouraged)

<img width="1130" alt="Screen Shot showing 'Delete Item Button' in the list of form controls" src="https://user-images.githubusercontent.com/338257/72829518-2b470380-3c3c-11ea-8db5-767be24e7dfd.png">

Additional internal info:
https://jira2.workday.com/browse/CANVAS-541

**Comment by anicholls** [comment]
Closed by https://github.com/Workday/canvas-kit/pull/419
