### ISSUE TITLE
canvas-kit-css-fonts has not been published to the NPM registry

### ISSUE THREAD

**Issue by aaronanderson** [Workday/canvas-kit#426]
## 🐛 Bug Report
Issue [339](https://github.com/Workday/canvas-kit/issues/339) has been resolved and the canvas-kit-css-fonts module source is available but it has not been published into the NPM registry along with the other 3.2.0 packages. Perhaps it was inadvertently excluded from the NPM publish process?

https://www.npmjs.com/search?q=canvas-kit-css-fonts

**Comment by anicholls** [comment]
This is now available @aaronanderson! https://www.npmjs.com/package/@workday/canvas-kit-css-fonts

Sorry for the delay. It was published, but set to private in npmjs. Thanks for helping us catch it.
