### ISSUE TITLE
Header search form not filling to width 

### ISSUE THREAD

**Issue by laurenraddatz** [Workday/canvas-kit#476]
## 🐛 Bug Report

_I added a red border to fully illustrate the issue_. 
![Screen Shot 2020-02-19 at 11 49 06 AM](https://user-images.githubusercontent.com/10822998/74865227-0e225500-530e-11ea-904b-854f4539db8c.png)
![Screen Shot 2020-02-19 at 11 49 18 AM](https://user-images.githubusercontent.com/10822998/74865231-0fec1880-530e-11ea-92a7-50a3aeefc17e.png)
The search bar does not properly fill its width. As a result it cannot be properly styled when imported, and it cannot be properly centered in a container without having to add margins to adjust for the "gap."

## To Reproduce

Inspect the search form, try to add styles to it, notice the width problem

## Expected Behavior

I expect the search form to the fill the width it's expected to be.

## Actual Results

The search form does not fill the width.

## Browser (if applicable)

Chrome, macos

**Comment by lychyi** [comment]
Would you mind opening a PR for this?

**Comment by JustAboutJeff** [comment]
:wave: I'm going to see if I can take a pass at this issue. PR referenced above ☝️
