### ISSUE TITLE
Checkbox onChange should match the `HTMLInputElement` interface it extends from

### ISSUE THREAD

**Issue by NicholasBoll** [Workday/canvas-kit#496]
## 🐛 Bug Report

Checkbox `onChange` is defined as a SyntheticEvent rather than a ChangeEventHandler like the extended interface. This causes problems downstream when an handler is typed as `React.ChangeEventHandler<HTMLInputElement>` (since that's the base shape).

https://github.com/Workday/canvas-kit/blob/1d4e3d4ffc27d7743c4bfb33b67e3d7fba473758/modules/checkbox/react/lib/Checkbox.tsx#L47

Comes from this comment: https://github.com/Workday/canvas-kit/issues/487#issuecomment-594923058

We could either remove that line or change the signature to match the base signature (benefit of that is to add our own JSDoc info and have the `onChange` property show up in our docs)

**Comment by anicholls** [comment]
@NicholasBoll This is a problem in more than Checkbox. We use this signature for the majority of our input elements. It should probably be updated everywhere

**Comment by ziel5122** [comment]
> ## 🐛 Bug Report
> Checkbox `onChange` is defined as a SyntheticEvent rather than a ChangeEventHandler like the extended interface. This causes problems downstream when an handler is typed as `React.ChangeEventHandler<HTMLInputElement>` (since that's the base shape).
> 
> https://github.com/Workday/canvas-kit/blob/1d4e3d4ffc27d7743c4bfb33b67e3d7fba473758/modules/checkbox/react/lib/Checkbox.tsx#L47
> 
> Comes from this comment: [#487 (comment)](https://github.com/Workday/canvas-kit/issues/487#issuecomment-594923058)
> 
> We could either remove that line or change the signature to match the base signature (benefit of that is to add our own JSDoc info and have the `onChange` property show up in our docs)

It won't show up in docs if you extend?

**Comment by NicholasBoll** [comment]
This line excludes a prop that originates from a `node_modules` folder: https://github.com/Workday/canvas-kit/blob/master/.storybook/docgen-plugin.js#L9

Without this line, there would be a lot of props. Every prop and attribute supported by a DOM element.

**Comment by NicholasBoll** [comment]
> @NicholasBoll This is a problem in more than Checkbox. We use this signature for the majority of our input components. It should probably be updated everywhere

This might be a breaking change for those using Typescript with a workaround to this feature. We'd have to verify.

**Comment by anicholls** [comment]
Closed by #499
