### ISSUE TITLE
Checkbox does not truncate long labels

### ISSUE THREAD

**Issue by ofalsap** [Workday/canvas-kit#508]
## 🐛 Bug Report
The label in the Checkbox component does not truncate long text when it is used inside a div with a specified width. The label is a prop of the Checkbox component. The Checkbox component may benefit to have an optional width props. I am happy to work on a fix for this if you think my suggestion is feasible.

## To Reproduce

Try to have a long text label in the Checkbox component used in a div.

## Expected Behavior
If the width prop has been set up :  the long label of the Checkbox component will truncate .

If the width prop has NOT been set up: the long label of the Checkbox component will over flow.

## Actual Results

The label in the Checkbox component does not truncate long text when in a div with specific width.

### Error Output
<img width="247" alt="Screenshot 2020-03-12 at 10 45 17" src="https://user-images.githubusercontent.com/62067641/76513703-9946c480-644e-11ea-892e-8cea9b7dc26a.png">

**Comment by NicholasBoll** [comment]
This is what I see: 
<img width="296" alt="image" src="https://user-images.githubusercontent.com/338257/150229634-5c5e0c4d-5001-45df-93d1-0c310e3ef106.png">

Codesandbox link: https://codesandbox.io/s/sad-dawn-i6whr

Does your application override the wrapping of the checkbox?

**Comment by jaclynjessup** [comment]
Can't reproduce & inactive issue.
