### ISSUE TITLE
Toggle Button Focus Outline Disappears on click (744)

### ISSUE THREAD

**Issue by jpante** [Workday/canvas-kit#534]
## 🐛 Bug Report

In Safari and Firefox, Focus outline disappears when a toggle button is clicked.

Applies to all toggle buttons including those in a segmented control

## To Reproduce

1. Open Firefox or Safari
2. Browse to https://workday.github.io/canvas-kit/?path=/story/components-buttons-button-react-icon-button--toggleable
3. Click a button within a toggle 

## Expected Behavior

Toggle button switches to selected, and focus outline is maintained

## Actual Results

Toggle button is selected, focus outline disappears

## Browser (if applicable)

Safari & Firefox

![focusoutlinedisapears](https://user-images.githubusercontent.com/1861673/77570550-3828e300-6e89-11ea-8738-f0483e0295f6.gif)

**Comment by anicholls** [comment]
@jpante This flash is fixed in #505, and the focus outline isn't expected to be visible at all here until you keyboard navigate because it's using [`InputProvider`](https://github.com/Workday/canvas-kit/tree/master/modules/core/react#input-provider).

Are you alright with closing?

**Comment by jpante** [comment]
Duplicate, resolved in 4.x release.
