### ISSUE TITLE
Add Pill Component

### ISSUE THREAD

**Issue by jpante** [Workday/canvas-kit#538]
## 🚀 Feature Proposal

Add the pill component and pillscontainer to Canvas Kit React. Migration from WDC (but using Canvas's design).

## Design Specifications

![pills](https://user-images.githubusercontent.com/1861673/78062961-491f9b80-7344-11ea-84bd-1b79a17b6805.png)

Designer - Dan N.

**Comment by alanbsmith** [comment]
Moving this back to `To-do` until we clarify more details about what needs to be supported.

**Comment by jaclynjessup** [comment]
PR has been merged - Closing
