### ISSUE TITLE
Update Sour Lemon Hex Values

### ISSUE THREAD

**Issue by jpante** [Workday/canvas-kit#539]
## 🚀 Feature Proposal

Update Sour Lemon within Canvas Kit to use the new hex values.

## Motivation

Sour Lemon, part of the core Workday color palette, has been updated by brand.

## Details

`Sour Lemon 400` from `#F7C72A` to `#FFC629`

**Comment by jpante** [comment]
New version available for canvas-colors-web with new sour lemon token available.

**Comment by anicholls** [comment]
Closed by #706
