### ISSUE TITLE
Setting TableRow's state={TableRowState.Hover} does not change style

### ISSUE THREAD

**Issue by bali182** [Workday/canvas-kit#549]
## 🐛 Bug Report

Rendering a TableRow with hover state, eg.:
```
<TableRow state={TableRowState.Hover}>...</TableRow>
```
Does not make the row look like when mousing over.

**The reason I do this**: I'm syncing 2 views, one's a tree structure, ones a table structure, they represent the same data. I got a requirement to highlight the appropriate table item when hovering over the corresponding tree item. This is the reason I'm trying to use `TableRowState.Hover`.

## To Reproduce

As described above

## Expected Behavior

The table row should look the same as when mousing over

## Actual Results

It looks like a default table row (eg.: `state={null}`)

## Browser (if applicable)

All

## Link to repl or repo (highly encouraged)

Can't publicly post, ping me if needed please.

### Error Output

Can't publicly post, ping me please if needed.

**Comment by alanbsmith** [comment]
Confirmed that this does not apply hover styles to the row as expected. Here's where that code lives: https://github.com/Workday/canvas-kit/blob/master/modules/react/table/lib/TableRow.tsx#L151-L193

**Comment by jaclynjessup** [comment]
A new table component is being developed #2058 This will be the recommend table component to use, therefore closing this issue.
