### ISSUE TITLE
Support flexible side panel layouts

### ISSUE THREAD

**Issue by anicholls** [Workday/canvas-kit#55]
## 🚀 Feature Proposal

Right now `SidePanel` opens and closes on top of content. It would be nice to have a layout component that could re-flow the content around the side panel when it opens. I think it makes sense to use the existing `Layout` component for this. 

`Layout.LeftPanel` and `Layout.RightPanel` would render a `SidePanel`, passing any event listeners necessary for `Layout` to manage the state. Maybe the existing `Layout` component becomes `Layout.Grid`?

Note: for performance reasons, we should also look at doing these transitions with translation rather than animating the width of `SidePanel`

## Example
```jsx
<Layout /* Add a prop to animate width vs. post translate */>
  <Layout.LeftPanel open={true} sidePanelBackgroundColor={SidePanelBackgroundColor.Gray}>
    <ul>
      <li>Link</li>
    </ul>
  </Layout.LeftPanel>
  <Layout.Grid>
    <Layout.Column>
      <Card heading="Column 1" />
    </Layout.Column>
    <Layout.Column>
      <Card heading="Column 2" />
    </Layout.Column>
  </Layout.Grid>
  <Layout.RightPanel open={true} sidePanelBackgroundColor={SidePanelBackgroundColor.Gray}>
    <ul>
      <li>Link</li>
    </ul>
  </Layout.RightPanel>
</Layout>
```

**Comment by drschulz** [comment]
One interesting consideration for this as well would be responsiveness. How would side panels look on mobile devices? Currently for us, they actually end up paneling over the main content and taking up the entire screen width. For the case where the panel is collapsed but still visible, we hide it in mobile completely and just have a floating toggle button. Do you think this is something canvas would handle or would it be up to consumers to handle how content is laid out on different devices?

**Comment by anicholls** [comment]
Hmm that's a good point @drschulz. In that case it's not necessarily a "best practice" single option. Some people may prefer to push content, go overtop fully, go overtop with a little bit of the content visible, or go overtop with an overlay behind the panel (over the content). When you factor in how it's toggled, there are a lot of variables. Will have to think about this one a bit more.

**Comment by NicholasBoll** [comment]
I personally think canvas should handle. In general, the more canvas does, the more consistent applications and application development become. But we have to be careful about what edge cases we take on. Too many configurations and we end up with a huge prop list. I think this proposal is a nice compromise for how to compose components together.

**Comment by willklein** [comment]
We can close this, the newer `SidePanel` in Preview shows how this is possible: https://workday.github.io/canvas-kit/?path=/story/preview-side-panel-react--basic
