### ISSUE TITLE
Canvas Kit CSS Checkbox wdc-form-checkbox class should have position: relative set

### ISSUE THREAD

**Issue by aaronanderson** [Workday/canvas-kit#559]
## 🐛 Bug Report
CSS checkboxes in a container with overflow: auto are not checking correctly. I believe this has to due with the position: absolute on the included in the css for the input and ::before selectors. In my case I included a checkbox on each row of an HTML table and clicking on checkboxes outside of the initial scrollbar viewport caused the checkboxes that were originally placed at the position I was clicking to be toggled, not the checkbox I was actually clicking.

Adding 

```.wdc-form-checkbox {
	position: relative;	
}
```
To my CSS seemed to fix my issue locally but didn't have an affect the JSFiddle reproducer I created.

## To Reproduce

Include a CSS checkbox in a container configured with overflow: auto with enough content to activate the scrollbars. Clicking on a checkbox outside of the initial viewport doesn't work or checks the incorrect checkbox.

## Expected Behavior

The checkbox that is clicked on is toggled.

## Actual Results
The first checkbox or checkboxes that were originally located at the mouse click event are checked, not the targeted checkbox.

## Browser (if applicable)
Chrome 81.0.4044.92

## Link to repl or repo (highly encouraged)

https://jsfiddle.net/326yqhsk/

**Comment by mannycarrera4** [comment]
hey @aaronanderson !

I was able to take a closer look at the issue and the jsfiddle you provided. At least in the example that was provided, the first thing that stuck out to me is that when you render the checkbox and label, they both have the same `id` and `for` therefore every single checkbox has those same attributes and the toggling of the checkbox is all off and it really just recognizes the first checkbox when you click on it.

Although putting position relative on the `::before` seemed to work, it looks like a false positive. You're no longer clicking on the right label for that checkbox.

A solution to this would be to add a unique `id` and matching `for` for every single checkbox. For a solution to the problem, i took your jsfiddle and edited it https://jsfiddle.net/g6wr7xnu/1/

**Comment by mannycarrera4** [comment]
Closing issue with link to jsfiddle with the solution above!
