### ISSUE TITLE
Modal has 1px gray card border

### ISSUE THREAD

**Issue by anicholls** [Workday/canvas-kit#56]
## 🐛 Bug Report

Modals are placed on a dark background, but have a gray border from the nested `Card` 
component. `Modal` renders a `Popup`, which then renders the `Card`. This gray border makes the edge look blurry. This could potentially be an issue when placing cards on any dark or colored background (i.e. the design.workday.com).

![Screen Shot 2019-07-31 at 4 11 35 PM](https://user-images.githubusercontent.com/908478/62254422-e8ebea80-b3ad-11e9-9785-c2d585d487f0.png)

## Expected Behavior

While we want the gray border on Cards and Popups, there should be no border on Modals.

**Comment by NicholasBoll** [comment]
This is fixed in v5
