### ISSUE TITLE
Don't publish canary builds for release PR merges

### ISSUE THREAD

**Issue by anicholls** [Workday/canvas-kit#567]
## 🐛 Bug Report

We're currently publishing canary builds for when release PRs are merged (triggering another build). Not only is this duplication and a waste of resources, it's also quite confusing.

Examples:
- `3.6.0` and `3.5.1-next.10` share the same code
- `4.0.0-beta.1` and `4.0.0-prerelease.7` share the same code

Our `trunk` deploy script should only run if the branch being merged is not a release branch. There isn't a super obvious way for the CI to tell the difference between a release PR and a regular one (since the tag is applied after merge). My first thought is that we should prevent this script from running if the branch starts with the word `release`. Anyone have any other ideas?

**Comment by anicholls** [comment]
@NicholasBoll Could you maybe account for this in #557?

**Comment by NicholasBoll** [comment]
> @NicholasBoll Could you maybe account for this in #557?

I think #557 should be kept as a pull request-only PR. We can make another PR to deprecate TravisCI for `trunk` and `tag` stages.

**Comment by NicholasBoll** [comment]
This is fixed since we moved to Github Actions and the Canary job only runs on `prerelease/*`
