### ISSUE TITLE
Increase Release Automation

### ISSUE THREAD

**Issue by jpante** [Workday/canvas-kit#568]
Look at current release process and add automation to steps that should be.

**Steps to consider.**

- [x]  Change log generator
- [x] Update change log file and manually categorize different PRs
- [x] Bump all versions (and specify)
- [x] Open PR
- [x] Merge PR , Checkout PR and tag it
- [x] Create a GH Release

**Other Considerations**
- Github contributor change log generator gives kudos to last commit contributor, not author..

**Comment by NicholasBoll** [comment]
Done
