### ISSUE TITLE
React: Toast should allow for styling markup

### ISSUE THREAD

**Issue by anicholls** [Workday/canvas-kit#57]
## 🐛 Bug Report

We only accept a string in the toast, but this means no text can be bold, italic, etc. Ideally we would support this kind of styling. 

https://github.com/Workday/canvas-kit/blob/master/modules/toast/react/lib/Toast.tsx#L14

## Potential solutions:
- Allow `ReactNode` as a child. Unfortunately changing this to allow any node allows people to put block level elements inside of toast which we would prefer to avoid. 
- Accept a string of markdown for the contents?

**Comment by alanbsmith** [comment]
This was fixed with #1309.
