### ISSUE TITLE
Implement ref forwarding on Icon components

### ISSUE THREAD

**Issue by laurenraddatz** [Workday/canvas-kit#574]
## 🚀 Feature Proposal
I am requesting to add an `iconRef` prop on the icon components, and forwarding it to the ref prop on the icon components.
## Motivation

this is already enabled in the button components, such as `IconButton`. In our use case, we have refs with _interesting_ types, such as ones that are callbacks.

## Example

reference the `IconButton` component.

let me know what you think and I can make a PR!

**Comment by mannycarrera4** [comment]
I think we want to do this for most of our components! For reference: https://github.com/Workday/canvas-kit/issues/548
