### ISSUE TITLE
canvas-kit-react-color-picker needs to re-export ColorSwatch

### ISSUE THREAD

**Issue by BlueVajra** [Workday/canvas-kit#575]
## 🐛 Bug Report

When importing `ColorPicker` from `@workday/canvas-kit-labs-react-color-picker`, the dist folder does not have the ColorSwatch component properly available.

## Reason for error

https://github.com/Workday/canvas-kit/blob/master/modules/_labs/color-picker/react/lib/parts/ColorReset.tsx#L7

If I am understanding correctly, we need to export ColorSwatch directly from canvas-kit-react-color-picker and import it like this:
`import {ColorSwatch} from '@workday/canvas-kit-react-color-picker';`

### Error Output

Paste the error output here

```bash
ERROR in ./node_modules/@workday/canvas-kit-react-color-picker/lib/parts/ColorSwatch.tsx 9:7
Module parse failed: Unexpected token (9:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import {SystemIcon} from '@workday/canvas-kit-react-icon';
|
> export interface ColorSwatchProps extends React.HTMLAttributes<HTMLDivElement> {
```

Let me know if you would like me to tackle this.

**Comment by anicholls** [comment]
@BlueVajra Thanks for catching this!

Exporting the swatch and importing as you've noted should fix it. If you could open a PR, that would be awesome! 👏  Thanks in advance
