### ISSUE TITLE
Update selected option to display a checkmark

### ISSUE THREAD

**Issue by jamesfan** [Workday/canvas-kit#607]
## 🚀 Feature Proposal

Currently, the Select (with the Canvas-styled menu) uses a background-color to style the selected option.

The Design spec for Select is being updated to use a checkmark icon to designate the selected option rather than a background-color (final spec pending). The component will need to be updated to match the new spec.

**Comment by myvuuu** [comment]
Not having a checkmark is not an a11y issue, closing out
