### ISSUE TITLE
React: Re-export everything from core module in universal module

### ISSUE THREAD

**Issue by anicholls** [Workday/canvas-kit#61]
## 🐛 Bug Report

`canvas-kit-react` only exports `canvas-kit-react-core`'s `canvas` namespace so we don't provide access to objects not contained in `canvas`. For example, `canvas-kit-react-core` is exporting `spacingNumbers` generally, but not under the `canvas` namespace.

## To Reproduce

```jsx
import {canvas} from '@workday/canvas-kit-react';

canvas.spacingNumbers; // undefined
```

or 

```jsx
import {spacingNumbers} from '@workday/canvas-kit-react'; // import error
```

## Expected Behavior

`spacingNumbers` should be available from `canvas-kit-react` universal module.

We don't want to export all types/enums on `canvas`, so I think we should re-export everything from the core module in the universal one since that's what we do for all other modules.

**Comment by myvuuu** [comment]
No longer relevant
