### ISSUE TITLE
Update to commitlint

### ISSUE THREAD

**Issue by anicholls** [Workday/canvas-kit#62]
## 🚀 Feature Proposal

Move from `validate-commit-msg` to `commitlint`

## Motivation

`validate-commit-msg` has been deprecated in favor of `commitlint`: https://www.npmjs.com/package/validate-commit-msg. It's working fine as is though, so this is a low priority

**Comment by Patil2099** [comment]
@anicholls  Can I work on this?

**Comment by NicholasBoll** [comment]
> @anicholls Can I work on this?

Definitely!
