### ISSUE TITLE
Add VisuallyHidden component

### ISSUE THREAD

**Issue by alanbsmith** [Workday/canvas-kit#621]
## 🚀 Feature Proposal

An element that provides content to assistive technology, but is hidden from the UI.

## Motivation

I found a use case for this when working on Badge, and I think there are probably other components that could use it as well.

## Example

```jsx
      <VisuallyHidden role="status" aria-live="polite" aria-atomic="true">
        New notifications
      </VisuallyHidden>
```

**Comment by alanbsmith** [comment]
Here's sort of what I had in mind:

```jsx
const VisuallyHidden = styled('div')({
  position: 'absolute',
  top: 0,
  clip: 'rect(1px, 1px, 1px, 1px)',
  overflow: 'hidden',
  height: '1px',
  width: '1px',
  padding: 0,
  border: 0,
})
```

This is based on [Polaris' component](https://polaris.shopify.com/components/titles-and-text/visually-hidden). There's not much to the component. Here's the JS, and this is the [styling](https://github.com/Shopify/polaris-react/blob/97da8aa3716f508ae51edd96dd2e52ddfe4a7660/src/styles/shared/_accessibility.scss).

It also seems like a shared mixin we could add as a variant for different components. e.g:

```jsx
<Label variant="hidden">Hidden label</Label>
```

**Comment by alanbsmith** [comment]
Here's the ReachUI example:

* [TSX](https://github.com/reach/reach-ui/blob/master/packages/visually-hidden/src/index.tsx)
* [Docs](https://reacttraining.com/reach-ui/visually-hidden/)

**Comment by anicholls** [comment]
We already have an [`accessibleHide`](https://github.com/Workday/canvas-kit/blob/master/modules/common/react/lib/styles/accessibleHide.ts) style object, but it probably wouldn't hurt having a component for this?

**Comment by alanbsmith** [comment]
@anicholls, 

Yeah, that's great! I think a component would be helpful too, though. Here's an [example](https://codesandbox.io/s/notificationbadge-example-hh5dn).

**Comment by mathalete** [comment]
Note the accessibleHide is the better CSS technique as it includes `white-space:nowrap;`. For reference see https://medium.com/@jessebeach/beware-smushed-off-screen-accessible-text-5952a4c2cbfe

**Comment by alanbsmith** [comment]
Closing as we already have `accessibleHide`.
