### ISSUE TITLE
Update lint-staged to v8

### ISSUE THREAD

**Issue by anicholls** [Workday/canvas-kit#63]
## 🐛 Bug Report

When trying to commit partially staged files, our linting adds the entire file during `precommit` without saying anything. I often accidentally commit lines I purposefully excluded because of this and end up with messy commits (or I have to re-write my local history).

## To Reproduce

- Make some changes to a file
- Run `git add -p`
- Select some lines and not others
- Run `git commit`

## Expected Behavior

My commit should only contain the changes I've staged.

## Actual Results

Your commit will include the lines you excluded

## Solution

We are currently on `lint-staged` v7.1. Support was added for partially staged files in v8.0: https://hackernoon.com/announcing-lint-staged-with-support-for-partially-staged-files-abc24a40d3ff

**Comment by Patil2099** [comment]
Can I work on this ?

**Comment by anicholls** [comment]
@Patil2099 By all means, please give it a go! Thanks 🙂
