### ISSUE TITLE
Using Menu with Popper causes a page scroll when popper is attached to document.body

### ISSUE THREAD

**Issue by divyanshu023** [Workday/canvas-kit#632]
## 🐛 Bug Report

The Popper component portals content to document.body when containerElement is undefined.

When the children is a component like Menu, which sets the focus on a menu item, the browser scrolls to the portal content.

This is probably a timing issue. Popper JS should update the position after the menu is focused.

## To Reproduce

```tsx
	<Popper
		ref={popperRef}
		placement={'left-start'}
		open={isOpen}
		anchorElement={buttonRef.current}
	>
		<Menu
			isOpen={isOpen}
		>
			<MenuItem>
				1
			</MenuItem>
		</Menu>
	</Popper>
```
## Expected Behavior

Popper Js should position the portal correctly so the page doesn't jump.

## Actual Results

The browser jumps to the newly added portal/content. This causes page to scroll.

## Browser (if applicable)

Chrome V80.x

**Comment by jpante** [comment]
To be verified if this is still an issue in CK 4.0

**Comment by mannycarrera4** [comment]
I think this is happening because the `MenuItem` has a `minWidth` set but never a `width: 100%` should be an easy fix, will verify.

**Comment by NicholasBoll** [comment]
From my testing it looks like the browser scrolls to the top of the page. I think this is because the focus happens _before_ PopperJS positions. We need to delay focus by a bit.

**Comment by NicholasBoll** [comment]
Fixed via https://github.com/Workday/canvas-kit/commit/dd74d1e43bdc61ce89df9885c88c4c3ea80eb0ae
