### ISSUE TITLE
chore: Remove Canvas Kit dev dependencies

### ISSUE THREAD

**Issue by anicholls** [Workday/canvas-kit#645]
## 🚀 Feature Proposal

Since we're using a yarn workspace, we do not need to track dev dependencies within the monorepo (i.e. dev dependencies on CK components). This is an extra vector for versioning errors/mismatches (see #644), so it would be good to avoid.

We should remove all of the CK dev deps (currently in):
- labs/menu
- common
- form-field
- icon
- page-header
- popup
- status-indicator
- toast
- tooltip

As is, our `check-dependencies-exist` script will complain if these deps aren't there (because they are referenced in stories and tests). Unfortunately [`depcheck`](https://github.com/depcheck/depcheck) only splits _unused_ dependencies into regular and dev, but it does not split _missing_ dependencies like this. This means we'll likely have to skip checking dependencies on stories (and maybe tests) all together. Alternatively, we could use relative imports for all of these deps.

Additionally, we should probably be enforcing that there are no CK dev deps in the package.json files. Open to ideas on how to accomplish this.

**Comment by NicholasBoll** [comment]
Closed by #992
