### ISSUE TITLE
Consolidate breakpoints

### ISSUE THREAD

**Issue by anicholls** [Workday/canvas-kit#65]
## 🚀 Feature Proposal

Consolidate breakpoints across the React and CSS kits and put them in the respective core modules as constants.

## Motivation

We have some inconsistent breakpoints that we should align on. Also it would be nice to have constants for breakpoints for consumers to depend on. This would make projects implemented with the Canvas Kits more consistent across the board.

This could also potentially be combined with the [`makeMq` helper](https://github.com/Workday/canvas-kit/blob/master/modules/common/react/lib/utils/makeMq.ts) for the React kit.

**Comment by myvuuu** [comment]
Duplicate for #1192
