### ISSUE TITLE
Switch Component requires two clicks to change checked state.

### ISSUE THREAD

**Issue by aaroncalderon** [Workday/canvas-kit#657]
## 🐛 Bug Report

When implementing the Switch component, it requires two clicks to change the checked state/value.

## To Reproduce

See CodeSandbox.io [Use Case: Workday Canvas-kit Switch](https://codesandbox.io/s/use-case-workday-canvas-kit-switch-0np5l), click on the switch component until it changes state several times from false to true and from true to false.

## Expected Behavior

As per your documentation only one click is required to change state.

## Actual Results

The component must be clicked twice to change checked state.

## Browser (if applicable)

Chrome

## Link to repl or repo (highly encouraged)

CodeSandbox.io [Use Case: Workday Canvas-kit Switch](https://codesandbox.io/s/use-case-workday-canvas-kit-switch-0np5l)

### Error Output

n/a

**Comment by mannycarrera4** [comment]
@aaroncalderon thanks for submitting an issue!

In the sandbox you've provided a noticed a couple things:
1) The click target  seems to be off which was preventing clicking on the whole switch:
<img width="917" alt="Screen Shot 2020-05-21 at 2 49 15 PM" src="https://user-images.githubusercontent.com/7966550/82609930-bac4da80-9b7a-11ea-8c97-db44195caad4.png">

We have a fix in the works for this here: https://github.com/Workday/canvas-kit/pull/669

2) By adding `event.preventDefault()` to your handleChange function, this was breaking the event listener because it's not a `cancelable` event and therefore stopping the natural behavior of an on change event. 

The PR should fix the click target and removing `event.preventDefault()` should do the trick!

**Comment by aaroncalderon** [comment]
@mannycarrera4 thanks so much for pointing this out.

I put together these CodeSandbox samples based off other react sample codes for `this.handleChange` functions.

Looks like on the canvas-kit documentation the `this.handleCheck` is the function name of choice. But, I have not been able to see any code sample for this.

Now the question is...

So, when a form contains additional code-kit components, like radio or select, and all components use the same onChange function, only the switch component (so far) displays this odd behavior when we have an `event.preventDefault();` in there. 

I believe that the `event.preventDefault();` is there to handle buttons, and prevent form submission.

- Does this mean that we must handle switch components differently?
- Is there a best practice regarding this?

I have a sample use case [Canvas-Kit Multiple Components on One Form](https://codesandbox.io/s/use-case-workday-canvas-kit-select-lilsz). Please note that I added a Form tag, and I am handling the onChange event with different functions for the Select and Switch components.

Thanks in advance for all your time.

**Comment by NicholasBoll** [comment]
I'm not sure where the `preventDefault` is coming from. It should be avoided unless you know what default actions are and why you need to prevent them. If you have a `button` element, you need to make it a `type="button"` if you wish to not have it submit a form. "submit" is the default type for buttons:

> If your buttons are not for submitting form data to a server, be sure to set their type attribute to button. Otherwise they will try to submit form data and to load the (nonexistent) response, possibly destroying the current state of the document.

From https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Notes

This is not a Canvas Kit issue, using a raw checkbox with an `event.preventDefault()` will cause problems: https://codesandbox.io/s/checkbox-eventpreventdefault-3qvld

Best practice is to _not_ use `event.preventDefault()` unless you know why you are using it.

**Comment by aaroncalderon** [comment]
@NicholasBoll Got it. Thanks so much for providing the reference links and the sample code.
