### ISSUE TITLE
ci: Improve prerelease versioning logic

### ISSUE THREAD

**Issue by anicholls** [Workday/canvas-kit#661]
Our existing structure for canary versioning has been hard/confusing to debug/reason about lately. We’ve been hacking around Lerna’s `canary` solution, and I think it’s time to drop that entirely and calculate our own versions because it’s not working. I would like to propose a few changes/improvements:

- Consider dropping Lerna `--canary` usage and calculate the version for canary builds ourselves (we've had lots of issues around the lack of configurability here - see https://github.com/lerna/lerna/issues/1893 for an example)
- Change the prerelease dist-tags to follow the same style as master
- Don't do canary builds for release merge commits
- Delete `canary` preids accidentally created in #619 
- Unrelated, but while we're at it can we add `--force-publish="*"` for release/tag builds?

## Canary versions

To customize the version at all when using `lerna publish`, the `--canary` flag is required. Alternatively, we could run `lerna version` manually first, and then publish that version (the same flow we use for releases). This may not be necessary depending on what we decide for other solutions below. 

With the improvement to dist-tags (see below), I don't think the sha is completely necessary, so maybe we can continue using `--canary`. Previously, we were using it so that we didn't have conflicts after a "prerelease release" (since that resets the count). We should fix this properly by appending the previous release to the preid (e.g. `4.0.0-beta.4-next.0`). Also, with the improvements below, I think it's much more obvious what the affixed number means.

## Prerelease dist-tags

Our current dist-tag release strategy for prerelease branches does not line up with how we treat master. We have a tag for the canary build (`prerelease`), but no tag for alpha/beta releases. This is a bit confusing, and I think we should update to match. Proposal: 

`latest` = The latest released version (e.g. `3.7.0` )
`next` = The latest master merge (e.g. `3.8.1-next.0`)
`prerelease` = The latest prerelease released version (e.g. `4.0.0-beta.3`)
`prerelease-next` = The latest prerelease merge (e.g. `4.0.0-beta.4-next.0`)

Note: the number after the `next` tags indicates the number of canary builds since the last release (either `latest` or `prerelease`)

## Merge commit builds
It's confusing when we generate two builds for a release merge commit (one canary and one for the release itself). We should prevent canary builds in this instance.

We need to determine a way to detect a release merge commit (since the tag is applied after merging). We could either look for "chore: Release" in the commit message, or check if the commit contains changes to `CHANGELOG.md` (can assume this is a release).

**Comment by lychyi** [comment]
Closed via #665
