### ISSUE TITLE
Add CI check for PR title

### ISSUE THREAD

**Issue by anicholls** [Workday/canvas-kit#67]
## 🚀 Feature Proposal

Add a CI check (maybe using GitHub Actions?) to check the PR title for conventional commit style.

Bonus points: Let's start reviewing PRs with the thought in mind that the title of the PR will be the merge commit message (which will ultimately be used in the changelog, so it should be very clear!)

## Motivation

Since we are moving to squash merges, the default squash commit message will be the title of the PR. We would like these commits to follow our standard conventional commit style.

**Comment by alanbsmith** [comment]
This is resolved by #1272
