### ISSUE TITLE
Avatar misaligned on IE

### ISSUE THREAD

**Issue by alexandrzavalii** [Workday/canvas-kit#675]
## 🐛 Bug Report

Avatar is missaligned on IE with version 4.

<img width="433" alt="Screen Shot 2020-05-25 at 3 58 15 PM" src="https://user-images.githubusercontent.com/10633451/82824231-de509380-9ea0-11ea-9637-163c695c43eb.png">

## Browser (if applicable)

IE11

**Comment by anicholls** [comment]
Closed by #676
