### ISSUE TITLE
More Modal variants

### ISSUE THREAD

**Issue by NicholasBoll** [Workday/canvas-kit#681]
## 🚀 Documentation Proposal

Design has identified 2 additional variants that solve common use-cases we've seen:

### Basic Modal
I'd say this is what we have now. No change needed here.

<img width="499" alt="Screen Shot 2020-05-26 at 3 42 04 PM" src="https://user-images.githubusercontent.com/338257/82953168-84ff6780-9f67-11ea-8acd-9472e281998c.png">

### Modal + Action Bar
I don't think we need a subcomponent for this. The example can use a special `ActionBar` component defined in the example. Here's an example: https://codesandbox.io/s/v7-actionbar-modal-4gf6nt

<img width="497" alt="Screen Shot 2020-05-26 at 3 41 54 PM" src="https://user-images.githubusercontent.com/338257/82953190-8e88cf80-9f67-11ea-91bd-aaf5e6ede672.png">

### Media modals Added with [#2226](https://github.com/Workday/canvas-kit/pull/2226) ✅ 
These are modals that have an image or video as the primary content. The example can use a special `MediaContainer` component in the example. Here's an example: https://codesandbox.io/s/v7-media-modal-x3wc28

<img width="507" alt="Screen Shot 2020-05-26 at 3 42 16 PM" src="https://user-images.githubusercontent.com/338257/82953205-98123780-9f67-11ea-807e-8e5662660781.png">

## Motivation

Having these examples in our documentation will make it easier for teams to copy/paste/modify to suite their needs. I'm not sure we need special subcomponents to support these cases. The ask is extra examples added to the documentation of the Modal page.

**Comment by NicholasBoll** [comment]
Related: #790, #786

**Comment by danbrady** [comment]
I'd like to help out with this issue. Would it be okay if I brought in the examples @NicholasBoll posted?

**Comment by RayRedGoose** [comment]
Example with action is still planned
