### ISSUE TITLE
Add toolbar dropdown button

### ISSUE THREAD

**Issue by mannycarrera4** [Workday/canvas-kit#685]
## 🚀 Feature Proposal

A clear and concise description of what the feature is.

## Motivation

As part of the toolbar atomic pieces, design has create a dropdown button with a chevron and an option for an icon or some other element.

This component allows for both use cases from design:
<img width="201" alt="Screen Shot 2020-05-28 at 4 19 53 PM" src="https://user-images.githubusercontent.com/7966550/83199830-3a185800-a0ff-11ea-8f27-7bd2258498af.png">

 And:
<img width="148" alt="Screen Shot 2020-05-28 at 4 20 05 PM" src="https://user-images.githubusercontent.com/7966550/83199856-456b8380-a0ff-11ea-81a1-ac1b6b2e525d.png">

Note: This is not a select, but changing the font type so the "open" state would just be a popup with custom content inside.

## Example

Please provide an example for how this feature would be used.

**Comment by jpante** [comment]
Resolved as part of #684
