### ISSUE TITLE
Loash version has security advisory

### ISSUE THREAD

**Issue by vibdev** [Workday/canvas-kit#69]
## 🐛 Bug Report

Versions of lodash before 4.17.12 are vulnerable to Prototype Pollution. The function defaultsDeep allows a malicious user to modify the prototype of Object via {constructor: {prototype: {...}}} causing the addition or modification of an existing property that will exist on all objects.

## Remediation
commitizen and jest-axe also have this vulnerability and need to be updated. Their repos have not received a patch yet though. They are dev deps and are not published with modules so they are less of a concern in the short term.

https://www.npmjs.com/advisories/1065

**Comment by lychyi** [comment]
Closed via #177
