### ISSUE TITLE
Modal is not sending focus back to the target button, in responsive

### ISSUE THREAD

**Issue by alexandrzavalii** [Workday/canvas-kit#694]
## 🐛 Bug Report

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/10633451/83637885-3291fc80-a5a0-11ea-8075-1687f180c820.gif)

## To Reproduce

 Make sure you use ios device with voiceover.
 Use this codesandbox link to reproduce: https://hqlce.csb.app/

## Expected Behavior

Focus should be sent back to the target, assumingly because missing the 300ms timeout on focus

**Comment by NicholasBoll** [comment]
#618 might have some related implementation

**Comment by NicholasBoll** [comment]
This is fixed in v5
