### ISSUE TITLE
Video Player

### ISSUE THREAD

**Issue by vibdev** [Workday/canvas-kit#70]
## 🚀 Feature Proposal

Lightweight video player. This player would support html5 video and would have having minimal default buttons (maybe play/pause, volume, captions, and full screen). I think there could be some discussion about if we could allow users to extend the list of buttons to add their own functionality. 

## Posible Features

- showControls / hideChrome
- setInitialPlayerState         
  - isPaused
  -  isMuted
  - volume
  - playbackRate
  - currentTime
  - quality
  - width
  - height
  - backgroundColor
- getting and setting playerState
- controlling playback
  - player.play()
  - player.pause()
  - player.mute()
  - player.unmute()
  - player.toggleFullscreen()
- adding listeners for player events
  - player.listen('timeupdate' ...)
  - player.listen('pause' ...)
  - player.listen('seeked' ...)

## Motivation

There has been some interest in a fast lightweight experience that just does video playback.

## Example

Minimum would be something like
```
<VideoPlayer
  source={sourceURL}
>
```
But you could imagine something a bit more complex like
```
<VideoPlayer
  source={sourceURL},
  width={width}
  height={height}
  background={posterImageUrl}
  subtitles={subtitlesObject}
>
```

**Comment by lychyi** [comment]
@vibdev We're working on PR previews which will be crucial to have design help walk through this component. So thanks for being patient as we get that setup... hopefully soon 🤞

**Comment by nathan5x** [comment]
@lychyi - We're going to kick start something similar. Please keep us posted to avoid any overlaps. Our team builds video products under WMC.

**Comment by anicholls** [comment]
As we've established the boundaries of Canvas Kit and the concept of Extended Systems, we've agreed that this probably makes more sense as a part of an Extended System in another repo. Let us know if you have any questions! Thanks for the proposal.
