### ISSUE TITLE
Improve visual testing coverage for Menu

### ISSUE THREAD

**Issue by jpante** [Workday/canvas-kit#714]
Improve coverage of snapshot tests for Menu module..

See #683

**Comment by lychyi** [comment]
A bug has been filed for menu here (#729), something to consider when taking this one on.

**Comment by jpante** [comment]
To address as part of improvements to menu components and system in upcoming release

**Comment by jpante** [comment]
As part of promotion to CK main. in 5.x

**Comment by NicholasBoll** [comment]
Done
