### ISSUE TITLE
Switch Component Enhancement: Add a text description to illustrate the value of each state (on/off)

### ISSUE THREAD

**Issue by aaroncalderon** [Workday/canvas-kit#716]
## 🚀 Feature Proposal

It has been my experience that adding a label/text associated with the state of a switch helps the end user understand the purpose and value of each state, checked and unchecked (on/off).

For this reason I want to suggest a new feature on the Switch component as follows:

- (O  ) Off
- (  O) On
- Off (O  )
- On (  O)

Excuse my lack of examples. I cloned the repo, but I am struggling with creating a Pull Request.

## Motivation

I have seen similar functionality in other samples and implementations of the Switches around the web.

- [Create a Toggle Switch in React as a Reusable Component](https://www.sitepoint.com/react-toggle-switch-reusable-component/)
- Microsoft's PowerApps Switch Component

This piece of visual aid will help the ind user better understand the purpose of the switch.

## Example

For example:

Imagine the following question: 

- Off state: Enable outline? (O  )
- On state: Enable outline? (  O)

It becomes more clear:

- Off state: Enable outline? (O  ) No
- On state: Enable outline? (  O) Yes

Or

- Off state: Outline thickness? (O  )
- On state: Enable thickness? (  O)

It becomes more clear:

- Off state: Enable thickness? (O  ) Thin
- On state: Enable thickness? (  O) Thick

Thanks in advance for your time.

**Comment by anicholls** [comment]
Thanks for the proposal @aaroncalderon I assume you essentially mean mimicking the [`label` prop in `Checkbox`](https://github.com/Workday/canvas-kit/blob/master/modules/checkbox/react/lib/Checkbox.tsx#L43)?

**Comment by aaroncalderon** [comment]
@anicholls yes, with the main difference that we would specify a 'label' value for each state true and false (on/off).

**Comment by jpante** [comment]
Added blocked label - Will work with design on this request.

**Comment by mathalete** [comment]
Note that this relates to https://jira2.workday.com/browse/CANVAS-539 as the current implementation relies on colour alone.

**Comment by aaroncalderon** [comment]
> Note that this relates to https://jira2.workday.com/browse/CANVAS-539 as the current implementation relies on colour alone.

@mathalete I cannot access the provided link/website content.

**Comment by jpante** [comment]
Commentary from recommendation by Peter H.

The canvas switch component https://design.workday.com/components/form-elements/switch  relies on colour alone to communicate its state.

WCAG 1.4.1 Use of Color [Level A].

See attached screen shot simulating achromatopsia (this is colour blindness where a person has no perception of colour) - observe that the state of the control isn't so clear.

The origin of the switch is from iOS. Note that iOS provides an accessibility setting called 'On Off labels' to ensure a user can augment these types of control to ensure they don't rely on colour alone, see https://help.apple.com/iphone/11/#/iph1da59eced

**Recommendation**

Colour that conveys information must have a perceivable alternative.

Augment the switch with text that indicates the current state - ideally 'on' and 'off' should be present within the switch itself
Alternatively, update the visible <label> to have the words 'On' or 'Off prepended to help communicate the state.
In either approach ensure that any visible text used to indicate the current state is wrapped within a container with aria-hidden="true" to ensure there is no audible duplication announcing the visible state text and then the state of the checkbox.
**Example implmentation**

https://cdpn.io/lefthandev/debug/4995b3d52ea0d186bcb49410524e87eb

**Comment by jaclynjessup** [comment]
closing to address in #1774
