### ISSUE TITLE
MenuItem labels are truncated in IE 11

### ISSUE THREAD

**Issue by nathan5x** [Workday/canvas-kit#729]
## 🐛 Bug Report

MenuItem labels are truncated in IE 11. 

## To Reproduce

* Add the below code snippet to any component and open the page in IE 11
```html
<Menu>
    <MenuItem> Menu Item Label 1 </MenuItem>
    <MenuItem> Menu Item Label 2 </MenuItem>
    <MenuItem> Menu Item Label 3 </MenuItem>
    <MenuItem> Menu Item Label 4 </MenuItem>
</Menu>
```

## Expected Behavior

Labels should not be truncated. 

## Actual Results
<img width="155" alt="Screen Shot 2020-06-10 at 11 51 23 PM" src="https://user-images.githubusercontent.com/61951984/84354762-4deba180-ab76-11ea-9d58-c0a1c6d6b0db.png">

## Browser (if applicable)
IE 11

## Link to repl or repo (highly encouraged)

https://4jrbc.csb.app/

**Comment by vibdev** [comment]
https://github.com/Workday/canvas-kit/blob/master/modules/_labs/menu/react/lib/MenuItem.tsx#L123
changing this line to `flex: '1 1 auto',` should fix it
