### ISSUE TITLE
Toast Popup having the onActionLink be a link rather than a button

### ISSUE THREAD

**Issue by Andy93** [Workday/canvas-kit#736]
## 🚀 Feature Proposal

Toast Popup having the onActionLink be a link rather than a button

## Motivation

In Learning Experience on the ActionClick we are using it as a link to a new tab

## Example

Action Click linking a using to Classic Learning in new tab

<img width="1272" alt="Screenshot 2020-06-11 at 14 02 05" src="https://user-images.githubusercontent.com/1674471/84503653-82fd0e80-acb2-11ea-8130-182471fb1396.png">

**Comment by anicholls** [comment]
@Andy93 Thanks for the request! In the short term, is there any reason you couldn't use `window.open()` in `onActionClick()`?

**Comment by alanbsmith** [comment]
This is resolved with the new Toast component. #1309
