### ISSUE TITLE
ColorPicker keyDown -> keyPress

### ISSUE THREAD

**Issue by davvidbaker** [Workday/canvas-kit#760]
## 🐛 Bug? Report

Not exactly a bug, more of a request to change behavior.

The request is to make [this change](https://github.com/Workday/canvas-kit/compare/master...davvidbaker:patch-1) to the color picker hex input behavior. (Use keypress instead of keydown for submission from the hex text input.)

## To Reproduce

The problem with keydown arises in the context of a text editor. We are responding to the `onColorChange` callback by re-focusing the text editor, but the `Enter` keypress event gets fired after the text editor has refocused, resulting in a new line. Changing the color picker text input to respond to the `Enter` keypress instead of keydown would fix this problem.

Here's a gif and sandbox illustrating the problem.
![keydown-color](https://user-images.githubusercontent.com/6373939/85884460-f5d0b400-b79f-11ea-9beb-28f9917fe125.gif)

[Sandbox](https://codesandbox.io/s/magical-hooks-g9poq?file=/src/App.js)

If this is not a change y'all would make, do you have a recommended alternative solution?

**Comment by NicholasBoll** [comment]
I think the `ColorPicker` should be a `form`. That way the `enter` key is automatically handled the way other forms handle data entry. Does that functionality change work for you?

**Comment by davvidbaker** [comment]
> I think the ColorPicker should be a form

How would that work? Currently, the `onColorChange` event happens when _either_ a swatch is clicked _or_ the text input is entered and submitted. Do you mean only the text input and submit parts would be a form?

**Comment by NicholasBoll** [comment]
I guess you haven't explained a use-case yet. I imagine you close the color picker when a color is selected? Why do you want to switch focus only when the enter key is pressed? Why not when the check icon is clicked or a color swatch is clicked?

**Comment by davvidbaker** [comment]
> Why not when the check icon is clicked or a color swatch is clicked?

**Comment by NicholasBoll** [comment]
Not the whole thing, just the input. The checkbox is the submit button. On the submit event, the `onChange` is fired for the `ColorPicker`

**Comment by davvidbaker** [comment]
Cool. I think making it a form should solve the problem.

**Comment by davvidbaker** [comment]
Would this fix go into CanvasKit 4.x or 3.x?

**Comment by NicholasBoll** [comment]
This change would go into 4.x. Do you have a deadline for it?
