### ISSUE TITLE
Add Virtual Elements to Popper component

### ISSUE THREAD

**Issue by luislikescoffee** [Workday/canvas-kit#762]
## 🚀 Feature Proposal

Add the ability to provide custom positioning for the Popper component.
 
## Motivation

Currently the Popper component only allows positioning elements by means of an `anchorElement`. This is great for positioning things relative to other elements, but sometimes I would like to tell Popper exactly where to place things. For example when implementing a context menu, I want to pass in the exact `x` and `y` coordinates of the mouse for placement.

## Example

The way I would imagine this working is by means of a prop that can act in place of `getBoundingClientRect`. A discriminated union would be used to prevent the user from also specifying an `anchorElement` when using this prop.

```tsx
// Correct
const withAnchorElement = <Popper anchorElement={myElement} />

// Correct
const withOverride = (
  <Popper
    overrideGetBoundingClientRect={() => {
      top: 10,
      left: 10,
      bottom: 100,
      right: 100,
      width: 12,
      height: 12,
    }}
  />
)

// Type error
const withBoth = (
  <Popper
    anchorElement={myElement}
    overrideGetBoundingClientRect={() => {
      top: 10,
      left: 10,
      bottom: 100,
      right: 100,
      width: 12,
      height: 12,
    }}
  />
)
```

Under the hood, Canvas would then take this function and create an object to pass to the underlying Popper instance to use as an Element. The `PopupStack` would not receive an owner element.

## Inspiration

This proposal was largely inspired by `react-popper`: (https://popper.js.org/react-popper/v2/virtual-elements/). However, unlike `react-popper` I am proposing that we don't ask the consumer to pass a "Virtual Element". Attempting to do this in the current version of Canvas works, but it's not correct. What is being passed in is not an element and it creates problems for the `PopupStack`. I think this should be communicated to the consumer and I think it feels kind of hacky to pass in an object with just `getBoundingClientRect` declared. Better to hide this in the component 😉

**Comment by NicholasBoll** [comment]
Is there strong opposition to the way PopperJS handles virtual elements? We can easily detect if a provided element is a virtual element or a real element and only pass an element to the PopupStack's `owner` property if it is a real element (this is used for the detection of inside clicks and to connecting popup's together through these owner elements).

If we don't want to use virtual elements, the prop name is a little strange. What does `overrideGetBoundingClientRect` do? If it isn't allowed with an anchor element, then it isn't overriding anything. Perhaps `anchorGetBoundingClientRect`? Or `getAnchorClientRect` to be more succinct.

I'm not sure either should be strictly necessary. Both just aid in positioning the popup. If neither are provided, the popper doesn't position, right?

**Comment by luislikescoffee** [comment]
No strong opinions here, just how I thought it should work. Should we allow both? If we do which one wins?

**Comment by NicholasBoll** [comment]
Disjoint unions are entirely possible. We do this for the `Button` family of components where you either provide props valid for a `button` element or provide an `as="a"` and then props valid for an anchor element. It does add some complexity though. In the case of Button, it seemed worth it for type checking attributes that are valid for `button` and an anchor separately.

The "override" in the prop name got me thinking that it would in fact override. I think it would be okay to accept both with the `getAnchorClientRect` overriding the physical position of the element. The `getAnchorClientRect` could be optional with the JSDoc explaining it will override the `ClientRect` of the anchor (if provided) or could act in place of `anchorElement`.

We should add something to the JSDoc of `anchorElement` that it will act as the "owner" of the Popper for PopupStack behaviors that make use of "owner" (like `useBringToTop` and `useCloseOnClickOutside`)

I'm not sure what PopperJS will do with that provided function on things like scrolling.

**Comment by luislikescoffee** [comment]
Are there cases where we will want `getAnchorClientRect` but not `anchorElement`? I'm thinking about context menus right now.

**Comment by luislikescoffee** [comment]
I tried out both using a discriminated union and just making `getAnchorClientRect` an optional prop. The latter was far cleaner and requires a similar amount of documentation so I think this may be the approach I take.
