### ISSUE TITLE
Header responsive behavior no longer working

### ISSUE THREAD

**Issue by anicholls** [Workday/canvas-kit#763]
## 🐛 Bug Report

The responsive breakpoints no longer seem to be activating in storybook

## To Reproduce

1. Go to https://workday.github.io/canvas-kit/?path=/story/labs-header-react--dub-header
2. Scale down the page

## Expected Behavior

Header should collapse

## Actual Results

It does not collapse

**Comment by alanbsmith** [comment]
Closing this as we deprecated the component.
