### ISSUE TITLE
Update SidePanel to match new design specifications

### ISSUE THREAD

**Issue by jpante** [Workday/canvas-kit#778]
## 🚀 Feature Proposal

Update side panel container to match design updates.

- Side Panel header to include optional accent icon to left of title
- Expand/collapse icon moved from bottom to top to meet A11y requirements
- Expand/collapse and title positioning rules depending on 1 or 2 lines of text
- Update expand/collapse Side Panel animation
- Collapsed side panel should also be Soap 100 on collapse

## Motivation

These updates to the side panel container are to create a more cohesive 

## Example

![Screen Shot 2020-07-15 at 8 50 11 AM](https://user-images.githubusercontent.com/1861673/87567834-9caac080-c679-11ea-8935-f349184fdfd4.png)

**Comment by lychyi** [comment]
There have been a lot more discussions to this now. I think we can move on this request without going to 5.x. The main updates are:
* The current should be deprecated (or we'll break it visually anyway) so we can add this new SidePanel in Labs targeting 4.x
* The side panel header is something that can be shipped separately from a side panel "shell": box that has opinions on `width` motion and perhaps a default icon button placement for the expand/collapse action. This allows us to deliver the first iteration of the panel faster while we consider other things.
* This new panel will have no opinions on the contents or spacing within. That is all up to the user or any other components that could follow, e.g. side panel items, side panel collapsable panes, etc.

Proposal drafted [here](https://codesandbox.io/s/canvas-kit-side-panel-proposal-zi4ox).
