### ISSUE TITLE
Modal - full width and full height support

### ISSUE THREAD

**Issue by NicholasBoll** [Workday/canvas-kit#786]
## 🚀 Feature Proposal

Support full-screen growth of modals. The design specification lists out how Modals should grow both in width and it height. Modals only have set sizes.

## Motivation

Teams sometimes need modals that maximize content shown to minimize scrolling.

## Example

Large: Screen width of 1024px or greater:

<img width="777" alt="Screen Shot 2020-07-21 at 9 20 41 AM" src="https://user-images.githubusercontent.com/338257/88073495-7bdbe280-cb33-11ea-9d75-380435507cd1.png">

Medium: 768px to 1024px

<img width="462" alt="Screen Shot 2020-07-21 at 9 22 11 AM" src="https://user-images.githubusercontent.com/338257/88073740-c2c9d800-cb33-11ea-8db9-c8b3c4afcd2a.png">

Small: Less than 320px

<img width="228" alt="Screen Shot 2020-07-21 at 9 22 19 AM" src="https://user-images.githubusercontent.com/338257/88073759-c9f0e600-cb33-11ea-8024-e5b67b2d6f46.png">

**Comment by NicholasBoll** [comment]
Related: #790, #681

**Comment by NicholasBoll** [comment]
I ran into issues with the different margins around the different screen sizes. The modals are centered, but having a different top and bottom margin throw off the center calculations. Should Modals center or pin to the top? Why have a larger left/right margin on the medium screen size? This leaves less room for content on a smaller screen than the large screen size.

**Comment by NicholasBoll** [comment]
Modals now grow to fit contents with a maximum size. So functionally, this is solved.

What's left for a question is margins via design.

**Comment by jaclynjessup** [comment]
Margins via design will be handled. Usage guidance for margins will be used.
