### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by 6r3al** [Workday/canvas-kit#801]
## 🚀 Feature Proposal

Option to turn on dark mode in Storybook: https://storybook.js.org/docs/configurations/theming/

## Motivation

Being able to check how components look with a dark background can help flagging issues.

## Example

Undesired halo around Avatar Dark variant can only be seen with dark background. 
![darkmode](https://user-images.githubusercontent.com/35978459/88415481-7c47d800-cdd6-11ea-828d-abaef1e4821e.png)

**Comment by jaclynjessup** [comment]
We currently do not support Dark Mode within Workday. Therefore we will not be adding this to our storybook. We will revisit this when Dark Mode is supported globally.
