### ISSUE TITLE
Menu Component Update

### ISSUE THREAD

**Issue by alanbsmith** [Workday/canvas-kit#813]
## 🚀 Feature Proposal

* Update storybook examples to match the [design spec](https://www.figma.com/file/zGe7lKAo2FgDQnU0vU1VVp/Internal-Canvas-Web?node-id=1375%3A17).
  * specifically populating the empty icon item (Item 4 in the Icon Menu)
* Add support for multi-line text wrapping in menu items

## Motivation

The [Menu component spec](https://www.figma.com/file/zGe7lKAo2FgDQnU0vU1VVp/Internal-Canvas-Web?node-id=1375%3A17) has been updated and needs to be updated in CK.

## Example

A11y would like long menu item text to not be truncated.

**Comment by myvuuu** [comment]
Needs to be done after https://github.com/Workday/canvas-kit/issues/1318
