### ISSUE TITLE
RFC: Box Component

### ISSUE THREAD

**Issue by alanbsmith** [Workday/canvas-kit#822]
# Box

## Summary

_a primitive for building containers_

Box is a low-level, visual primitive component. It's highly flexible and is only constrained by our token values. It's purpose is to provide a base component that can be composed into other specific instances throughout Canvas Kit.

### What's a "primitive" component?

We usually think of low-level components as `Button`s, `Icon`s, `Header`s, etc. If you're familiar with [Atomic Design](https://bradfrost.com/blog/post/atomic-web-design/), you could call these "atoms." Primitves live a little lower. If we’re keeping the atomic design metaphor, they’re like the electrons, protons, and neutrons of the system.

Box is one of these primitives. It knows about our theming and tokens, and it exposes visual props that allow it to be manipulated in lots of different ways within the parameters of our design system.

### Problem

Many of the components we build in Canvas Kit are really containers under the hood. `SidePanel`, `Menu`, `Card`, `Toast`, `Tooltip`, etc. While they all have their own styling and behaviors, they basically boil down to `Box`es. But because they aren't connected built with common primitive components, such as `Box` they are more challenging to update and maintain.

`Box` will help us:

- create a shared component API across all containers
- consolidate our API surface area
- empower teams teams adapt components for their use cases
- reduce the number of new components needed in CK
- reduce effort to create new components

### Constraints

`Box` is highly flexible, but does have a few constraints:

- It is only concerned with styling
  - no behavior, business logic, or state
- It is intended for box-like elements
  - not text, inputs, buttons, etc
- It is constrained to values within our design system (where appropriate)
  - spacing, color, etc. props will only allow system values

## Prior Art

- [Styled System](https://styled-system.com/api)
- [Chakra UI](https://github.com/chakra-ui/chakra-ui/blob/develop/packages/layout/src/box.tsx)
- [Primer Components](https://github.com/primer/components/blob/master/src/Box.js)
- [Theme UI](https://github.com/system-ui/theme-ui/blob/master/packages/components/src/Box.js)
- [Paste](https://github.com/twilio-labs/paste/blob/main/packages/paste-core/primitives/box/src/index.tsx)

### Props

While `Box` has a long list of props, it uses CSS properties for its API. This provides a familiar interface for developers. And those using Typescript will also have the advantage of [CSS types](https://www.npmjs.com/package/csstype) that will allow for autocomplete and inline validation.

#### As

_The `as` prop is limited to container elements (div, article, aside, footer, header, main, section, span, etc)_

#### Background

- backgroundImage
- backgroundSize
- backgroundPosition
- backgroundRepeat

#### Border

_Border props will only accept values from our tokens (color, radii, etc)_

- border
- borderWidth
- borderStyle
- borderColor
- borderRadius
- borderTop
- borderTopWidth
- borderTopStyle
- borderTopColor
- borderTopLeftRadius
- borderTopRightRadius
- borderRight
- borderRightWidth
- borderRightStyle
- borderRightColor
- borderBottom
- borderBottomWidth
- borderBottomStyle
- borderBottomColor
- borderBottomLeftRadius
- borderBottomRightRadius
- borderLeft
- borderLeftWidth
- borderLeftStyle
- borderLeftColor
- borderX
- borderY

#### Color

_Color props will only accept values from our color tokens._

- color
- bg
- backgroundColor

#### Layout

- width
- height
- display
- minWidth
- minHeight
- maxWidth
- maxHeight
- size
- verticalAlign
- overflow
- overflowX
- overflowY

#### Position

- position
- zIndex
- top
- right
- bottom
- left

#### Shadow

_Shadow props will only accept values from our tokens_

- boxShadow

#### Space

_Spacing props will only accept values from our spacing tokens._

- margin (alias: m)
- marginTop (alias: mt)
- marginRight (alias: mr)
- marginBottom (alias: mb)
- marginLeft (alias: ml)
- marginX (alias: mx)
- marginY (alias: my)
- padding (alias: p )
- paddingTop (alias: pt)
- paddingRight (alias: pr)
- paddingBottom (alias: pb)
- paddingLeft (alias: pl)
- paddingX (alias: px)
- paddingY (alias: py)

### Example

A custom `Card` component built with `Box`:

```tsx
// Card can choose whether to expose BoxProps or not
const Card = (props) => {
  <Box
    padding="m"
    border={`solid 1px ${colors.border}`}
    boxShadow={boxShadow}
    {...props}
  />;
};
```

## Drawbacks

One of the benefits of Canvas Kit today is that components are structured in a relatively flat hierarchy is that each component starts with little-to-no assumptions about the other components. Creating primitive components, such as `Box`, gives that up. `Box` in particular will be used throughout most of our composed components and will have implications for how they are built.

Another initial drawback is that creating a new component API and way of building will inevitably lead to initial confusion. It will affect how we and other developers create and modify components.

## Alternatives

Instead of a centralized `Box` component, we could have a collection of prop utilities that we could spread over components. This would create a lot of the same benefits without relying on a central component. But the rework per component would be significant, in my opinion.

## Open Questions

- Should `Box` be limited container-like components, or should it be the base for all our components?
- Is the list of props too large, is it fine, or should there be more?

### How should `Box` props be exposed in higher-level components?

We'll need to be really thoughtful about which props we expose and where. It's easier to expand a component API than to reduce it. As a general rule, higher-level components should not expose style props. Lower-level, less-opinionated components will however. For example, a Card component:

```tsx

interface CardProps extend BoxProps, HTMLElement<HTMLDivElement> {
  // special card props (if any) would go here
}

const Card = ({
  children,
  p='s',
  border=`1px solid ${borderColor}`,
  ...props,
 }) => {
  return (
    <Box p={p} {...props}>
      {children}
    </Box>
  );
}
```

While we have an opinion about how default cards should appear, we also want to allow flexibility for different variations. Exporting some or all of `Box`'s style props makes that possible. Alternatively, A component like `DropdownMenu` with a very specific use-case, would not export style props.

### Is it too restrictive to limit spacing props to token values?

I think it's fine to expand spacing props to allow non-system values. I'd like to clarify that `Box` is not intended as a layout component, but instead to be composed into _new_ components. I think margin and padding will be likely use system values. I also think `Box` will primarily be used internal to Canvas Kit, though teams could use it to build net-new components that aren't defined in Canvas. But it's intended as a last resort when higher-level components don't meet your use-case.

### Would nested `Box` children inherit styles from their parents?

One of the nice things about Emotion is ensuring styles are scoped to a particular component. Unintended side-effects from CSS are minimized. That said, we still live within the parameters of the CSS cascade, and it would be possible for a `Box` to set a value such as `color` and have an internal component `inherit` that style. It's a general best-practice for components to only style themselves without introducing side-effects into other components further down the markup tree.

### Should we have token values for all props?

The short answer is no. If we think of tokens as a way to encapsulate our design sub-systems: space, color, typography, depth, motion, shape, etc., we really only need tokens that capture those values. Style props such as `width`, `height`, etc. can be left as generic values to provide more flexibility.

**Comment by anicholls** [comment]
Also a question: Are some/all of the `Box` props expected to be exposed if it is the outermost container of a component? (e.g. we may want configurability over the padding within a card/popup component). Maybe this is something we leave to be defined explicitly

**Comment by alanbsmith** [comment]
@anicholls, yeah. Good question. My general take is: For higher-level components, low-level style props aren't exposed. Example: A `DropdownMenu` has opinions about how it should render for visual consistency and wouldn't expose padding / margin / etc props. If you need to customize it, grab another `Box`, style it, and add the behaviors you need.

Lower-level components seem more up in the air to me. Maybe `Card` has default values for padding set, but we allow users to override it? That depends on how much friction we want with `Card`s. But that doesn't stop someone from using `Box`. and styling it similarly.

**Comment by alanbsmith** [comment]
@anicholls , a follow-up to this is that we'll need to be really thoughtful about what we expose and where. It's easier to expand a component API than it is to reduce it.

**Comment by alanbsmith** [comment]
A pattern for safely spreading props: https://github.com/twilio-labs/paste/blob/main/packages/paste-core/primitives/box/src/SafelySpreadProps.ts

**Comment by lychyi** [comment]
> Spacing props will only accept values from our spacing tokens.

This sounds a bit restrictive to "only" accept values from tokens. We've run into plenty of situations internally (and from app teams in general) that need to break out of our spacing tokens. To me, I like the idea that it's flexible, maybe props accept strings that match our spacing sizes e.g.`xxs` or `m` _and_ any other number e.g. `17` or string e.g. `auto` or `40%` as well.

There are just too many edge cases and reasons to have spacing, colors, depth, etc. outside of our tokens. I would vote to make our token usage easy while still providing a way to use other values.

**Comment by alexandrzavalii** [comment]
yeah I agree, I think if we cover the exceptions by allowing not only spacing but also 'px, %' maybe even em,rem, We are making sure that Box component can be used for 100% use cases.

**Comment by alexandrzavalii** [comment]
I guess another very useful thing would be to accept array of values to cover responsiveness.
```
<Box pl={['xxl', '50%', '200px']} />
```

**Comment by michael-oloughlin** [comment]
Is it possible to have nested `Box`es. If so would the child `Box` also inherit the styles of the parent `box` or can we override styles when necessary? Im thinking of a scenario whereby the child `Box` needs different padding or margins to the parent.

**Comment by michael-oloughlin** [comment]
If the `props` only accept values from our tokens should we have a value for each item (in this `props` list above) defined in our canvas tokens

**Comment by alanbsmith** [comment]
_Added this question to the FAQ above_

> Is it possible to have nested `Box`es. If so would the child `Box` also inherit the styles of the parent `box` or can we override styles when necessary? Im thinking of a scenario whereby the child `Box` needs different padding or margins to the parent.

One of the nice things about Emotion is ensuring styles are scoped to a particular component. Unintended side-effects from CSS are minimized. That said, we still live within the parameters of the CSS cascade, and it would be possible for a Box to set a value such as color and have an internal component inherit that style. It's a general best-practice for components to only style themselves without introducing side-effects into other components further down the markup tree.

**Comment by alanbsmith** [comment]
Added this question to the FAQ above

@michael-oloughlin

> If the `props` only accept values from our tokens should we have a value for each item (in this `props` list above) defined in our canvas tokens

The short answer is no. If we think of tokens as a way to encapsulate our design sub-systems: space, color, typography, depth, motion, shape, etc., we really only need tokens that capture those values. Style props such as width, height, etc. can be left as generic values to provide more flexibility.
