### ISSUE TITLE
RFC: Flex Component

### ISSUE THREAD

**Issue by alanbsmith** [Workday/canvas-kit#834]
# Flex

## Summary

_a primitive for creating layouts_

`Flex` is a low-level component to align elements in rows and columns. It's built on top of the `Box` primitive, but it's designed to use [CSS Flexbox](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout) for aligning content.

### Problem

Creating maintainable layouts is challenging. A lot of the problem stems from how we think about managing space and layout. It's very easy to get lost in the details of styling a single component and lose sight of how elements relate to one another in space.

`Flex` creates a helpful, ergonomic API that allows users to put together layouts without getting lost in the details. By constraining options for how to align content, we help engineers make the right choices quickly.

### Constraints

Like `Box`, Flex is also highly flexible, but is a bit more constrained:

- It has all `Box`'s constraints
- It is focused on creating layouts
- It is limited to using CSS Flexbox for aligning content

## Prior Art

- [Theme UI](https://theme-ui.com/components/flex)
- [Chakra UI](https://chakra-ui.com/flex)
- [Primer Components](https://primer.style/components/Flex)

### Props

`Flex` extends `Box` and has access to all `BoxProps` as well.

### Flex

- alignItems
- alignContent
- justifyItems
- justifyContent
- flexWrap (alias: wrap)
- flexDirection (alias: direction)
- flex
- flexGrow (alias: grow)
- flexShrink (alias: shrink)
- flexBasis (alias: basis)
- justifySelf
- alignSelf
- order

### Example

```tsx
<Flex flexDirection="column" flexGrow={1} padding="s">
  <Flex flexGrow={1} padding="m">
    First Item
  </Flex>
  <Flex flexGrow={1} padding="m">
    Second Item
  </Flex>
  <Flex flexGrow={1} padding="m">
    Third Item
  </Flex>
</Flex>
```

## Drawbacks

By adding `Flex` to our library, we're starting to become opinionated about how teams should create layouts. They are not blocked from working in other ways, but we're establishing a preference for how they should use our library. This is an approach I'm borrowing from [Libertarian Paternalism](https://www.jstor.org/stable/3132220?seq=1) as described by Richard H. Thaler. With every opinion we add to CK, we'll also need additional communication around that choice.

I would also highly recommend we use styled system under the hood for this as handing responsive values is extremely important for layout, but it also comes at the cost of another dependency and another API to learn.

## Alternatives

Similar to `Box`, we could create Flexbox utilities for other components to consume and use. This creates an extra step for the user but would remove the dependency on a single `Flex` component.

## Open Questions

- Is exposing all the `Box` props a good idea?
- Should this be limited to container components?

**Comment by jsievenpiper** [comment]
To be honest -- I'd probably never use this component, unless I'm missing some magic value add here.

Teams are rarely going to be needing _just_ flex styling: it often comes along with colors, padding, margins (which I recognize you've added here via the canvas spacing), and is abstracted / shared in ways unique to each application I've seen. So they'll often have flex properties, but more too.

I've also noticed a trend of teams trying to abstract their CSS from the tooling (e.g. emotion, canvas-kit). The idea being that a migration like glamorous -> emotion would not be as difficult the second time around. I can't say I personally subscribe to that group (but I understand the sentiment). Those types of teams would likely be less willing to adopt this, as this abstracts away CSS in a way that's non-portable.

Would this make responsive flexbox design any more / less ergonomic?

**Comment by alanbsmith** [comment]
@jsievenpiper Great thoughts! Thanks for sharing. 😄 

So, `Flex` would be built on top of `Box`, and would have access to all [its props](https://github.com/Workday/canvas-kit/issues/822) in addition to the Flexbox properties. I should call this out in a more pronounced way. Apologies for the confusion.

And thank you for the context on abstracting CSS from tooling. I'd like to learn more about what problem portable styles are solving. I'll follow-up in Slack for a longer convo. 😄

**Comment by alexandrzavalii** [comment]
I do see the value of the Flex component, we are using flex in 99% of layouts :D
