### ISSUE TITLE
Update Pagination Component

### ISSUE THREAD

**Issue by lychyi** [Workday/canvas-kit#843]
CANVAS-1016

Spike to figure out engineering work required from design and teams consuming pagination.

Deliverable: make a list of the requirements based on the differences of the new pagination and the current pagination design.

Also take into account new pagination design discussions in case they change this component fundamentally.

**Comment by lychyi** [comment]
# Summary
Our current pagination component looks and interacts something like this:

**Basic**
![image](https://user-images.githubusercontent.com/14299381/95800556-8201db00-0cac-11eb-93fe-99dae559ce8f.png)
**Non-linear Jump**
![image](https://user-images.githubusercontent.com/14299381/95800538-72829200-0cac-11eb-954c-c70b8a95ee01.png)
**Compact**
![image](https://user-images.githubusercontent.com/14299381/95800550-79110980-0cac-11eb-887f-38c5541d0408.png)

## Why the change?
Our design system team has identified new requirements based on a couple facts:
* Designers are requesting a simpler pagination look and interaction, especially on compact viewports
* The "windowing" interaction in the **Non-linear Jump** version is really complex for no real good reason
* We need to think about first/last controls in addition to prev/next
* We need to account for the use case that a user may not know the final page count

Some technical and architectural considerations came into play too:
* We wish to be able to extend things via composability rather than additional props

# Proposed Changes
![image](https://user-images.githubusercontent.com/14299381/95800882-621ee700-0cad-11eb-9295-a4b7c7f697c6.png)

**Design Changes**
* We're getting rid of the complex "truncation" behavior when you're paging through things
* We're specifying first/last controls using the double chevron icons
* "Goto" input is now part of the label

**Technical Changes**
A new API is still WIP but it'll tend to favor sub components like `Pagination.Label` where we can rather than a config like `showLabel`.

# Approach
The first thing is to start by breaking out the components into more composable bits rather than exposing props (where it makes sense).

**Today's code**
![image](https://user-images.githubusercontent.com/14299381/95801576-8d0a3a80-0caf-11eb-8734-8d7535541d50.png)

**Can be refactored into components like:**
* Pages
* Buttons (first/last, prev/next)
* Label (e.g. "1-10 of many")
* Input

Then we could write a hook like: `usePagination` to extract the wiring of all of the `aria-` attributes to colocate the logic. Then you can spread things like `...paginationProps`, `...buttonProps`, `...labelProps` onto the subcomponents that need it.

Finally, we have the opportunity to simplify a lot of the logic in our current pagination component and delete a lot of the current code and tests since we don't rely on "windowing" (show a subset of pages with the `...` in between) as we increment and decrement pages.

# Open Questions
* When everything is refactored, what should be exposed as public API?
* There are a lot of sub components to this one, should we also ship common variants that are a lot easier to use?

**Comment by alanbsmith** [comment]
@lychyi,

I really like what you have laid out here; I think it makes a lot of sense. 👍 

Regarding your questions:

> When everything is refactored, what should be exposed as public API?

I would have to play with the component a bit to see, but I think we generally want to expose:

* top-level component and sub-components (and their types)
* a behavioral hook like `usePagination`
* possibly a common variant for the default / most common case (if needed / makes sense)

> There are a lot of sub components to this one, should we also ship common variants that are a lot easier to use?

I would opt to only ship what we think will be the most common case, and have doc examples for how to build the others.

**Comment by lychyi** [comment]
@alanbsmith Agreed. The code example should reflect those sentiments. I made the edits this morning.

I think we'll just have to see how it goes but the idea is to get this version out as soon as possible for team wanting this next release.
