### ISSUE TITLE
Update Icon Button to support multiple accents

### ISSUE THREAD

**Issue by seans-cummin** [Workday/canvas-kit#847]
## 🐛 Bug Report

Icon buttons (toggled on) poorly display system icons that feature multiple accents, most notably on active states. Example of an icon with this issue: wd-icon-c-bar-clustered

## To Reproduce

Insert wd-icon-c-bar-clustered into a  toggled state icon button
https://workday.github.io/canvas-kit/?path=/story/testing-react-buttons-button-icon-button--icon-button-states

## Expected Behavior

A system icon with multiple accents like wd-icon-c-bar-clustered should behave like an icon with just a fill.

## Actual Results

A system icon with multiple accents like wd-icon-c-bar-clustered will only display different icon states using the fill, leaving the accent colors unaccounted for (see Image).

<img width="743" alt="Screenshot 2020-09-03 at 11 27 41" src="https://user-images.githubusercontent.com/64029458/92103928-89de7d80-edd8-11ea-9892-e6017bf5db50.png">

## Clarification on the problem
See https://github.com/Workday/canvas-kit/pull/848#discussion_r492398824

**Comment by mannycarrera4** [comment]
This issue is related: https://github.com/Workday/canvas-kit/issues/793
