### ISSUE TITLE
Add additional support to PageHeader

### ISSUE THREAD

**Issue by anicholls** [Workday/canvas-kit#85]
## 🚀 Feature Proposal

It would be cool if `PageHeader` could be customized to achieve results similar better support what is available in our product:
<img width="540" alt="1060e0f6-4a3c-11e9-872c-240e560a2b0e" src="https://user-images.githubusercontent.com/908478/62662076-af742b80-b927-11e9-93ba-cfa125fccb87.png">

It would be really convenient if it had component that wrapped the left/right side, and common parts like title/sub-title like:

```tsx
function MyPageHeader() {
  return (
    <PageHeader title="Hello">
      <PageHeader.TitleContainer>
        <PageHeader.Title>View Flows</PageHeader.Title>
        <PageHeader.SubTitle>HackerRank <Button /></PageHeader.SubTitle>
      </PageHeader.TitleContainer>
      <PageHeader.Navigation>
        <IconButton icon={exportIcon} />
        <IconButton icon={fullscreenIcon} />
      </PageHeader.Navigation>
    </PageHeader>
  )
}
```

## Motivation
To avoid reimplementing (almost) the same component with custom children/make the PageHeader a bit more customizable for use cases when a title and controls are not enough

**Comment by myvuuu** [comment]
Deprecating page header in v6
