### ISSUE TITLE
Modal's with overlay backgrounds in IE11 don't always cover the fullscreen

### ISSUE THREAD

**Issue by UltraTempest** [Workday/canvas-kit#850]
## 🐛 Bug Report
Modal's should appear in front of the content already on screen in all instances. This currently isn't happening in IE11 within the learning codebase:
![1703fe00-eecf-11ea-8249-afd4e436d532](https://user-images.githubusercontent.com/14952930/92370718-9291c500-f0f2-11ea-878a-dfc227ac361f.png)

Versus how it displays in all other browsers:
![18cdc180-eecf-11ea-8db8-f91693d7a01b](https://user-images.githubusercontent.com/14952930/92370695-8a398a00-f0f2-11ea-9c8e-d448dcc02f0d.png)

## To Reproduce

You'll need access to the new Workday Learning Experience on a test environment:

Login
Navigate to Future of Learning Blended Course
Enroll 
Navigate to the Webinar, Lesson 6
Select 'View All Lesson Details'

## Expected Behavior

Modal appears with Login Details and Additional Information

## Actual Results

Modal appears behind the Lesson Overview component and cannot be viewed

## Browser (if applicable)

IE11

**Comment by NicholasBoll** [comment]
We've dropped support for IE11 and won't be fixing this. There is a workaround internal teams use and we'll leave the existing code so the current workaround continues to work.
