### ISSUE TITLE
CanvasProvider's bdo tag is not recognized in IE11

### ISSUE THREAD

**Issue by miguelc1221** [Workday/canvas-kit#862]
## 🐛 Bug Report

When using the `<CanvasProvider />`, IE11 doesn't recognize the `<bdo>` tag and so IE in this case doesn't add a display property, therefore there is a blank space above our app (you can see how the right border on sidebar doesn't reach the top). Explicitly Adding display: 'block' fixes this issue.
![image](https://user-images.githubusercontent.com/11799597/93621819-5a636f80-f999-11ea-969a-c1c1ac17e4b6.png)

## To Reproduce

- Wrap your app component in `<CanvasProvider />`
- Render a `<h1>Hi</hi>` and remove any top margins/padding
- You can now see that the `Hi` text still has a space above

## Expected Behavior

There should be no space above our app when using the `<CanvasProvider />` in IE11.

## Browser (if applicable)

IE11

**Comment by lychyi** [comment]
Thanks for reporting, @miguelc1221 

Do you have a code sandbox for this or a proposed fix?

**Comment by miguelc1221** [comment]
@lychyi i don't have a sandbox, but i believe @NicholasBoll confirmed this. The fix would be to add a `display: 'block'` to the bdo tag

**Comment by miguelc1221** [comment]
i can open a quick pr when i have some time.

**Comment by anicholls** [comment]
Closed by #868
