### ISSUE TITLE
Reset Color Swatch doesn't show box-shadow when given different formats of #ffffff (FrenchVanilla100)

### ISSUE THREAD

**Issue by Riffmeister** [Workday/canvas-kit#881]
## 🐛 Bug Report

If a consumer of colorSwatch passes in #ffffff (colors.frenchVanilla100) a box shadow around the color swatch (https://github.com/Workday/canvas-kit/blob/master/modules/color-picker/react/lib/parts/ColorSwatch.tsx#L30) is created. However, if a user passes #FFFFFF, #fff, or #FFF the box-shadow is not created despite the color being the same. This especially seems strange for the reset color button because if a format other than #ffffff is passed in we do not have any indication of a color swatch next to reset because it all just looks white. 

## To Reproduce

Pass #FFFFFF, #FFF, or #fff into the colorSwatch component and notice that no box-shadow is applied to the swatch.

## Expected Behavior

I would expect that the box shadow should appear when I pass in any format of #ffffff.

## Actual Results

Passing in #FFFFFF, #FFF, or #fff results in a color swatch that blends into the container when the container is also #ffffff.

## Browser (if applicable)

I was on chrome.

### Error Output

![image](https://user-images.githubusercontent.com/10534488/95769318-ef921500-0c74-11eb-9443-e021d524effc.png)

**Comment by NicholasBoll** [comment]
Thanks for submitting this issue. This will probably be a problem for other colors as well that are close to pure-white. Not all screens show perfect color reproduction and not everyone sees all colors. I will take this issue to the team to figure out what we should do in the case of low-contrast colors against the background.

**Comment by NicholasBoll** [comment]
I tried a few different things:

Always have a border:
![image](https://user-images.githubusercontent.com/338257/95790480-afdf2380-0c9c-11eb-8349-33f589666fa4.png)

Have a border with less than 1.5 contrast value:
![image](https://user-images.githubusercontent.com/338257/95790528-c4bbb700-0c9c-11eb-861a-81bdb66f905a.png)

**Comment by NicholasBoll** [comment]
We'll bring this up with accessibility. We'll still put this into our backlog. We can fix the case where the color is pure white independent of the decision for the box shadow on more swatches

**Comment by Riffmeister** [comment]
Thank you for jumping on this @NicholasBoll!
