### ISSUE TITLE
Remove `aria-label` requirement restrictions for IconButton

### ISSUE THREAD

**Issue by lychyi** [Workday/canvas-kit#894]
## 🐛 Bug Report

Currently for `IconButton` (**TODO** and I'm sure other components) we require `aria-label` as a prop/attribute but it really should require _either_ `aria-label` and `aria-labelledby`.

I would vouch to either 1) remove the restriction entirely and promote accessibility through documentation or 2) add a union type that specifies that we require one or the other.

**Comment by NicholasBoll** [comment]
Closed by #1401
