### ISSUE TITLE
Resolve test warnings

### ISSUE THREAD

**Issue by anicholls** [Workday/canvas-kit#90]
## 🐛 Bug Report

There are various warnings being logged in four test files. Currently our tests pass as long as there are no errors, but we should aim to have no warnings when running tests.

### To Reproduce

Run `yarn test`

### Error Output
![Screen Shot 2019-08-08 at 9 05 53 AM](https://user-images.githubusercontent.com/908478/62719200-56a2a280-b9bc-11e9-8d7f-943d619cfce9.png)
![Screen Shot 2019-08-08 at 9 05 59 AM](https://user-images.githubusercontent.com/908478/62719220-5f937400-b9bc-11e9-8f9a-84a2f700c362.png)
![Screen Shot 2019-08-08 at 9 06 06 AM](https://user-images.githubusercontent.com/908478/62719223-615d3780-b9bc-11e9-95b5-61460383cb3b.png)
![Screen Shot 2019-08-08 at 9 06 21 AM](https://user-images.githubusercontent.com/908478/62719226-63bf9180-b9bc-11e9-9ccc-0f848783e2a1.png)

**Comment by rbrishabh** [comment]
Hey! Can I take this up?

**Comment by myvuuu** [comment]
Not running test locally anymore
