### ISSUE TITLE
Add Box and Flex for internal use

### ISSUE THREAD

**Issue by alanbsmith** [Workday/canvas-kit#906]
## 🚀 Feature Proposal

Add `Box` and `Flex` components for internal canvas-kit use.

## Motivation

As discussed in #822 and #834, `Box` and `Flex` support our effort to make canvas-kit more composable. As we build out our behavioral primitives, we should also begin to add visual primitives.

We should start adding these primitives for internal use so we can iterate on the API and validate the approach.

## Example

Examples are provided in the #822 and #834 RFCs.

**Comment by mannycarrera4** [comment]
We use this already internally! :)
