### ISSUE TITLE
icon inside button moves when clicked in IE11

### ISSUE THREAD

**Issue by znahman** [Workday/canvas-kit#907]
## 🐛 Bug Report

When a button with an icon in it is clicked in IE, the icon moves down and to the right slightly. Expected the icon to stay stationary like the text. (afaik only happens in IE)

See gif:
![button](https://user-images.githubusercontent.com/24512926/99284380-6c278e80-27f3-11eb-9753-86a4c4de33ef.gif)

## To Reproduce

Click button with icon in IE. 

## Expected Behavior

Text and icon stay stationary on click.

## Actual Results

Text stays stationary but icon moves down and to the right.

## Browser (if applicable)

IE

**Comment by jaclynjessup** [comment]
IE11 support has been deprecated
