### ISSUE TITLE
Tabs Phase 2: Single List

### ISSUE THREAD

**Issue by jpante** [Workday/canvas-kit#910]
Update Tabs to support the following features:

## Overflow
If there isn't enough space in the container, additional tabs should overflow into a menu:
![Tabs overflowing into a menu](https://user-images.githubusercontent.com/338257/99314465-64c9aa80-281e-11eb-9242-deef0b1d24c7.png)

##  Controllable State
Add ability for developers to observe and/or control state.

**Comment by myvuuu** [comment]
Can be broken down w/ spikes (into current sprint starting on 8/18). Breadcrumbs also needs similar features.

**Comment by myvuuu** [comment]
Pulled out of the sprint and replaced with something else
