### ISSUE TITLE
Document new component API patterns and guidelines

### ISSUE THREAD

**Issue by alanbsmith** [Workday/canvas-kit#920]
## 🔍 Spike /  Exploration

We've had a lot of internal conversation about how we want to evolve our component APIs, and we're now ready to document those. This document should be for our internal use and for external contributors.

## What questions would be answered once this spike was completed?

1. What are our standards for contributing new components?
2. What are the patterns and guidelines for building components in CK?

## Other Success Criteria?

1. Document should live in GH
2. Doc should be referenced in our GH issue template
3. We should discuss this internally
4. We should share this with canvas-kit consumers

## Does this relate to any existing issues?

No

**Comment by jpante** [comment]
Closed, doc'd as part of https://github.com/Workday/canvas-kit/blob/master/COMPOUND_COMPONENTS.md
