### ISSUE TITLE
Allow Labs Select to accept a prop for a custom render method for the selected option

### ISSUE THREAD

**Issue by jordandgold** [Workday/canvas-kit#924]
## 🚀 Feature Proposal

As it stands, the Labs Select component has a prop to pass a custom render method for each option in the select. Currently, this only works to change the options in the dropdown, but not the selected option that shows when the component is closed. This issue a request to add functionality to allow a custom render method for the selected option just like the options in the dropdown.

The current render prop (`renderOption`) used to render options in the dropdown is demonstrated [here](https://workday.github.io/canvas-kit/?path=/story/labs-select-react-top-label--default-with-custom-options-data) in Storybook. This proposal would extend this custom render functionality to the Select Button so the display of the selected option in the Button (when the dropdown menu is closed) could be customized as well.

## Motivation

This would support the designs for a feature I am working on.

**Comment by giulialubet** [comment]
I'd like to work on this!

**Comment by willklein** [comment]
Released in [v7.0.0](https://github.com/Workday/canvas-kit/releases/tag/v7.0.0)
