### ISSUE TITLE
Switch on change in firefox

### ISSUE THREAD

**Issue by psattiza** [Workday/canvas-kit#93]
## 🐛 Bug Report
Switch does not change state well on firefox
## To Reproduce

Toggle the switch in your app on firefox
## Expected Behavior
Nice animation (blue outline around switch component)

![Canvas toggle in chrome](https://user-images.githubusercontent.com/13973416/62740608-8752fe00-b9f5-11e9-90f2-7dfbe7170e3a.gif)

## Actual Results
Small square box pops under the switch
![Canvas toggle in firefox](https://user-images.githubusercontent.com/13973416/62740596-80c48680-b9f5-11e9-9c65-35f9a4dd953c.gif)
## Browser (if applicable)
Firefox 68.0.1 (64-bit) on mac os 10.14.5

**Comment by lychyi** [comment]
@psattiza Thanks for reporting. We will take a look!

**Comment by mannycarrera4** [comment]
Closing this issue seeing as it has been resolved in `v3.0.0-beta.0`
