### ISSUE TITLE
Stop Restricting Toast Children to String

### ISSUE THREAD

**Issue by TylerCharlesworth** [Workday/canvas-kit#932]
## 💡 Suggestion

[Canvas Kit > Popups > Toast](https://workday.github.io/canvas-kit/?path=/story/components-popups-toast-react--success) should allow `React.ReactNode` children as usual, not restrict to string children.

## Motivation

Toasts require children to be a string, presumably to avoid "bad behavior", people putting in images or something crazy. But we discussed (in an [internal thread](https://workday-dev.slack.com/archives/C8X0W5AQH/p1607387329388800)) and decided that it's reasonable to include semantics (more markup) in these Toast children.

## Example

```<Toast>New user <em>Chano Fernandez<em> successfully added.</Toast>```

**Comment by mannycarrera4** [comment]
Closing this. We've recently added a compound toast component that allows this: https://workday.github.io/canvas-kit/?path=/docs/labs-toast-react--basic
