### ISSUE TITLE
Update Storybook to solve Docs addon breaking Storybook Composition for certain prop default values

### ISSUE THREAD

**Issue by anicholls** [Workday/canvas-kit#933]
## 🐛 Bug Report

There is an issue with `Tooltip` and `react-docgen-typescript` that I have not been able to figure out. The docgen plugin is incorrectly detecting the default for the Popper `placement` prop as the window object, rather than `'top'`. We didn't notice this within the Canvas Kit storybook, but this causes an issue with Storybook Composition as it uses CORS. Attempting to serialize the `window` object of another frame throws an error.

Oddly enough, other Popper-based components with a `placement` prop don't have this issue. I'm still trying to track down why that is happening. Disabling the docs addon resolves the issue.

This error seems to be appearing from several different causes and is tracked here: https://github.com/storybookjs/storybook/issues/7215. Unfortunately there hasn't been much activity/response recently.

## To Reproduce

1. Start dev server or serve built storybook
2. Add local URL as a ref in a fresh storybook repo
3. Try to access a CK story in the composing storybook

## Attempted solutions

I have tried several solutions to no avail. Here are the things I've tried:

- Playing with the JSDoc `@default`. Neither `'top'`, nor `top` make a difference.
```tsx
  /**
   * Sets the placement preference used by PopperJS.
   * @default 'top'
   */
  placement?: Placement;
  ```

- Assigning default in function body, rather than in params destructure
```tsx
export const Tooltip = ({
  // ...
  ...elemProps
}: TooltipProps) => {
  const {placement = 'top'} = elemProps;
```

**The only way I've been able to get it to work is to remove the usage of the prop and force an assignment:**
```tsx
export const Tooltip = ({
  // ...
  ...elemProps
}: TooltipProps) => {
  const placement = 'top';
```

Obviously this is not something we can merge as consumers need to be able to control the placement of the tooltip.

### Error Output

 I get the error `Uncaught DOMException: Blocked a frame with origin from accessing a cross-origin frame.` at [this line](https://github.com/storybookjs/telejson/blob/master/src/index.ts#L352) whenever trying to load a story from the lower level "composed" storybook in the higher level "composing" storybook.

**Comment by anicholls** [comment]
Update: I've tracked down the problem in the Docs addon and opened an issue for it here https://github.com/storybookjs/storybook/issues/13608

**Comment by anicholls** [comment]
After another exploration, https://github.com/storybookjs/storybook/issues/13608 still isn't fixed and the issue needs to be reopened. Unfortunately moving this back to blocked and we'll still with a static build for Anthology for now.

**Comment by myvuuu** [comment]
@anicholls has this been resolved?

**Comment by NicholasBoll** [comment]
This does not seem to be an issue anymore for us. I'm closing.
