### ISSUE TITLE
Add support for space helper to component wrappers

### ISSUE THREAD

**Issue by anicholls** [Workday/canvas-kit#94]
## 🚀 Feature Proposal

A while ago we added support for easily customizing the margin and padding of component containers ([see here](https://github.com/Workday/canvas-kit/tree/master/modules/core/react#margin--padding)). We haven't done much with this, but we should be taking advantage of it in the container of most, if not all, of our components.

We may need to discuss restricting certain props in some way. For example, consumers should be able to adjust the margin around an avatar, but adjusting the padding doesn't make sense.

Pulled from https://github.com/Workday/canvas-kit/issues/51, but this is not breaking.

## Motivation

Many consumers need to adjust the spacing within/around the container element of our components. Currently they either have to use a wrapping div, or a `style` attribute - neither are ideal due to the extra markup they create. This API was created to add an easy way to adjust this spacing using normal props.

We should probably also standardize on the variable name used for these styled components as well (I'm thinking `Container`)

## Example

```tsx
import {space} from '@workday/canvas-kit-react-core';

// ...

const Container = styled('div')(space)<MyComponentProps>(
  // my styles
)

// ... 

export default class MyComponent extends React.Component<MyComponentProps> {
  // ...
  render() {
    const {myProp, ...elemProps} = this.props;

    return (
      <Container myProp={myProp} {...elemProps}>
        ...
      </Container>
    )
  }
}

// Consumer
<MyComponent p={spacing.xl} pb={64} m={40} mx={10}>
  ...
</MyComponent>
```

**Comment by jpante** [comment]
Closing this, as #771 aims to cover the motivation behind this feature proposal
