### ISSUE TITLE
Mark Page Header Component for Deprecation

### ISSUE THREAD

**Issue by jpante** [Workday/canvas-kit#942]
## 💡 Suggestion
Deprecate the Page Header Component by:

- [ ] Add deprecation warning in Canvas Kit / Storybook
- [ ]  Document deprecation reason in migration notes for 6.x

## Motivation
The Page Header component will no longer be supported by Canvas and will transition to UI Platform team. Page Header will still exist in v6, but will be marked for deprecation to prepare users for the migration/deprecation.

**Comment by alanbsmith** [comment]
Resolved with #1247
