### ISSUE TITLE
Move from enums to string literals

### ISSUE THREAD

**Issue by jpante** [Workday/canvas-kit#943]
## 🚀 Feature Proposal

Migrate enums to string literals across Canvas Kit. As part of this we should define and document string literal style.

For each change, we need to develop a code mod for easier migration.

## Example

"large" instead of Button.Size.Large

**Comment by aaroncalderon** [comment]
@jpante 

I am curious to know the reasons behind this initiative.

Personally, I can see the benefit when coding. Less code is better, right? 

But, can you offer any insight behind this?

Thanks.

**Comment by NicholasBoll** [comment]
@aaroncalderon There are some problems with enums:
- Different experience between Typescript and JavaScript. For example, `<Button size="s">` is valid in JavaScript, but not Typescript
- Issues with base interfaces. Enums do not place nicely with restricting or expanding allowed values in components.
- Lack of auto-complete for props. When you type `<Button size=`, there's no autocomplete for what comes next. You have to start typing `Button.Size.` to start getting auto-complete.

None of these problem exist for disjoint unions of string literals.

- #1017 - Removed enums from button components
- #1028 - Removed enums from card components
- #1029 - Removed enums from Popup components
- #1091 - Removed enums from Modal components
