### ISSUE TITLE
Add Preview and focus purpose of CK Labs.

### ISSUE THREAD

**Issue by jpante** [Workday/canvas-kit#944]
## 🚀 Feature Proposal

Add Preview as an added confidence level of CK components

**Preview** - Components that have the full design and a11y review, part of the DS ecosystem and are given the gold star to use in product. API's could be subject to change, but not without strong communication and migration strategies.

**Labs** - Curated experimental space. These components still need to meet the minimum requirement that it 'could be part of the core design system.'  Components here will incubate, to evaluate use-fullness and alignment to the CK vision but may not receive priority support.

## Motivation

Currently labs is a combination of primetime components and experimental components making labs a confusing space and some teams not wanting to pick components up that are ready for use. This approach will allow us to create clarity in the component promotion path.

## Notes

**Include notes on why a component is in labs in the readme.**

Migration of current components in CK Labs

- Breadcrumbs > Preview
- Color Picker > Preview
- Combobox > Labs
- Core - Space > Labs 
- Core - Type > Tokens - Type > Preview
- Drawer > Labs
- Header > Labs
- Cookie Banner > Labs
- Menu > Preview
- Pagination > Main
- Select > Preview
- Side Panel > Preview
- Tabs > Main

**Comment by anicholls** [comment]
Closed by #1069
