### ISSUE TITLE
Spike: CK Slash Imports

### ISSUE THREAD

**Issue by jpante** [Workday/canvas-kit#952]
## 🔍 Spike /  Exploration

Leveraging slash imports would allow us to have cleaner package imports for consumers. This is becoming even more relevant as we discuss the future of preview and labs in canvas kit. We should consider using rollup at the same time.

## What questions would be answered once this spike was completed?

1. What the level of effort is to implement slash imports for CK
2. Document a critical path to implementing slash imports across CK

**Comment by anicholls** [comment]
Closed by #922. Merged in https://github.com/Workday/canvas-kit/commit/340c8635710a04e4ec8a581b6f0bd5bd41e04287
