### ISSUE TITLE
Add closeButtonAriaLabel to Modal Component

### ISSUE THREAD

**Issue by UltraTempest** [Workday/canvas-kit#955]
## 🚀 Feature Proposal

Add closeButtonAriaLabel prop to Modal Component.

## Motivation

Allow for custom aria-label attribute on the close button for the modal.

## Example

`<Modal closeButtonAriaLabel="Example Label" />`

**Comment by NicholasBoll** [comment]
Solution is to add `closeButtonAriaLabel` to the props in `Modal`/`ModalContent` files and pass that props on to the `Popup` component used in `ModalContent.tsx`

**Comment by alanbsmith** [comment]
An interesting wrinkle here:
https://github.com/Workday/canvas-kit/blob/master/modules/popup/react/lib/Popup.tsx#L68
Modal uses Popup under the hood, and Popup has a closeButtonAriaLabel. But we’re not passing any of those props along to Popup.
https://github.com/Workday/canvas-kit/blob/master/modules/modal/react/lib/ModalContent.tsx#L223
