### ISSUE TITLE
Proposal for a Rocker component

### ISSUE THREAD

**Issue by devonsoto77** [Workday/canvas-kit#960]
## 🚀 Feature Proposal

Rocker Component. This feature is pretty simple in terms of UI and complexity. 

https://pt-storybook.s3-us-west-2.amazonaws.com/notification-designer/index.html?path=/story/components-rocker--simple

## Motivation

We had developers interested in our rocker component that came and asked about it. There is no deadline to get it in. 

## Example

We use it in a side Panel to control UI padding values. 

![Screen Shot 2021-02-04 at 9 46 30 AM](https://user-images.githubusercontent.com/17392486/106926027-e6b6ca80-66cd-11eb-92ce-f829d8f1748a.png)

**Comment by anicholls** [comment]
Hi @devonsoto77!

Your links don't seem to be working so I can't validate what you're referring to. I assume you're calling the attached icon buttons a "Rocker"?

If so, have you checked out our `SegmentedControl` component? 
![image](https://user-images.githubusercontent.com/908478/106926914-73f62100-66c6-11eb-8f0b-a92b25bd76a3.png)

Story: https://workday.github.io/canvas-kit/?path=/story/components-buttons-segmented-control-react--default
Code/Docs: https://github.com/Workday/canvas-kit/tree/master/modules/segmented-control/react

**Comment by NicholasBoll** [comment]
I'm guessing he's talking about 
![image](https://user-images.githubusercontent.com/338257/106927587-8de83180-66cf-11eb-8d56-411360f0977c.png)

**Comment by anicholls** [comment]
AH - somehow I totally missed that 🤦‍♂️  Nvm, carry on 😅

**Comment by myvuuu** [comment]
We will not be supporting a Rocker component in Canvas, this component is too product specific

**Comment by alanbsmith** [comment]
To add to what My said, we appreciate the proposal. We haven't found enough teams who also need this functionality to warrant adding it to Canvas Kit. If that need changes in the future, we would be happy to add this to our library. Cheers.
