### ISSUE TITLE
Modal: Convert to Compound Component

### ISSUE THREAD

**Issue by jpante** [Workday/canvas-kit#962]
## 🚀 Feature Proposal

Evolve modal to the compound component pattern (CCP). 

## Motivation

Modal is one of the most requested components for variants, evolving the modal to support the CCP will allow for increased flexibility and usability of the CK Modal component

## Related Issues

#905 feat(modal): Support scrolling entire modal
#756 Modal - allow aria-labeldBy prop to be passed
#786 Modal - full width and full height support
#681 More Modal variants
#790 Modal: Support scrolling entire modal / overlay for overflowing content.

**Comment by NicholasBoll** [comment]
Closed by #1091
