### ISSUE TITLE
Button API Changes

### ISSUE THREAD

**Issue by anicholls** [Workday/canvas-kit#97]
## 🚀 Feature Proposal

Button needs several breaking changes to bring it in line with our [API & Pattern Guidelines](https://github.com/Workday/canvas-kit/blob/master/API_PATTERN_GUIDELINES.md):

- Rename `buttonType` to `type`
- Rename `buttonSize` to `size`
- Rename all types to singular
- Rename all static variables to singular
- Re-evaluate prop spread behavior (let's discuss further)
- Make aria-label required for IconButton
- Consider scaling down `Small` `SquareFilled` Icon Button icon to match the other `Small` icon
- Fix the focus outline on square buttons to match others (it's the only one that doesn't have the white ring inside the blue) (see https://github.com/Workday/canvas-kit/pull/53#discussion_r312263943).

Ensure you document all breaking changes that are made in your PR.

Pulled from https://github.com/Workday/canvas-kit/issues/51 and will be a breaking change.

## Motivation

We want our APIs to be as consistent as possible and `Button` is currently one of the most divergent components. Let's bring it back in line by making these changes so our APIs feel more natural from one component to the next.

**Comment by lychyi** [comment]
> Rename buttonType to type

Unfortunately, `type` is a reserved keyword in TS. Can we use `variant` instead?

**Comment by lychyi** [comment]
> Re-evaluate prop spread behavior (let's discuss further)

@anicholls what were the discussion points around this?

**Comment by anicholls** [comment]
@lychyi It depends on how it's used (i.e. `const type = 'a'` works just fine). I don't believe the key for an object vs. the name of a variable would be any different, so I don't think it's reserved in this context. Will have to look into it though.

> Re-evaluate prop spread behavior (let's discuss further)
> @anicholls what were the discussion points around this?

Remember when we ran into an issue a few months back because `elemProps` was being spread on the container, the label icon and the label data? I don't remember exactly what it was, but I know it's caused us problems and it's definitely non-standard. Just something we may want to reconsider.

**Comment by anicholls** [comment]
@lychyi So after experimenting with it, there's no conflict with the TS `type` connotation. However, we do have  a conflict with the `React.ButtonHTMLAttributes<HTMLButtonElement>` type member (i.e. `<button type="reset">`. We should still support this, so I think we will have to go with `variant` for now.
