### ISSUE TITLE
Convert Button family to use `createComponent` helper

### ISSUE THREAD

**Issue by NicholasBoll** [Workday/canvas-kit#970]
## 💡 Suggestion

The `Button` component (and family) does not forward `ref` and has custom support for the `as` prop that doesn't document well. The `createComponent` helper fixes these issues.

The breaking change is the `Button` currently supports a `buttonRef` for ref forwarding vs a `ref` which currently points to the `Button` class. This change would mean `ref` points to the element instead of the class and the `buttonRef` prop goes away.

**Comment by anicholls** [comment]
And `Avatar` / `AvatarButton` 🙂

**Comment by anicholls** [comment]
Closed by #1017
